- src/bootchooser.c
> bootchooser: also set ramining_attempts for barebox

- src/install.c
Note that propagating errors from custom handlers ist not implemented yet
> Added error handling for handlers

- .travis.yml
* Use trusty (14.04 LTS) release of ubuntu to prevent package update
issues
* install packages non-interactive
> .travis.yml: fixup install

- src/main.c
- test/rauc.t
This provides several enhancements for the command line handling in rauc.
* Return non-zero exit code when command failed
* Better report invalid args
* Better help output 
* Command-specific help messages
* Tests for command line handling
* ...
> Improve command line parsing and handling

- include/config_file.h
- include/context.h
- src/config_file.c
- src/context.c
- src/install.c
- src/service.c
- test/bin/postinstall.sh
- test/bin/preinstall.sh
- test/bin/systeminfo.sh
- test/config_file.c
- test/install.c
- test/test.conf
- pre/post/systeminfo handler support and simple fixes
> handler support (pre/post/systeminfo)

- contrib/uboot.sh
- src/bootchooser.c
- src/config_file.c
- test/bin/fw_setenv
- test/bootchooser.c
> bootchooser: add support for uboot via fw_setenv

- src/main.c
> main: show sizes with the info command

- src/install.c
When booting from nfs, no valid active slot will be detected if nfs is
not mentioned in system.conf.
Ignoring this when seeing `/dev/nfs` in the command line will ease
working with rauc from nfs for testing and debugging purpose.
Signed-off-by: Enrico Joerns <mail@ejoerns.de>
> install: ignore missing active slot for nfs boots

- src/bootchooser.c
- src/bundle.c
- src/signature.c
This adds some fixes and enhancements for error handling conerning key / cert file parsing and handling.
It also corrects a warning message in bootchooser code.
> Error handling fixes

- .travis.yml
- Makefile.am
- configure.ac
- include/manifest.h
- src/main.c
- src/manifest.c
- test/rauc.t
- test/sharness.sh
This allows to select between different printout styles for `rauc info`.
> Add --output-format option for `rauc info`

- src/install.c
This both will provide more useful error outputs when working with the
network installation method and is a further step for making the bundle
and network install method more similar.
> install: Use GError in launch_and_wait_network_handler()

- docs/integration.rst
- docs/overview.rst
- docs/reference.rst
- docs/using.rst
- src/main.c
Also note about incomplete `rauc resign` implementation
> meta-ptx was renamed to meta-rauc

- src/bootchooser.c
Signed-off-by: Jan Remmet <j.remmet@phytec.de>
> bootchooser: put magic values in defines

- docs/integration.rst
> doc: integration: fix typo

- data/rauc.service.in
> rauc.service: let mountprefix point to systemd runtime dir

- CHANGES
- README.rst
- docs/contributing.rst
- docs/index.rst
- docs/reference.rst
* Adds contribution guideline
* Removes empty `file` section description
* Update CHANGES file
> Updates for Documentation and CHANGES file

- src/install.c
Add indication if pre or post install handler failed
> install: allow to differentiate handler error messages

- src/main.c
This patch makes progress and LastError information available from the
command line client that only printed
rauc-Message: installing /bundle.raucb: installing
installing `/bundle.raucb` failed
This will now make it be much more verbose, such as
rauc-Message: installing /bundle.raucb: 000% Installing
rauc-Message: installing /bundle.raucb: 000% Determining slot states
rauc-Message: installing /bundle.raucb: 020% Determining slot states done.
rauc-Message: installing /bundle.raucb: 020% Checking bundle
[...]
rauc-Message: installing /bundle.raucb: 050% Loading manifest file done.
rauc-Message: installing /bundle.raucb: 060% Verifying manifest failed.
rauc-Message: installing /bundle.raucb: 100% Installing failed.
rauc-Message: installing /bundle.raucb: LastError: Failed verifying manifest: …
> src/main: display Progress and LastError D-Bus properties in client

- Makefile.am
- configure.ac
- test/service.c
- test/services/de.pengutronix.rauc.service.in
This adds tests for installing rauc bundle via D-Bus.
The series includes the patch from #129 in order to make it succeed.
> D-Bus Testing

- docs/integration.rst
- docs/reference.rst
* add local tocs
* fix section levels
> Some structural fixups for documentation

- src/install.c
- test/bundle.c
* Remove excess variables
* Give test proper names
> Some minor code cleanups

- include/config_file.h
- include/manifest.h
- include/update_handler.h
- src/config_file.c
- src/install.c
- test/config_file.c
* clean ups and restructuring
* introduced and used `is_slot_mountable()` method
Note: This PR is based on #145 which should be merged first.
> Improve slot status loading and saving

- docs/integration.rst
> docs/integration: add links to barebox state user and dtb binding doc

- include/bundle.h
- src/bundle.c
- src/signature.c
- test/bundle.c
- test/common.c
- test/common.h
- test/manifest.c
This is the result of some prework done for several bundle-related changes.
> Set of fixes, cleanups and test restructuring for bundle handling and testing.

- include/config_file.h
- src/config_file.c
Some simple patches fixing small issues in the context of config/status files.
> Miscellaneous

- .travis.yml
* use apt addon
* use gcc-6 for testing
* fix coveralls exclude path
> Further Travis Changes

- docs/integration.rst
Latest questions on both the RAUC GitHub issue tracker and the mailing
list have shown that the current U-Boot integration description is too
unverbose and lacks some important hints.
This patch should improve the situation by giving more hints on what is
required and what is expected for letting RAUC interact with U-Boot.
> docs/integration: More verbose and helpful description of u-boot support

- docs/basic.rst
- docs/integration.rst
- typo fixes
- document additional buxysbox options for tar autodetection (see the actual commit message)
> docs: spelling and busybox updates

- include/install.h
- src/install.c
- test/install-content/custom_handler.sh
- test/install.c
This series prepares, introduces and tests a simplified and improved target slot selection handling as the current implementation had a couple of drawbacks.
It is also preparing structures that allow future extension regarding image selection.
Based on #158
> Rework Target Slot Selection and Image Matching Algorithm

- src/config_file.c
- src/main.c
- src/mark.c
These are 3 minor fixes / enhancements that have no relation to each other.
> Collection of a few minor fixes

- src/context.c
The kernel command line 'root' option allows to pass partitions via
PARTUUID=xxx instead of passing the real device path.
Despite preferring explicit information about selected partition (i.e.
slot) provided by the bootloader (e.g. via slot.rauc argument) we should
also support resolving PARTUUID to the corresponding real device path.
> src/context: support resolving PARTUUID to real path

- src/manifest.c
- test/manifest.c
make save_manifest_file variant aware
> save_manifest_file for variants

- src/install.c
- src/main.c
* Fixes progress step calculation
* Adds variant information to `rauc info` printouts
* Adds some useful logging output about variant usage
> Improvements and fixes for image variants

- src/update_handler.c
Up to now, we only supported ubifs images for ubivol slot type.
Handling ubifs to ubifs slot type is quite similar, with the difference
that we assume the slot to be mountable when executing pre- or
post-install hooks and thus use mount_and_run_slot_hook() instead of
run_slot_hook().
> src/update_handler: add support for writing ubifs to ubifs

- src/main.c
Allows to extract contents of a bundle to given destination folder
> src/main: add 'rauc extract' command

- src/context.c
> src/context: support root=UUID=

- README.rst
> README: add link to IRC and Matrix channel

- .uncrustify.cfg
- uncrustify.sh
This initial configuration tries to keep the changes as small as
possible.
> uncrustify: add configuration and helper script

- docs/reference.rst
- docs/using.rst
> docs: list and reference valid 'hooks' arguments in reference.rst

- docs/advanced.rst
Signed-off-by: Nicolas Di Pietro <potens1@gmail.com>
> Add of required parameters to create casync bundle.

- README.rst
- docs/reference.rst
Add methods Info, Mark and GetSlotStatus
> Dbus doc methods

- docs/advanced.rst
- docs/basic.rst
- docs/reference.rst
- docs/terminology.rst
- docs/using.rst
> docs: fix some minor spelling errors (mostly typos)

- .travis.yml
- configure.ac
- include/bundle.h
- include/config_file.h
- include/manifest.h
- src/bootchooser.c
- src/bundle.c
- src/checksum.c
- src/config_file.c
- src/context.c
- src/emmc.c
- src/install.c
- src/main.c
- src/manifest.c
- src/mark.c
- src/mount.c
- src/network.c
- src/service.c
- src/signature.c
- src/update_handler.c
- src/utils.c
Bump the required GLib version to 2.45.8 and use g_auto helpers for automatic cleanup.
> use g_auto helpers for automatic cleanup 

- docs/reference.rst
- include/config_file.h
- src/config_file.c
- src/install.c
- test/config_file.c
#221 rename `ignore-checksum` to `force-install-same`. `ignore-checksum` is further supported.
> Force install same

- README.rst
- docs/integration.rst
- src/bootchooser.c
Suggested-by: Michael Heimpold michael.heimpold@i2se.com
Fixes: #262
> docs: integration: document need for 'unsquashfs' tool for 'rauc info'

- docs/integration.rst
- src/bundle.c
- src/signature.c
- src/update_handler.c
This adds some fixes of issues revealed by static analyzers and humans.
* docs: better document fakeroot requirements
* src/signature: Initialize autoptr variable 'file' in cms_verify_file()
* src/bundle: warn if downloaded bundle could not be deleted
* src/update_handler: fix dead error checking code
> Various Fixes

- .travis.yml
- test/rauc.t
Adds minimal support on testing casync features.
> add casync tests

- src/bootchooser.c
bootnext might null
Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>
> src/bootchooser: fix segfault in efi_get_primary()

- docs/using.rst
> docs: using.rst: add chapter on how to debug RAUC

- src/install.c
- src/main.c
- test/install.c
- test/service.c
This aims to improve debug and error message reporting in cases where we can give more useful information but do not do yet or where information may be misleading.
It also removes redundant infos and fixes usage of correct printing function.
> More targeted debug and error messages

- src/context.c
- src/service.c
- src/utils.c
Some minor fixes I came across when testing for the 1.0 release...
> Minor fixes

- .travis.yml
- Makefile.am
- docs/conf.py
- docs/extensions/lexer/DtsLexer.py
- docs/integration.rst
- include/network.h
- include/signature.h
- src/context.c
- src/network.c
- src/signature.c
- test/fakerand.c
- test/get-coverity.sh
- test/manifest.c
- test/network.c
- test/rauc.t
- test/run-coverity.sh
- uml-test-init
- uncrustify.sh
This uses the custom build ejoerns/rauc-testing docker image for
running tests.
It aims to eliminate the current drawbacks (random errors probably caused by broken images) and pains we see when testing with Travis on current xenial (beta) environment.
Currently this uses my personal docker test environment build, thus we might want to move this to the 'rauc' GitHub user as well.
Fixes: #323
> Migrate to Using Docker for Testing

- docs/integration.rst
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
> docs/integration.rst: fix typo (s/DELPOY/DEPLOY)

- CHANGES
> Prepare for 1.0 release

- src/context.c
- src/install.c
> src: fix memory leaking gchar's returned by g_data_input_stream_read_line()

- CHANGES
- docs/examples.rst
> CHANGES: document final changes

- configure.ac
> Fix copy&paste typo in configure.ac

- docs/using.rst
- src/install.c
- src/update_handler.c
- test/update_handler.c
This adds passing some missing system and slot properties via env variables to hook scripts.
> Pass Variant and More to Hooks via Env

- src/main.c
- src/service.c
* Support mount point detection for symlinked devices in system.conf
* Propagate external mount points to the frontend (D-Bus / CLI)
> Fixes for external mount point detection and handling

- README.rst
- docs/integration.rst
* Some clarifications in README.rst
* Notes on required libraries (and versions) in integration chapter
* Note on Buildroot support in integration chapter
> Collection of some documentation updates

- README.rst
> README.rst: add lgtm badge

- docs/using.rst
Debugging chapter needs to be subchapter of using.
> docs: using: fix section level

- src/main.c
According to glib manual, g_variant_lookup() is a wrapper using g_variant_get()
internally, so the same GVariant format strings rules apply.
A format string "s" returns already a copy of the string while "&s" borrows
the memory. In our case, we pass the received pointers to g_strdup_*() functions
and thus we care about copying data ourself. So using "&s" instead
prevents leaking memory.
And on the second/receiving side, we pop the pointer from the queue and
have to free it now.
> Fix memory leaks in D-Bus notification callbacks (refs #426)

- Makefile.am
> Makefile.am: add docs images and extensions dir to EXTRA_DIST

- CHANGES
- docs/conf.py
> CHANGES: prepare for 1.1 release

- README.rst
> README.rst: fix two small typos

- src/mbr.c
- src/update_handler.c
This should fix the word size issues introduced by #435 and reported in #452.
> Fix compilation on ARM32

- src/emmc.c
when writing number of active boot partition to eMMCs EXT_CSD_PART_CONFIG register
> keep BOOT_ACK and PARTITION_ACCESS values 

- src/main.c
> src/main: add help text for 'service' (if configured)

- src/install.c
checking if a destination device exists, if a device is already,
mounted, if the source image is accessible, these are all things that
can be done *before* actually starting the installation, meaning *before*
we mark the slot as non-bootable and enter the atomic procedure of
updating.
It is really inconvenient to fail during installation with a failure we
could have discovered before actually starting the installation.
We use a working slot for nothing with the current implementation.
Thus, all what's pre-checkable is moved into the function
pre_install_checks() here that will be executed before marking the slot
non-bootable in the bootloader.
> src/install: check basic things before starting installation

- src/main.c
This adds a fix for false-positives in detection of output bundles inside input directory and an additional check that the input path points to a directory.
> Fix and enhance input/output path sanity checks for bundle generation

- docs/integration.rst
> docs/integration: some clarification on grub.cfg and grubenv placement

- docs/basic.rst
- docs/using.rst
Signed-off-by: Louis des Landes <louis.deslandes@fleet.space>
> Closes #520 - document bundle contents != manifest

- src/network.c
These lines caught my eyes while reviewing pull request #522.
> A handful of fixes for src/network.c

- src/install.c
- src/main.c
- src/manifest.c
- test/bundle.c
- test/manifest.c
This is a collection of minor things I came across when working on different RAUC topics.
The most significant change is the removal of some dead code in manifest handling.
> Collection of minor cleanups

- src/bundle.c
strlen() can potentially return values < 6 for emtpy or really short strings.
If we now substract the value of 6 without further checking, we end up
with a wrap of the unsigned size_t that effectively results in a very
very large value in size_t that will likely cause the memory allocation
in g_strndup() to fail.
Fix this by checking for string size being > 6 before and otherwise
always return 0.
> src/bundle: fix usage of g_strndup with strlen()

- src/update_handler.c
For this to work successfully the accompanying _casync_ has to be augmented by (the currently unmerged) _casync_ pull request [#227](https://github.com/systemd/casync/pull/227).
> Introduce casync based bundles to the update of UBI volumes

- include/context.h
- src/bundle.c
- src/context.c
- src/main.c
- test/rauc.t
> Allow custom mksquashfs with --mksquashfs-args

- docs/reference.rst
Closes: #534 
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
> docs/reference: clarify wording of BootSlot property contents

- include/context.h
- src/bundle.c
- src/context.c
- src/main.c
- test/rauc.t
I left the test as a separate commit, not sure whether it gives full coverage? Let me know if changes needed or you would like me to squash.
Thanks!
Closes #545
> Allow custom casync arguments with --casync-args

- docs/reference.rst
- docs/using.rst
This collects various adjustments related to the documentation of handlers and hooks as people still tend to mix things up.
Hopefully, this clarifies some aspects, cleans up things a little and becomes more concrete in some points.
> Documentation Update To Clarify and Clean Up Handler and Hook Usage

- README.rst
> README.rst: fix upper / lower case and typo

- src/bundle.c
Also make sure that resign does not overwrite existing files.
> src/bundle: remove output files consistently on error

- .travis.yml
- test/get-coverity.sh
- test/run-coverity.sh
This also makes it simpler to only run it on specific branches.
> use a separate travis stage for coverity

- rauc.1
The man page is currently a little bit outdated since new options were introduced for some commands, so update the man page accordingly.
While at, I stumpled over a formatting nitpick.
> Bring man page into shape again

- docs/faq.rst
This came up on the mailing list.
> docs/faq: document bundle format compatibility

- src/main.c
The CLI for the non-service configuration case was not well tested and has some printout issues this PR addresses.
> Fix install printout for non-service configuration

- docs/reference.rst
- rauc.1
I needed to re-read some documentation details and just stumbled over two minor issues.
> Small documentation fixes

- docs/faq.rst
> docs/faq: document hints for using RAUC with dm-verity-protected slots

- docs/examples.rst
- docs/integration.rst
- docs/using.rst
> docs/integration: add links and fix typos

- configure.ac
- qemu-test
- test/bootchooser.c
These fix some things I noticed on different development systems and prepare the qemu test environment for upcoming tests.
> test fixes and improvements

- docs/integration.rst
Just a little note in the docs that would have helped me a bit. Hopefully it will be useful to someone out there :smile:
> Added note in docs to restart the service after changing system.conf

- src/update_handler.c
Depending on the vfat implementation, vfat labels can be interpreted quite strictly, following the original specification.
This is why mkfs.vfat introduced more stricter sanity checks on label names with dosfstoolfs v4.2.
See also dosfstools commit 40da1b2c ("fatlabel: Implement proper checks when setting new label") for this:
https://github.com/dosfstools/dosfstools/commit/40da1b2c0129124f70fc0ec74363c699a3a479f8
Labels created so far by RAUC did not follow the FAT specification, too. This becomes actually more critical as recent mkfs.vfat now refuses vfat creation on the target.
This commit introduces `vfat_label_generator()` function that turns the slot name into a valid FAT label.
This also makes the prior string length check superfluous which was incorrect anyway as it tested for 16 …
> src/update_handler: generate only valid vfat label names

- src/install.c
The whitespace is not relevant for shell loops, but can be confusing
nevertheless. Remove it.
> src/install: remove trailing whitespace from RAUC_SLOTS and RAUC_TARGET_SLOTS

- src/update_handler.c
In dbd8f2df ('docs/advanced: clarify how boot-mbr-switch works') and 27c0bdf0 ('docs/advanced: update boot-gpt-switch explanation to "first/second half" wording') the documentation for MBR/GPT boot partition switching was clarified and made more precise.
However, the log output for these functions was not adapted and is thus misleading/wrong.
This is fixed here to reflect that we do not switch between different partitions but switch the location of the boot partition between the first and the second half of a defined region.
Also, adapt the variable name `inactive_part` to `inactive_half` for this.
> src/update_handler: adapt MBR/GPT boot partition switch terminology

- docs/contributing.rst
Signed-off-by: Alexander Dahl <ada@thorsis.com>
> docs/contributing: Fix typo

- docs/integration.rst
- include/utils.h
- src/utils.c
Minor fixes which accumulated when hacking on different things. Patches 1 and 2 are self contained. Patch 4 depends on patch 3, those two could be squashed if desired.
> utils: Misc fixes

- rauc.1
> manpage: briefly mention new extract-signature command

- src/bundle.c
This protects against the issue described in #819.
> src/bundle: download temporary bundle to a separate temp directory

- src/update_handler.c
As automatically closing of the fd is explicitly disabled, the fd needs to
be closed manually in case of any errors.
Signed-off-by: Christian Hitz <christian.hitz@bbv.ch>
Fixes #761
> src/update_handler: copy_raw_image() close out_fd in case of failure

- CHANGES
This collects the changes since the 1.5.1 release.
> CHANGES: prepare for 1.6 release

- README.rst
- test/network.c
- test/rauc.t
* Do not use unreliable example.com
* Check for openssl being present (skip related tests otherwise)
> Test Suite Adaptions

- test/run-coverity.sh
Since commit c7562c8 ("test/Dockerfile: Update the base image to the
latest Debian stable") coverty check fail.  Fix it.
> tests: use python3

- docs/advanced.rst
- src/de.pengutronix.rauc.Installer.xml
This PR fixes a few minor typos, no functional changes.
> Fix minor typos.

- src/bundle.c
- src/config_file.c
- src/context.c
- src/manifest.c
- src/signature.c
- src/utils.c
- test/signature.c
This is a collection of memory leak fixes.
Some were discovered by Coverity, some were discovered during work on other topics.
> Fix Some Memory Leaks

- include/dm.h
- include/verity_hash.h
- src/bundle.c
- src/dm.c
- src/verity_hash.c
- test/dm.c
* Introduces more convenient methods for verity creation and verification
* Renames dm module public methods to match common naming scheme
> Rename and Simplification of verity-related methods

- include/signature.h
- src/bundle.c
- src/signature.c
* Fixes memory leaks (adds more autoptr cleanup handling)
* simplifies / deduplicates code
* fixes error freeing
This is mainly fallout from adding cms handling for encryption.
> Collection of mostly signature-related fixes

- src/dm.c
- test/dm.c
Aligns with upcoming dm-crypt support.
> Minor fixes vor dm-verity handling and testing

- src/stats.c
- src/utils.c
* Fixes #871 
* Fixes 59653ab7
> (Re)Fix two Coverity-reported defects

- src/bundle.c
The cleanup logic meant to remove incompletely generated artifacts/bundles on error is wrong and thus also removes existing files under bad circumstances.
The current logic is based on always removing the generate output in case of an error, except when the file exists and the error was a `G_FILE_ERROR_EXIST` error.
The `G_FILE_ERROR_EXIST` error is thrown by explicit file existence checks in `truncate_bundle()`, `mksquashfs()` and `convert_to_casync()` functions.
The problem is, that these methods are not the first ones run in the respective output-generating methods. Most run `check_bundle_payload()` first for example. And if this fails, and the output path already existed, then this will just be silently removed.
An simple example of where this will hit you is when running:
rauc bundle …
> src/bundle: don't let existing bundles disappear

- README.rst
> README.rst: add required kernel options for streaming and encryption

- CHANGES
This brings the CHANGES file up-to-date.
> CHANGES: prepare for 1.7 release

- src/nbd.c
If the server does not provide the requested file, this won't likely
change on subsequent tries.
> src/nbd: no need to retry if we received a 404 from the server

- src/bundle.c
As part of the plain bundle ownership safeguard, RAUC attempts to chown bundles that are neither owned by root nor by the uid executing rauc to user root.
This cannot work when rauc runs as non-root. Thus emit a more helpful error message and abort in advance.
To not call `geteuid()` unnecessary often, introduce variable `euid` to store the result.
> src/bundle: do not attempt to take ownership if running as non-root

- src/update_handler.c
This adapts casync seed slot unmount handling to what is done in archive_to_*_handler() for slot unmount handling already.
This was split off from #774, as we can merge the simple fix for v1.8.
> src/update_handler: unmount seed also on casync error

- src/bundle.c
- src/update_handler.c
This fixes cases where users of adaptive updates can unexpectedly run into issues that not necessarily tell what is actually wrong:
* having adaptive mode enabled but no data directory configured in system
* trying to generate block hash index from archives
* knowing if and which adaptive method was selected
> Usability Improvements for Adaptive Updates

- docs/advanced.rst
- docs/basic.rst
- docs/faq.rst
We had some questions on how we handle forward and backward compatibility, so we should document our approach explicitly.
> docs: document our approach to bundle compatibility

- test/stats.c
On i387 floating point calculations can be quite surprising. The motivation for this change came from the observation that compiling and testing rauc-1.8 on the i386 Debian build machine had a failure on
g_assert_cmpfloat(r_stats_get_avg(stats), ==, 62.54615384615385);
. In that case r_stats_get_avg(stats) (when stored in a double typed variable) returned
0x1.f45e85e85e85fp+5
which is 0x1f45e85e85e85f00 / 2**55. However when stored in a long double typed variable it has the value
0x1.f45e85e85e85e85p+5
This value is 0x1f45e85e85e85e85 / 2**55 and so it has a significand that cannot be stored in the 53 bits that are allocated for double typed variables. 62.54615384615385 is a plain double and so evaluates to 0x1.f45e85e85e85fp+5.
This makes the comparison implemented in g_assert_cmpfloat() …
> test/stats: make tests involving floating point calculations more lax

- .github/workflows/coverity.yml
- .github/workflows/scan-build.yml
- .github/workflows/tests.yml
- README.rst
- data/meson.build
- docs/meson.build
- meson.build
- meson_options.txt
- qemu-test
- qemu-test-init
- scan-build
- scan-build-wrapper.sh
- src/update_handler.c
- test/Dockerfile
- test/meson.build
- test/rauc.t
This adds support for building RAUC with meson build system.
It also adapts CI tests to use meson instead of autotools.
Fixes: #829
> Add Meson Build Support 

- src/nbd.c
In streaming mode, RAUC currently assumes that libcurl is built with proxy suport. When configuring libcurl, it [tries to set `CURLOPT_HTTPPROXYTUNNEL`](https://github.com/rauc/rauc/blob/315d12bb37b4b0acf3ad2859cbc21816bd8a3e0a/src/nbd.c#L442) which will fail with libcurl without proxy support with `CURLE_UNKNOWN_OPTION` (48).
In a brief discussion, @jluebbe suggested to just ignore this case and give a hint in debug output.
> src/nbd: be lenient with libcurl without proxy support

- README.rst
This intends to better guide new users to recent features in RAUC.
> README.rst: Some Updates To Updates Scopes and Add Features

- docs/basic.rst
* note that combination with streaming serves as download optimization
* shorten and clarify the proper use case
* replace term 'hash' by 'checksum'
> Update slot skipping documentation

- src/config_file.c
- src/install.c
These are some things I came across while preparing for artifact updates.
> minor cleanups

- src/install.c
This allows obtaining the correct backing file for partitioned loop devices such as /dev/loop0p1 by using a regex match that cuts out the base loopN name.
Fixes: #631
Fixes: #1057
Closes: #1077
Reported-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Reported-by: Karsten Sperling Opdal <karsten.sperling.opdal@laerdal.com>
> src/install: support resolving partitioned loop devices

- src/install.c
`install_args_update()` was sometimes called with a static string and sometimes with a string allocated using `g_strdup_printf()`. In the latter case, this string was not freed.
Instead move the formatting into `install_args_update()`. As it needs its own copy anyway, this avoids the confusing alternative of a consuming the reference.
> src/install: fix string memory leaks

- include/utils.h
- src/utils.c
- test/utils.c
This will be used for artifact updates.
> utils: add helper to atomically update symlinks

- docs/advanced.rst
- docs/basic.rst
Meson was not mentioned and it might not have been clear that this is only a build-time option.
Fixes: #1132
> docs: clarify streaming build-time option

- README.rst
- docs/integration.rst
> point to distribution packages in the integration chapter and in the README

- src/context.c
- src/manifest.c
- src/signature.c
> Fix some leaks revealed when running sharness test with adress sanitizer

- .github/workflows/sanitizers.yml
- src/config_file.c
- src/install.c
- src/manifest.c
- test/install-fixtures.c
- test/install.c
> Fix leaks and enable address sanitizer for install-test

- .readthedocs.yaml
- docs/conf.py
- docs/requirements.txt
- test/Dockerfile
Should give nicer results when pasting links to the documentation into social media.
> add opengraph sphinx extension for social media preview 

- docs/requirements.txt
Regenerated using 'pip-compile requirements.in -U > requirements.txt'.
Closes: #1254
Closes: #1255
> requirements.txt: update to current versions

- Makefile.am
- docs/advanced.rst
- docs/reference.rst
- include/config_file.h
- include/event_log.h
- meson.build
- qemu-test-rauc-config
- src/config_file.c
- src/context.c
- src/event_log.c
- src/main.c
- test/config_file.c
- test/event-log.c
- test/meson.build
This is a first draft implementation of the event logging feature noted in concept issue #1070
> Configurable Event Logging

- .github/workflows/sanitizers.yml
- src/config_file.c
- src/event_log.c
- test/event-log.c
This fixes a number of smaller issues revealed by static code analysis and adds the event logger to the sanitizer CI job.
> Fixes for Event Logging (Static Code Analysis)

- docs/integration.rst
> docs/integration: recommend using stable paths in fstab and system.conf

- src/utils.c
- test/event-log.c
The issues were introduced since the last release.
> fix resource leaks and return value checks

- qemu-test
- qemu-test-init
This can be used with `git bisect run`.
> qemu-test: allow specifiying test to run

- docs/using.rst
Emphasize more that the hook script
* should be part of the bundle
* is invoked based on hooks= settings
* is responsible for multiplexing hook calls
> docs/using: be more specific about how hooks work

- README.rst
> README.rst: add repology overview image

- contrib/uboot.sh
Each project has different use-cases and trade-offs, so this script can only serve as an example how the selection logic could be implemented as a U-Boot bootcmd.
> contrib/uboot.sh: add note to explain that it needs to be adjusted to the use-case

- docs/examples.rst
Fixes meta-rauc-communit -> meta-rauc-community
> Fixes typo in documentation

- src/bundle.c
> src/bundle: fix double free

- include/update_utils.h
- src/update_handler.c
- src/update_utils.c
Depending on the situation, we want to write into existing devices (/files for testing) or make sure to create new files. Create separate functions for that.
> update_utils: refactor output stream

- include/manifest.h
- src/manifest.c
This prepares for additional checks related to artifacts.
> refactor manifest checks

- src/nbd.c
When invoking 'rauc info' the connection to the NBD server is never handed to the kernel and thus just terminated by the code in r_nbd_stop_server() that just closes the socket.
This leads to messages like
> rauc-Message: 23:00:27.704: nbd server failed with: failed to read request from client: Unexpected end of file
> rauc-nbd-Message: 23:00:27.714: failed to stop ndb server: failed to stop streaming subprocess: Child process exited with code 1
This can be handled better by manually invoking a nbd disconnect before that triggers a shutdown on NBD server side that prevents the error message and also prints stats etc.
> src/nbd: manually trigger NBD disconnect

- src/main.c
This is a collection of a few fixes/enhancements in the context of RAUC event logging.
> Fixes for Event Logging

- .github/workflows/codeql.yml
* Updates to codeql-action v3
* Filters out meson-private directories to prevent false positives.
> CodeQL Workflow: Update and Filter Results

- src/update_handler.c
The old one is inaccessible due to changed anchors. Also prefer HTTPS.
> src/update_handler: update link to emmc boot partition

- docs/integration.rst
Fix typo in the intro paragraph
> Fix typo the intro paragraph in integration.rst

- src/main.c
This should help when analyzing bug reports.
> src/main: log version and build config at debug level

- docs/integration.rst
- test/bin/barebox-state
- test/bin/fw_printenv
- test/bin/fw_setenv
- test/bootchooser.c
Hello,
I found several typo while I was digging the code trying implementing a new bootloader backend.
Feel-free to cherry-pick any one change you like and/or discard them.
Kind Regard,
Gaël
> Fix several typos

- docs/requirements.txt
Regenerated using './update-requirements.sh'.
Closes: #1387
> docs/requirements.txt: update to current versions

- README.rst
> README.rst: update license date to 2024

- test/Dockerfile
These will be required to run the pytest-based tests.
> test/Dockerfile: install pytest and pydbus

- src/signature.c
This lets us do better error checking and avoids some complexity in the functions where it is used.
> src/signature: add helper function to access a GBytes via a BIO

- test/conftest.py
faketime is currently incompatible with sanitizers, so mark it as unavailable if RAUC is built that way.
> test/conftest: skip faketime tests if a sanitizer is enabled

- CHANGES
> CHANGES: prepare for 1.12 release

- test/conftest.py
- test/test_install.py
- test/test_service.py
This improves the isolation between test cases.
> test: create system files using the tmp_path pytest fixture

- build-uncrustify.sh
- test/bundle.c
- test/install.c
- test/nbd.c
This only replaces some spaces with tabs.
> update to uncrustify-0.79.0

- data/rauc.catalog
> data: fix BUNDLE_VERSION variable in catalog entry

- src/utils.c
This only moves the declarations and no behaviour change is intended.
> src/utils: declare variables at the first assignment

- test/Dockerfile
This is useful when inspecting the state of artifact repos.
> test/Dockerfile: add tree utility

- qemu-test-init
- test/conftest.py
- test/helper.py
This helped with testing the artifact update code (#1301).
> minor updates to the test infrastructure

- test/conftest.py
This avoids pulling in backwards-compatibility baggage associated with dbus-launch and X11 autolaunching.
Based on a patch by Simon McVittie <smcv@debian.org> written for the old shell-based test setup.
Closes: #1502
> test/conftest: start dbus-daemon directly instead of using dbus-launch

- .codecov.yaml
Be less strict and ignore minor changes in coverage.
> add codecov yaml configuration file

- .github/workflows/tests.yml
These features are not related to each other, so two test runs should suffice.
> .github/workflows/tests: test with and without service and gpt features

- test/test_bundle.py
This seems to have a slight different flavor than 0.8.0 had. Adapt style to not have style check errors in unrelated PRs.
> test/test_bundle: update formatting to ruff 0.8.1

- docs/advanced.rst
- docs/contributing.rst
- docs/integration.rst
- docs/reference.rst
- docs/using.rst
* update the note on kernel-like coding style
* unify shell examples
* some typos etc fixed
> docs: some documentation updates and fixes

- test/test_extract.py
- test/test_info.py
- test/test_replace_signature.py
- test/test_resign.py
- test/test_verify.py
With 0.9.0, a number of string and f-string-related changes were introduced:
https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#090
> test: re-format pytest tests with ruff 0.9.1

- src/bundle.c
When pseudo is active, like it would be in a pseudo-enabled bitbake task, calling fakeroot is useless or can cause issues.
For this purpose, deactivate the call to 'fakeroot' when detecting an active pseudo environment.
We can simply leverage the existing `check_pseudo_active()` method which was introduced with adaptive update conversion handling.
While simply omitting the 'fakeroot' part of the call might looks a little hacky, it is the least invasive solution to the problem.
A cleaner, but more invasive solution would be to re-use the fakeroot env handling based on `r_fakeroot_*()` methods. However, this only works with true fakeroot and will fail when being called from a 'pseudo' acting as a 'fakeroot' like it is done in the 'meta-rauc' OE layer.
> src/bundle: casync_make_arch(): don't use fakeroot in pseudo

- src/main.c
Hello,
This should fixes two trivial leaking errors.
Regards,
Gaël
> src/main: fix leaking error

- .github/workflows/tests.yml
- CHANGES
- docs/integration.rst
- docs/reference.rst
- include/artifacts.h
- include/artifacts_composefs.h
- meson.build
- meson_options.txt
- qemu-test-init
- src/artifacts.c
- src/artifacts_composefs.c
- src/bundle.c
- subprojects/composefs.wrap
- test/bundle.c
- test/common.c
- test/common.h
- test/conftest.py
- test/install.c
- test/install_fixtures.c
- test/meson.build
- test/test_artifacts.py
Based on #1301, add support for composefs artifacts.
> add support for composefs artifacts

- src/update_handler.c
* simplifies control flows by removing gotos
* unify some input argument checks
> Minor Update handler cleanups

- README.rst
- test/conftest.py
- test/test_mark.py
> test: migrate from pydbus to dasbus

- README.rst
- docs/conf.py
> update license and copyright date to 2025

- CHANGES
The composefs PR added the change description to the 1.13 section by mistake.
> CHANGES: prepare for 1.14 release

- docs/advanced.rst
This will add the greengrass reference to the docs.
> advanced.rst: add aws greengrass

- docs/integration.rst
> docs/integration: document tar requirements for artifact repos

- docs/integration.rst
And link to the class variable description.
> docs/integration: clarify the RAUC_BUNDLE_FORMAT variable

- rauc.1
> rauc.1: add missing 'rauc install' arguments

- include/context.h
- src/context.c
This replaces some assertions with more explicit error messages regarding context and progress handling, and adds some hints to make the progress handling more accessible to developers.
> context and progress handling improvements for development

- src/signature.c
- test/signature.c
These are just some minor cleanups which will make it easier to add/review support for multiple bundle signatures.
> signature: prepare for multiple signature support

- .github/workflows/tests.yml
- README.rst
- src/context.c
- test/test_http.py
Instead of running the test suite only on the Debian release used to build our CI container, also run them on the different distros and releases in the stable matrix. I'll build on this with a patched OpenSSL to test the multiple signature handling next.
Also fix some minor issues found while preparing this PR.
> run test suite for various distributions
