rauc/rauc

include/signature.h
src/install.c
src/signature.c
test/signature.c

signature.c: Fix and add error handling
* Added error handling for cms_file
* Added missing error reporting for in cms_verify_file() when return
value indicated an error (led to assertion errors)
* Used literal error reporting function where possible
install: Propagate mount errors to the user
* Also fixed some error prefixing strings

signature.c: Fix and add error handling

---

src/config_file.c

set res to FALSE in case of an error if there is no function that could
set res itself. Otherwise the return value of the surrounding function
will not match the detected error.

config_file.c: Fix error handling

---

Makefile.am
src/manifest.c
src/signature.c
test/broken-manifest.raucm
test/config_file.c
test/manifest.c

* signature.c: Add missing error set for bytes_from_bio() call
* manifest.c: provide named error codes for manifest errors
* manifest.c: Fix error handling for invalid compatible

Fix and enhance manifest error handling

---

src/manifest.c

Comparing compatible is a much shorter task than checksum verification.
Thus it should be done first to allow rejecting as early as possible

manifest: Check for compatible before verifying checksums

---

.travis.yml

Fixes travis build fail caused by utopic universe/multiverse repositories
removed from archive.ubuntu.com

.travis.yml: Move from utopic apt repository to vivid

---

src/install.c
test/install.c

barebox bootstate sets the selected boot target vi kernel commandline
parameter `bootstate.active`. This is now used to determine the boot
slot if `bootloader=barebox` was selected in the system.conf.

install.c: add handling for barebox bootstate commandline parameter

---

include/bundle.h
src/bundle.c
src/install.c
src/main.c
test/bundle.c

Note: This patch stack is based on the command line handling patch stack
* `rauc info` shows more details of a bundle (manifest)
* Only the manifest file is extracted from squashfs, to save disk space
* Option `--no-verify` allows to check bundles without certificate check
Example output of `./rauc info --no-verify test/good-bundle.raucb`:
** Message: checking manifest for: test/good-bundle.raucb
** Message: system config not found, using default values
** Message: Compatible String:	'Test Config'
** Message: 2 Images:
** Message: (1)	rootfs.img
** Message: 	Slotclass: rootfs
** Message: 	Checksum:  de2f256064a0af797747c2b97505dc0b9f3df0de4f489eac731c23ae9ca9cc31
** Message: (2)	appfs.img
** Message: 	Slotclass: appfs
** Message: 	Checksum: …

bundle info enhancements

---

include/bundle.h
src/bundle.c
test/bundle.c

This fixes the defect reported by coverity which would have lead to uninitialized size parameter passed to r_mount_loop(). The pr also adds a check for extract_file_from_bundle().

fix coverity defect

---

test/bundle.c
test/checksum.c
test/config_file.c
test/install.c
test/manifest.c
test/network.c
test/signature.c

Otherwise locale is set to the current system locale, which will result
in making tests for expected warning messages fail as the string
comparison will not match.

tests: set locale to "C" to fix warning message tests

---

include/config_file.h
src/bootchooser.c
src/config_file.c
test/config_file.c

Otherwise a failure of r_boot_set_state() will not be propagated.

main: handle return code of r_boot_set_state() in status mark-good/bad

---

include/utils.h
src/main.c
test/common.c
test/common.h
test/install.c

When running `rauc info` or executing test, a lot of artifacts were left in the /tmp directory.
This and some surrounding issues (such as lack of documentation of utils.h) are fixed by this PR.

Fix tmpdir cleanups and add utils.h documentation

---

src/install.c

This fixes two cases where steps that were begun may not be ended correctly.

progress step fixes

---

src/main.c

The main purpose of g_message() is logging, not end-user output.
Additionally it outputs to stderr when using the default handler.
Thus, use g_print instead, which simply outputs plainly to stdout.

main: Use g_print() for printing bundle information

---

src/install.c

Slots that do not have a bootname (and those that have a parent) are not
meant to be handled by the r_boot_set_* routines for boot source
switching.

install: perform r_boot_set_* only for slots with bootname

---

src/bundle.c
src/install.c
src/mount.c

There should be a space between the prefix string and the original error
message to ease reading it.

fix some GError propagation prefix strings

---

Makefile.am
src/install.c
test/common.c
test/common.h
test/config_file.c
test/install.c

The algorithm is able to handle multiple cases where the former one
failed.
Now it is allowed to chains parent relation in slots, i.e.
rootfs  <-----  appfs  <----- demofs
parent         parent
The former algorithm was also very focused on having a single parent and
all other slots being childs of one of them.
Now it is possible to update multiple slot classes not connected to each
other and also to have slot classes with only one member, while others
have more than one.
The returned GHashTable now has references to RaucSlots as data, while
the keys remain the target class names.

New determine_target_slots algorithm

---

src/bootchooser.c

Marking a slot good resulted in giving it a fixed priority of 20.
This may make the slot non-booting if it owned a higher priority before.
The behavior of setting slot priority to 0 for marking a slot bad
remains untouched by this change as it does not conflict with other
priorities.

bootstate.c: do not set priority for marking slot good

---

src/config_file.c
src/install.c
test/config_file.c

To make the bootname checks for updating bootloader status working, no
default bootname must be set.

config_file: do not set bootname if config did not provide any

---

src/main.c

GVFS needs the session bus for remote protocols and we don't use it.

main: disable gio vfs support

---

src/main.c
test/rauc.t

Commands must be chained with `&&` in order to let the tests fail
correctly in case of an error. Otherwise the error code of the
previously executed command would be overwritten by the next.
This also fixes a bug in `rauc status` that was hidden due to the ignored tests.

rauc.t: fix rauc test command chaining

---

src/bundle.c
src/install.c
src/main.c
src/mount.c
src/service.c
src/update_handler.c

This will prevent the client handlers from accessing args when might
have already been cleared.
This fixes a segfault that occured while rauc terminated with an error
code.
And, this should also fix the following error:
| Unexpected error from C library during 'pthread_mutex_lock': Invalid
| argument.

install: disconnect all signal handlers that use args before destroying it

---

src/main.c

Otherwise the assertion in install_args_free() that status_result is >=
0 will wail. Fixed by reducing scope of args allocation and freeing.

main: assure args->status_result is set before freeing args

---

src/main.c
test/rauc.t

The installer should fail earlier and more verbose when trying to
install a bundle with an invalid name or non-existing path.

main: in case of local bundle, check for extension and existence

---

src/signature.c

The genreic error message "signature error" is too unspecific to debug
issues with certificates. The Openssl library routines provide routines
to for getting more precise error codes and messages which are used
here.
A side-effect of this is that the openssl library does not print error
messages in its own format directly to screen, but only through the
normal rauc error reporting mechanism.

signature: obtain verbose error string for CMS_verify() failures

---

src/mount.c

It proved handy to automatically create the parent directory for the mount points. While adding this the permission "issue" was noticed.

automatically create mount prefix and more conservative permissions

---

src/install.c

Errors in launch_and_wait_default_handler() that occur before beginning
step `update_slots` should skip termination of this step in their
error-out path.

install: fix termination of `update_slots` step

---

Makefile.am
configure.ac
include/install.h
include/network.h
src/install.c
src/main.c
test/install.c

Unconditionally depending on libcurl adds a lot of dependencies that are
not required for most of raucs operation modes.
Thus this patch introduces a `--disable-network` configure switch.

allow to disable network support for not using libcurl

---

src/manifest.c
test/install.c
test/manifest.c

This adds checks for unparsed keys and groups  in the manifest file. This allows manifest file authors to earlier detect issues caused by using invalid or misspelled key / group names.

Check manifest for unparsed content

---

include/bundle.h
src/bundle.c
src/install.c
test/bundle.c
test/common.c
test/common.h
test/install.c
test/manifest.c

This is some pre-work for further test setups that fixes some issues, reduces a little bit of code duplication and extend tests by some newly added one and some more tested details.
* Adds test for some error paths in bundle checks
* shares common code in bundle test routines
* Tests if updates actually write content
* Add a little bit of test description

Extend tests

---

configure.ac
include/config_file.h
include/install.h
include/manifest.h
include/update_handler.h
src/config_file.c
src/install.c
src/manifest.c
src/update_handler.c
test/bundle.c
test/common.c
test/common.h
test/install-content/hook.sh
test/install.c
test/manifest.c
test/manifest.raucm
test/update_handler.c

This patch series introduces hooks to rauc.
In contrast to handlers, hooks can be specified from your respective installation bundle and will be executed only for the current installation.
All hooks run from a single script which gets the hook name passed as a parameter. All further informations required will be passed via environment variables as known form handlers.
Hooks need to be registered explicitly. Some may work on a per slot/image base while some may perform more installation-global operations.
Currently introduced hooks are:
Per slots
* pre-install
* post-install
* install
Per update
* install-check
An example of how to specify them in the manifest:
```cfg
[hooks]
filename=hooks.sh
hooks=install-check
[image.rootfs]
filename=...
...
hooks=pre-install;post-install
```

Introduce Hooks

---

src/bundle.c

`sigsize` is of type guint64 and thus should be printed using
`G_GUINT64_FORMAT` instead of `G_GSIZE_FORMAT`.
This led to compilation errors on some systems.

bundle: fix format specifier for printing sigsize

---

src/install.c

The variable `slotstatuspath` is initialized after mounting the target
slot when reading the slot status file for checking if we can skip the
update.
If mounting the target slot for reading the slot status path failed
(which is uncritical as it might have been a virgin or broken slot) but
the image update ran successfully and we attempt to write the new status
file, the variable `slotstatuspath` will not be set, yet.
Thus it has to be set after the second mount too in case it is still
NULL.

install: slotstatuspath may not be set when trying to write status file

---

src/bundle.c

Accidently calling rauc with a valid squashfs file but not a valid bundle, could lead to:
``` sh
rauc info /path/to/file.squashfs
(rauc:30892): GLib-GIO-CRITICAL **: g_input_stream_read_all: assertion 'buffer != NULL' failed
(rauc:30892): GLib-CRITICAL **: g_propagate_error: assertion 'src != NULL' failed
(rauc:30892): GLib-CRITICAL **: g_propagate_error: assertion 'src != NULL' failed
Segmentation fault (core dumped)
```

fix null buffer issue when extracting signature from bundle

---

src/main.c
test/rauc.t

This introduces a `output-format` optional parameter for `rauc status` which allows to select the desired printout style.
This will be helpful to either get human readable or parsable output.
Currently supported formats are:
* human readable
* shell-parsable
* json
* json-pretty (with line breaks and indention)
Note that having 'json-glib' on the system is required for building with json support. The configure switch `--disable-json` allows building rauc without json support.
This obsoletes PR #26

rauc status: allow to choose output style

---

include/manifest.h
src/manifest.c
test/manifest.c
test/update_handler.c

This version of glib changed an error message for key-file errors and checks for duplicate test paths. This triggered some errors when running the tests that will be fixed by these two patches.

Fix test errors with glib 2.49

---

src/main.c
test/rauc.t

This adds support for printing registered bundle and slot hooks when
calling `rauc info` for all available output formats.

main: print hooks in rauc info

---

src/install.c

The progress information for a skipped slot installation was 'Copying
image' so far. To not irritate a Progress log reader, this should be
changed to something clearly indicating that image copying was skipped
as rauc detected that the slot already contains the desired revision.

src/install: Explicitly mention that slot was skipped in progress

---

src/install.c

There is no guarantee that we will be able to mount raw slots and write
status information to it, thus this step should be skipped.

install: skip slot status update for raw slots

---

src/main.c
test/rauc.t

The compatible of the device rauc is running on is an information of
certain interest for both user of rauc and possible scripts.

main: show compatible in output of rauc status

---

include/context.h
src/install.c
src/main.c

This allows to install a bundle with a different compatible, e.g. for
making a generic board with a standard factory image a board with
product-specific rootfs.

introduce rauc install --ignore-compatible switch

---

README.md
docs/conf.py
docs/integration.rst

This extends the chapter 'integration' with informations about bootloader integration and rough PTXdist integration.
It also removes some remaining occurences of lowercase RAUC in documentation.

Even more documentation for RAUC

---

src/service.c

g_bus_own_name is an async call, we can't immediatley set the idle state
afterwards since we potentially haven't aquired the bus name yet. Move it into
r_on_bus_aquired to set it before exporting our properties to the bus name.
Signed-off-by: Rouven Czerwinski  <r.czerwinski@pengutronix.de>

service: move set initial idle state to r_on_bus_aquired

---

docs/using.rst

use correct upper and lower case for dbus interface and method/property
Signed-off-by: Jan Remmet <j.remmet@phytec.de>

doc: using: dbus case sensitivity

---

src/install.c

If the pre-install handler fails we errorneously goto out instead of goto
umount, leaving the mount-directory on the filesystem. Fix it by using the right
goto directive if the pre-install handler fails.
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

install: fix mount-directory removal on pre install handler error

---

data/de.pengutronix.rauc.service.in

Exec argument must call rauc with the `service` argument in order to let
it spawn the service. Otherwise d-bus activation will fail and the
client reports:
Error creating proxy: Error calling StartServiceByName for de.pengutronix.rauc: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
D-Bus error while installing `/home/root/update-2017.02-1.raucb`

Fix Exec argument to start service

---

configure.ac
src/context.c

Currently, releases cannot be built with invoking autoreconf as `git-version-gen` is missing in distribution.

Build fixes

---

src/config_file.c
test/config_file.c

Return an error instead of interpreting a typo in the readonly key's value as
"false".

config_file: enhance parsing boolean "readonly" key

---

src/signature.c

As in CMS_sign() also in CMS_verify() the CMS_BINARY argument must be
set in ordert to make libcrypto handle the data as binary data.
Note that since OpenSSL 1.1.x this really makes a difference in handling
and a missing CMS_BINARY flag will result in a verification error:
140573172512064:error:2E09D06D:CMS routines:CMS_verify:content verify error:../crypto/cms/cms_smime.c:393:
Fixes: #115

signature: add missing CMS_BINARY to CMS_verify flags

---

src/bootchooser.c

Just a minor simplification.
Shouldn't those defines be typed constants instead anyway?

Use C's string concat instead of runtime copy

---

include/context.h
include/install.h
src/context.c
src/install.c
src/main.c
test/common.c
test/common.h
test/install-fixtures.c
test/install.c
test/rauc.t

* Adds `--override-boot-slot` cmdline argument to allow faking a detected boot slot
* Moves bootslot detection to context

Allow passing booted slot via cmdline and context

---

README.rst

It must be content-dir/manifest.raucm instead of content-dir/manifest.
Also, specifying sha256 and size is unnecessary since that will be
overwritten anyway.
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>

README: Fix example

---

src/service.c

This fixes a bug introduced by 7b27396055062ffbdb10a182d08465ed1f825f9d
where the call of `r_installer_set_operation()` was moved without moving
the associated call of `g_dbus_interface_skeleton_flush()`.
If not flushed, notifications for property updates will happen in and
idle loop. Thus multiple property updates might get aggregated.
If the same property is updated multiple times before a notification is
sent out, this will result in status update informations being lost.
A case where this could be observed quite often where the installation
status messages updates that randomly dropped some sub-steps from the
report.
Note that when introducing more fine-grained status updates (e.g.
reporting image write progress, progress updates may be performed
intentionally without calling the …

src/service: flush dbus interface to not drop property updates

---

docs/using.rst

It is not the boot that gets marked, it is the slot.

docs: using: adjust description of mark-good/bad

---

Makefile.am
data/de.pengutronix.rauc.service.in
data/rauc-service.sh.in

On systemd-less systems the rauc service is started by dbus on request.
Since dbus differs from systemd in that it doesn't setup a proper
environment, a wrapper is installed to setup the path before starting
rauc.
The wrapper script sets the path to be
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
which is similar to what systemd sets up.
Without this, rauc installs fails when calling e.g. `fw_setenv` from
u-boot to set the boot order, and when calling `mkfs.ext4` to install
tarballs on ext4 slots.
Signed-off-by: Martin Hundebøll <mnhu@prevas.dk>

dbus: use wrapper when starting rauc service

---

test/service.c

This one needs to be set on the server side, not on the client side.
Thus pass it via cmdline arg.

test/service: fix setting mount path prefix

---

src/bootchooser.c
src/bundle.c
src/checksum.c
src/config_file.c
src/context.c
src/install.c
src/main.c
src/manifest.c
src/mount.c
src/network.c
src/service.c
src/signature.c
src/update_handler.c
src/utils.c

Arrangement of include directives in source files was more or a result of constant development than of wisely chosen and grouped order. Also usage of local and global includes was mixed. On the one hand this this was simply untidy, on the other hand this resulted in real issues, such as #137.
This series addresses this issue and cleans up and fixes the includes.

Cleanup include directives

---

src/main.c

Some misleading argument number parsings were fixed and commands now can print a summary giving a brief description of what they will do.

Fix and enhance command line handling

---

include/network.h
src/network.c
test/network.c

downloading files from network did not provide any GError functionalities nor did fail on severe issues, such as getting 404 from a webserver.
This adds at least a few basic constructs to allow obtaining error information from `download_file()`.

network: allow basic error handling

---

src/bundle.c

--no-verify is meant to be a flag for disabling signature verification
check, not for entirely disabling bundle checking.
Despite the check_bundle() function already provides a 'verify' argument,
it was called only in case of 'verify' diabled. This is now replaced by
calling check_bundle() unconditionally.
For this, the check_bundle() function had to be fixed to honor the 'verify'
argument when deciding if a missing keyring file would break bundle
checking or not.

src/bundle: fix handling of rauc info --no-verify

---

include/context.h
src/context.c
src/main.c

When using rauc info, for example a keyring file is required in order to
be able to verify the bundle signature.
The keyring could only be configured from the system configuration file
which meant that you had to have a system.conf on your build host if you
wanted to use rauc info properly.
As a system.conf on the build host is not useful and could be
error-prone, thus a keyring argument for the RAUC CLI really simplifies
using rauc info and other possible commands requiring a keyring file.

src/main: add keyring command line argument

---

Makefile.am
docs/reference.rst
docs/using.rst
include/config_file.h
include/mark.h
src/config_file.c
src/install.c
src/main.c
src/mark.c
src/rauc-installer.xml
src/service.c
test/config_file.c
test/rauc.t
uml-test-init

Today RAUC bundles are copied to the local filesystem, then installed via `rauc install <PATH/TO/BUNDLE.raucb>` and finally the system is rebooted into the new software.
Additionally support for the following use case is needed: after installation the freshly installed slot is not activated automatically, but only after an explict decision made by a user. Before this activation reboots shall only start the old slot. This comes from practical demands of a service technician who wants to push new software to some dozens of systems at the same time, but take them into operation individually and under supervision.

activate-installed & mark-active

---

include/bundle.h
include/signature.h
src/bundle.c
src/install.c
src/main.c
src/manifest.c
src/service.c
src/signature.c
test/bundle.c
test/signature.c

This series performs some refactoring of bundle handling functions. It introduces a `RaucBundle` structure to support passing configuration and meta information to bundle handling functions.
These changes form the base for the also included extraction of certificate and trust chain information obtained during bunde verification.
`rauc info` will now print trust chain information if signature verification succeeded.
A new option for `rauc info` ( ``--dump-cert``) lets you dump useful certificate information about a bundle.
Series is based on PR #152 and #153

Support for extracting and dumping certificate and trust chain info

---

include/context.h
include/signature.h
src/context.c
src/install.c
src/signature.c
src/update_handler.c

This series adds functions for extracting public key hashes of certificates involved in signing and the trust chain.
This potentially allows to perform decisions about key chains to use on the target depending on which certificate was used to sign the bundle. A common use case for this is to switch from a development-key-signed bundle to one signed with a release key without changing the bundle content.
Based on PR #154

Support for extracting and handling SPKI hashes

---

src/signature.c

#159 
gcc version 4.9.2 (Raspbian 4.9.2-10)
Signed-off-by: Caglar Kilimci <ckilimci@gmail.com>

Type-casting is needed to compile on Raspberry Pi

---

.travis.yml

Prior Travis build slaves seem to have provided this by default.
Now it is missing and causes the rauc.t service tests to fail.

.travis.yml: manually install dbus-x11 to have dbus-launch

---

.travis.yml

Latest coveralls is incompatible with default urllib3 version installed.
This currently breaks coveralls checks in Travis as coveralls aborts
with a stack trace noting:
```
...
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'
```
Adding upgrade triggers pip to use the latest version of urllib3.

.travis.yml: use --upgrade in pip install cpp-coveralls

---

src/update_handler.c

slot is already mounted, so call run_slot_hook
Signed-off-by: Jan Remmet <j.remmet@phytec.de>

update_handler: fix post install hook in tar_to_ubifs_handler

---

include/config_file.h
src/config_file.c
test/config_file.c

If we cannot find a parent that is configured, continuing will lead to
unintended behavior and slot handling. This must be avoided!

src/config_file: not finding a configured parent must be fatal

---

docs/integration.rst

v2017.03 contains patches required to work with recent state versions.

docs/integration: add note about minimum required dt-utils version for RAUC

---

src/install.c

function 'get_all_file_slot_classes()' is only used by
'launch_and_wait_network_handler()'.
Thus it leads to a compile error if the static function is defined
unconditionally.

src/install: fix build without network support

---

.travis.yml

vivid repository was removed and apparently user-mode-linux package is
fixed in trusty so we do not have to fetch it from a separate repository
anyway.
Thus, simply install it (and grub-common) from the trusty repository

.travis.yml: remove vivid apt repository

---

docs/using.rst

This small improvement has been discussed on the mailinglist (see thread "mark-active" from December 2017) and enhances the understanding of 'rauc status mark-active booted' to avoid misunderstandings.

docs/using: clarify usage of 'rauc status mark-active booted'

---

.travis.yml

We already have GCC 7 which might find more issues by improved compile-time checks. Thus enable it for testing.

.travis.yml: use gcc-7

---

m4/ax_code_coverage.m4

former version was incompatible with lcov 1.13

configure: update ax_code_coverage.m4 from autoconf-archive master

---

docs/integration.rst

Barebox chooses the boot target via boot.default not via bootchooser.default.
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

doc/integration: fix wrong variable name in barebox integration

---

include/bootchooser.h
src/bootchooser.c
src/install.c
src/mark.c
test/bin/barebox-state
test/bootchooser.c
test/install-content/custom_handler.sh

This series targets different issues in Barebox bootchooser (boot selection layer) implementation.
The two main ones are:
* This is one of the components that still lacks appropriate GError handling, giving us only insufficient information about failures
* barebox-state backend did not properly handle disabled slots for setting slots as primary. This also additionally requires reading state info instead of only writing it

Fixes and error handling rework for RAUC boot selection layer

---

include/bootchooser.h
src/bootchooser.c
src/main.c
test/bootchooser.c

A long-living inconsistency in RAUC is the behavior and purpose of `rauc status`.
While the sub-commands of `rauc status`, which are `mark-good`, `mark-bad` and `activate` all deal with changing the state of the underlying boot selection implementation, a call of `rauc status` does not provide any hints on the state of the bootloader.
Instead it only prints out the base system configuration with a few runtime info, such as mount points.
This series (based on #191 and #179) adds support for obtaining and displaying bootloader status as provided by the RAUC boot selection abstraction layer.
The information provided is:
* slot currently selected as primary (i.e. the one that will boot the next time)
* status of each slot (if they will potentially booted), referred to as 'good' or 'bad' at …

Obtain and Display bootchooser status

---

src/install.c
src/mark.c

Adds printout and returning of new error messages provided by the bootchooser layer to `rauc status mark-{good,bad,active}` and the normal installation process.

Use GError messages now provided by bootchooser layer

---

src/config_file.c

When we cannot mount, the should be no need for umounting. Furthermore,
if we call r_umount_slot() without having successfully passed
r_mount_slot() results in not having slot->mount_point set and makes
RAUC crash because of a sanity check on slot->mount_point being non-NULL
in r_umount_slot().

src/config_file: do not unmount when mounting fails in save_slot_status()

---

docs/using.rst

There simply is no handler called 'install' defined. The description
refers to the full custom handler that can be specified in the bundle
manifest. Intentionally, there is no equivalent in system.conf

docs/using: remove bogus 'Install Handler' rubric

---

README.rst
configure.ac
docs/index.rst
docs/integration.rst
src/bootchooser.c
src/config_file.c
test/bin/efibootmgr
test/bootchooser.c
test/config_file.c
test/system.conf

This series adds support for handling EFI-based booting on x86 machines.
It calls and parses output of the `efibootmgr` tool to modify and read the EFI variables required for boot order modification.

Add EFI bootchooser backend for x86

---

src/context.c
src/install.c

Especially in cases where standard device paths (such as /dev/sdb) are
not persistent over reboots, one might need to use symlink pathes
generated by standard or custom udev rules. A good example for this are
the /dev/disk-by-* symlinked device paths.
As RAUC uses the device path to string-compare against the `root=`
kernel command line argument it will not match against a system config
slot entry with a symlink device path such as
[slot.rootfs.0]
device=/dev/disk/by-path/pci-0000:00:17.0-ata-1-part1
...
This patch resolves this by calling `realpath()` to always get the
canonicalized absolute pathname of the `device` parameter when comparing
against boot slot device name as provided by root= kernel command line.

Support resolving device symlinks using `realpath()` for more flexible matching

---

src/bootchooser.c

g_data_input_stream_read_line may return NULL but leave the error
argument unset to indicate there was no content to read.
In this case we must not try to propagate an unset error but generate an
appropriate error message ourselves.

src/bootchooser: fix g_data_input_stream_read_line error handling

---

src/bootchooser.c

Some EFI implementations might choose to have a default EFI boot entry
always placed on first position in order to execute it first and then
continue selecting the next boot target to boot the actual system.
In this case, the simple approach on looking at the first element in
EFI BootOrder for finding the primary slot will not work.
Also having BootNext set must not necessarily mean that this will match
one of the bootnames handeled by RAUC.
A more generic approach for this would be to scan the entire BootOrder
list until finding the first element we know as a bootname for any of
our slots configured and consider this to be the primary one.
The patch changes the efi_get_primary() method to gain this behavior.

src/bootchooser: support re-sorted EFI boot entries in efi_get_primary()

---

include/manifest.h
src/install.c
src/manifest.c
test/bundle.c
test/manifest.c
test/service.c

Step by step this removes the code from `verify_manifest()` by either moving or simply dropping it.
While doing this, some drawbacks and issues of the current handling are resolved while preparing code for cool new features.

Rework manifest verification handling

---

Makefile.am

Packaging the dbus wrapper script renders the corresponding .in file useless.
@bindir@ is ignored making the systemd service fail if the rauc binary
location differs from the packaging host.
e119229 ("Makefile.am: do not package data/*.service") fixed this for
all .in files in data until then. This bug was introduced later on.
Fixes: dcd184d ("dbus: use wrapper when starting rauc service")

Makefile.am: do not package data/rauc-service.sh

---

include/config_file.h
src/install.c
src/mount.c

This makes mount handling more explicit and also allows to (bind) mount
slots that are already mounted which will be required by further RAUC
features.

src: replace RaucSlot mount_internal by ext_mount_point

---

docs/advanced.rst
docs/examples.rst
src/main.c
test/rauc.t

If called with a slot name and image the image is written to the device
corresponding to the slot. This is useful for development purposes and
initial board provisioning.

Add sub command 'write-slot'

---

docs/using.rst
src/main.c
test/rauc.t

There hasn't been a way to get hold of a slot's status information (which bundle has been used to install it, when has it been installed last, has it been activated, ...). Now this data can be extracted via ``rauc status --detailed`` supporting all present output-formats to have it machine-parsable if required.

Add option  "--detailed" to rauc status

---

docs/advanced.rst
docs/reference.rst
include/bundle.h
include/config_file.h
src/bundle.c
src/config_file.c
src/install.c
src/main.c
src/update_handler.c

This series of patches adds support for using the [casync](https://github.com/systemd/casync) tool for image and archive installation.
By using casync, way we gain a couple of cool new capabilities:
* Direct streaming of Updates from remote servers (without intermediate download of images)
* Binary Delta-like Updating to reduce network load (e.g. for constrained links)
* Simpilified and storage friendly artifact pooling on deployment server side
* CDN friendly chunk fetching
Creating a casync-supporting bundle is a two-step process:
1. Create your conventional RAUC bundle
2. Convert it
rauc convert old-bundle-raucb casync-bundle.raucb
This will create a `casync-bundle.raucb` bundle file (only containing index files instead of real images)  and a separate casync chunk store …

Introduce casync support

---

src/update_handler.c

This adds support for writing a .vfat image (which should be a valid
extension for a vfat image) to a vfat slot by using the img_to_fs_handler.

src/update_handler: support vfat to vfat

---

src/main.c
src/service.c

gsize should be printed with type G_GSIZE_FORMAT to prevent build warnings:
src/main.c: In function 'r_status_formatter_readable':
src/main.c:972:34: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'gsize {aka unsigned int}' [-Wformat=]
g_string_append_printf(text, "\n              size=%lu", slot_state->checksum.size);
^
src/main.c: In function 'r_status_formatter_shell':
src/main.c:1067:26: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'gsize {aka unsigned int}' [-Wformat=]
str = g_strdup_printf("%lu", slot_state->checksum.size);
^

src/main: fix format argument for printing gsize in status formatters

---

src/mark.c

Discard the explicit check as g_clear_error() does it implicitly.

src/mark: do not check for ierror twice

---

Makefile.am
include/network.h
src/bootchooser.c
src/bundle.c
src/checksum.c
src/config_file.c
src/context.c
src/install.c
src/main.c
src/manifest.c
src/mount.c
src/network.c
src/service.c
src/signature.c
src/update_handler.c
src/utils.c
test/common.h
test/install.c

This should ensure that we don't forget to include it.

Makefile.am: include config.h via CPPFLAGS instead of in each file

---

Makefile.am
README.rst
docs/advanced.rst
include/emmc.h
src/emmc.c
src/update_handler.c

This enables atomic updates of eMMC boot partitions for bootloaders:
- read active boot partition
- empty the inactive boot partition
- set inactive boot partition rw
- write bootloader to inactive partition
- set inactive boot partition ro
- set inactive boot partition active
- check that the previous inactive boot partition is active now
Also the docs were restructured and now reflect the first bootloader update possibility via RAUC.

Add support for updating eMMC boot partitions 

---

.travis.yml
Makefile.am

Fixes out-of-tree builds for newly introduced config.h handling and disables coverity that showed some strange behavior in Travis over the last builds.

Fix out-of-tree build and temporary disable coverity

---

include/config_file.h
src/config_file.c
src/main.c
src/service.c

I want to get the output from "rauc status" also vie dbus.
GetSlotStatus sends only the "detailed" status information in terms of "rauc status --detailed"
Is this the right place for this information or should it go to an own method?

Dbus getslotstatus entries

---

contrib/uboot.sh

Meerly fixing a small typo in contrib/uboot.sh.

Fix typo in uboot.sh, vaild instead of valid.

---

contrib/uboot.sh

Command 'expr' is not available, use setexpr instead.
Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>

contrib: fix uboot.sh example script

---

docs/advanced.rst

The required patch went mainline in the meantime. Mention explicit version numbers to make things easier.

doc: advanced: mention explicit kernel versions with fixed mmc ioctl

---

src/signature.c
test/signature.c

Interfiles does not have to be NULL. When passing these intermediate certificate files from the commandline this should not fail.
Signed-off-by: Marcel Hamer <marcel@solidxs.nl>

Remove assertion on interfiles

---

docs/reference.rst
docs/using.rst

Point the reader towards the D-Bus API from the installation chapter, add a separate D-Bus API subchapter to explain bundle installation, and add pointers to the API reference from there.
Stress that the Install() is non-blocking and the installation is finished when the "Completed" signal is emitted in both places.

Clarify bundle installation D-Bus API

---

docs/integration.rst

The example system.conf for UEFI integration was missing 'slot.' before each slot which causes rauc to fail to recognise any slots.
Signed-off-by: Philip Downer <phil@pjd.me.uk>

docs/integration: Corrected the UEFI system.conf example

---

.gitignore

In 23a287f ("Makefile.am: Fix gdbus-codegen for VPATH builds") the
generated D-BUS interface code was moved from ./src to ./ .

gitignore: fix location of rauc-installer-generated.[ch]

---

src/emmc.c
src/update_handler.c

From `open()` man page:
| on Linux 2.6 and later, O_EXCL can be used without O_CREAT if pathname
| refers to a block device.  If the block device is in use by the system
| (e.g., mounted), open() fails with the error EBUSY.
This will prevent us from erroneously writing devices that are already
mounted or used at the moment of opening.

src: open device path with O_EXCL to assure exclusive access on block device

---

src/emmc.c

Kernels up to (and including 3.3) forgot to include types.h in their
mmc/ioctl.h, and thus __u32 (and others) are not defined, causing
compilation errors:
http://autobuild.buildroot.org/results/621/621587906bd2bb27c43b6fcbb051d75f20e32e7c/build-end.log
Fix that by explicitly including types.h before mmc/ioctl.h.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>

emmc: add workaround for older kernels

---

README.rst
docs/integration.rst
src/bundle.c
src/update_handler.c

Always call tar extract with --numeric-owner option to preserve original
user and group IDs as packed into the archive.
This is required to assure reproducible and deterministic IDs that are
also consistent with the password file and prevent from later user
relabeling that would cause issues in the context of trusted boot.

src: preserve original uig/gid during tar extraction

---

src/install.c

935346f replaced the function `r_boot_set_primary()` with the function
`mark_active()`. While `r_boot_set_primary()` returned a gboolean that was
assigned to the return variable 'res', mark_active() does not.
As `res` will have been set to `TRUE` by the code flow before, this
absolutely requires to set 'res' manually to `FALSE` in case of an error
of `mark_active()`.
As this was missing, the installation was reported successfully even if
the actual slot activation failed.
This patch now fixes the return value of
`launch_and_wait_default_handler()` in case of a failed `mark_active()`
call by setting `res` to `FALSE` manually.

src/install: fix invalid return value in case of failed mark_active()

---

src/bundle.c
src/signature.c
test/rauc.t

* adds certificate validity times to chain printout
* removes incomplete (unsigned) bundles on error
* avoids extra newlines in g_warning() outputs
* removes bundle created in tests

Some unrelated fixes and enhancements

---

src/update_handler.c

This is a more generic approach of #278 as it fixes `fsync()` handling in `copy_raw_image()` directly which itself is used by different handlers.

Add fsync to copy_raw_image()

---

docs/reference.rst
include/config_file.h
src/bundle.c
src/config_file.c
test/config_file.c

At the moment, a hard-coded BUNDLE_DL_MAX_SIZE define is
used for a safety check when a bundle is downloaded.
To be more flexible at runtime, introduce a new config
parameter 'max-download-size'.
The current define is used as default value when the
config setting is not specified.

Introduce max-download-size config setting (fixes #287)

---

src/bootchooser.c
test/bin/fw_printenv
test/bin/fw_setenv
test/bootchooser.c

This fixes some minor inconsistencies in RAUC'S boot selection code but mainly adds support for stateful `fw_setenv`/`fw_printenv` testing as preparation for further implementation and fixes, e.g. as introduced by #293.

Advanced Testing for U-Boot and Minor Boot Selection Fixes

---

docs/faq.rst

The ability to use RAUC in non-D-Bus mode is not very well documented.
Thus we add at least a little hint in the FAQ to mention it despite we
do not want to encourage people to use RAUC that way if not mandatory.
Fixes #227

docs: add minimal hint on --disable-service in RAUC faq

---

include/utils.h
src/config_file.c
src/manifest.c
src/utils.c
test/config_file.c
test/manifest.c

This Fixes #225 by applying the same checking for inavlid groups and keys as we do for bundle manifests already.

Strict parsing of RAUC config files

---

src/bootchooser.c
test/bootchooser.c

This implements the `r_boot_get_state()` and `r_boot_get_primary()`
interface for the U-Boot bootloader.
The expected handling is implemented similar to what other bootloader
do. Both the `BOOT_ORDER` and `BOOT_x_LEFT` variables are taken into account
to determine the state of a slot and the primary one.
Replaces #293

Support obtaining slot status and priority for U-Boot

---

.travis.yml

The line installing it was unintentionally deleted in
af015f699d8b1e02ce0068787056d4f462a6e011. Now we re-add it to fix coveralls notification.

.travis.yml: re-add missing cpp-coveralls

---

src/install.c

Use convenience function g_propagate_prefixed_error() to not throw away
error message in case of R_INSTALL_ERROR_MARK_BOOTABLE.

install: propagate error in mark_active()

---

src/install.c

determine_slot_states() is called during rauc service start, slot status
retrieval and 'rauc mark'. These code paths are not part of an
installation and should not be decorated with steps ultimatively leading
to an update of the 'Progress' and 'Operation' D-Bus properties:
$ busctl get-property de.pengutronix.rauc / de.pengutronix.rauc.Installer Progress
(isi) 100 "Determining slot states done." 1
Fix this by calling r_context_begin_step()/r_context_end_step() in
do_install_bundle() and do_install_network() just before and after
determine_slot_states() is called.

install: move determine_slot_states step to calling install methods

---

Makefile.am
configure.ac
src/update_handler.c

The eMMC boot partition support, added in commit
ea5cc7ff606c65536da218bd1ef6d0ca279c9b17 ("src/update_handler: add
support for updating eMMC boot partitions"), requires
<linux/mmc/ioctl.h>, only available starting from kernel headers 3.0.
Even though it is pretty likely that people are going to use Linux >=
3.0 on their embedded systems these days, RAUC also needs to be built
natively on the build machine to produce update artifacts, and the
build machine is sometimes using an ancient Linux system, especially
in an enterprise contexts.
In order to make sure that RAUC builds fine in this context, this
commit makes the eMMC boot partition support optional, by verifying
the availability of <linux/mmc/ioctl.h>.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

build: make eMMC boot partition support optional

---

src/install.c

Otherwise, a manifest containing an image for e.g. both a rootfs and an
appfs will install successfully also if the target system does not have
an appfs configured.
This is against the rule of RAUC of being unambiguous in the
installation description.

src/install: Not finding an appropriate target slot must be fatal

---

src/update_handler.c

My image is formatted as `squashfs` and at first I could not perform an update via `rauc install`.
With the help of this changeset, setting `RAUC_IMAGE_FSTYPE=squashfs` and setting the slots type to `raw`, it was then possible to update the slot.
Do you have any experience using `casync` to update a `squashfs`-based slot ?

update: add squashfs to raw handling.

---

src/install.c
src/main.c
test/install.c
test/rauc.t

So far we had the slot config booloan key `readonly` that allows to mark
a slot as being detected but not being writable by RAUC.
But, this option was only of informational nature and did not really
prevent from accidently installing content to a slot marked as readonly.
This patch now slightly extends the target slot selection algorithm to
actually care about the readonly flag by not adding the slot to the
hash map of target slots.
This way it will not be possible to install data to 'readonly' slots,
but they are still considered e.g. for parent slot detection, etc.
An extra test to assure this was added.
Fixes #161

src/install: actually handle readonly slots

---

docs/using.rst
include/signature.h
src/signature.c
test/rauc.t
test/signature.c

To detect signing errors and expired certificates early, this series adds trust chain verificiation during creation of a bundle if the  `--keyring` argument is provided or a keyring configured.
Additionally a check is implemented to warn the signer about using certificates in the chain that will expire within the period of a month.

Add Support for Verifying Signature During Bundle Creation

---

docs/reference.rst
docs/using.rst
src/install.c
src/update_handler.c
test/install-content/hook.sh

I wrote a post-install handler and was a little surprised to find that there was not RAUC_SLOT_TYPE_x variables. While figuring out where to add such logic I stumbled on some unrelated stuff; I'm happy to make those into a separate PR if requested.

export slot type to handlers and hooks

---

src/main.c

We need to call g_object_unref directly with a pointer to the object.

src/main: fix freeing of RInstaller

---

src/install.c
test/install.c

This is the initial step of deprecating the unused and
slightly outdated RAUC network (non-bundle) mode.
If someone actively uses this mode (Note: Affects only 'real' network mode, without bundles, not the remote functionality of RAUC)

src/install.c: Add network mode deprecation warning

---

docs/advanced.rst
docs/integration.rst
docs/reference.rst
docs/using.rst

Called like that:
codespell -i 3 -w docs/**/*.rst
Signed-off-by: Alexander Dahl <ada@thorsis.com>

docs: Fix typos found by codespell

---

test/rauc.t

The certificate expiry tests previously just failed if faketime is not installed.
With this PR, we first check if faketime can be executed and skip them otherwise.

test/rauc.t: check if faketime is available

---

docs/reference.rst
src/bootchooser.c
test/bootchooser.c

This is a collection of several patches related to the bootchooser.c code as a result of originally only trying to add `BOOT_ORDER` handling to the U-Boot implementation.
As some of the design decisions of bootloader interaction are not that intuitive, I decided to add a new section to the reference part of the RAUC documentation for at least bringing a little light into the darkness.
The return handling fixes are part of the rework I promised (but still owe) @michaelolbrich when he acknowledged the g_autoptr patches of @pH5.

Bootloader Interface Fixes, Enhancements and Documentation

---

docs/reference.rst
include/config_file.h
include/mount.h
src/config_file.c
src/mount.c
test/common.c
test/config_file.c

Allow passing custom slot config options to RAUC's slot mount calls.
This fixes #281.

Add extra-mount-opts slot config key

---

include/context.h
src/context.c
src/install.c

Let progress objects allocate and free their strings themselves and do not leave this to the other levels.
By also introducing a printf-style printout function this prevents producing memory leaks by allocated but non-freed strings when creating progress messages.
This addresses the issues noted in #341.

Rework progress step allocation and freeing

---

include/bundle.h
include/network.h
src/bundle.c
src/install.c
src/main.c
src/network.c
test/bundle.c
test/network.c
test/rauc.t

In #264 and other discussions the question came up if the current way of forcing a `.raucb` extension for RAUC bundles is really required.
Background is that some may simply want to hide how they update, do not like the extension or have other requirements in their infrastructure that needs them to use a special extensions.
However, the main reasons that RAUC forces a `.raucb` extensions is to be explicit what we want to handle as a bundle, but the more to have a distinction between the historical RAUC 'network mode' that uses manifests instead of bundles and the conventional bundle mode that is effectively the one-and-only today.
When removing the need for a `.raucb` extensions, this does not mean we encourage everyone to use whatever extension he likes, but, we allow it. Note that it is …

Remove need for .raucb extension

---

docs/reference.rst
src/rauc-installer.xml
src/service.c
test/service.c
test/test.conf

Make system information availabile via dbus. This adds the properties
Compatible, Variant, and Bootslot
Signed-off-by: Jan Remmet <j.remmet@phytec.de>

service: add system info properties

---

src/main.c

Fixes 2 issues on the client side:
* boot status is displayed inverted
* bootname for primary slot is unavailable

Fix Issues with Slot Status Over D-Bus

---

test/Dockerfile

This will be used by the Docker Hub autobuild to build the rauc/testing
docker image that will be used for RAUC's Travis CI runs soon.

test: add Dockerfile

---

src/main.c
src/service.c
test/rauc.t

So far, even if a call of 'rauc service' failed with
Failed to obtain name de.pengutronix.rauc
the service returned exit code 0, indicating everything is fine.
This will be fixed now.

Fix service error return handling

---

README.rst

As we use codecov.io now for generating coverage reports, we should also
use its badge.

README.rst: replace coveralls badge by codecov.io badge

---

src/main.c
test/get-coverity.sh
test/rauc.t
test/run-coverity.sh

* Remove redundant tests
* Add more testing
* Revealed that excess args do not result in exit code != 0

Some extensions and fixes for rauc.t argument handling testing

---

src/context.c

We use the 'system_variant' key as a temporary storage for the filename
the key should be derived from.
No matter if we succeed with that or not, we must assure the key is
replaced afterwards.
With the current handling, in case for example get_variant_from_file()
failed and returned NULL, we do not overwrite 'system_variant' which
leads to having the variant set to the path to the filename we wanted to
read it from. This is clearly wrong.
We can simple fix this by setting the context 'system_variant'
unconditionally. Then it gets either the value 'NULL' (unset) or the
right value.

src/config_file: fix: always overwrite temporary system_variant

---

src/bootchooser.c
test/bootchooser.c

This mainly fixes the barebox boot selection handling for cases where we update a slot class from another as this is usual the case in asymmetric scenarios.
To prevent from breaking this, some test were added.

Fix boot selection handling for asymmetric update scenarios.

---

src/install.c

print_slot_hash_table() is only used within the network handling code,
thus when having this disabled this static function is unused and will
produce a warning that is fatal when compiling with -Werror.

src/install: fix building with --disable-network

---

docs/advanced.rst
docs/examples.rst
docs/reference.rst

This provides some useful examples for common slot configuration scenarios and hopefully slightly clarifies the handling of `bootname` slot config keys.
Fixes #368

Slot Config Examples And More Explicit `bootname` Handling

---

src/bootchooser.c
test/bootchooser.c

Equivalent to how barebox_get_primary and efi_get_primary do it.
Fix bootchooser test to cover this case properly. The test covered this
case before already, but because it used R in BOOT_ORDER without also
specifying BOOT_R_LEFT the test case failed differently hiding the missing
error reporting on the absence of a primary slot.
Fixes #386.

src/bootchooser.c: Report error on missing primary slot in uboot_get_primary

---

src/signature.c

The current code tries to handle tm_mon wrapping, but fails to
increment tm_year - also, there's no handling of, say, March 31 ->
April 31, making the resulting broken-down time invalid, in which case
timegm() need not produce a sensible result.
Instead of doing these fragile computations on a struct tm, just add
30 days to now.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>

src/signature.c: make a-month-from-now computation more robust

---

src/main.c

Otherwise this leads to an assertion error in g_hash_table_destroy()
when `RaucStatusPrint` population was aborted early, e.g. due to missing
access to D-Bus.

src/main: free_status_print(): free slots hash table only if existing

---

src/context.c

This targets to be a replacement for the implementation in #366 as requested by @jluebbe.

Support specifying system variant via system-info handler

---

docs/reference.rst
include/config_file.h
src/bootchooser.c
src/config_file.c

This adds the efi-use-bootnext option that allows disabling the default
BootNext setting for marking a slot primary as this may be inappropriate
for use cases where the BIOS already handles the slot switching
properly.
For these cases, simply sorting the slot as the first element in the
bootloader is more appropriate.

Introduce efi-use-bootnext option to change primary-marking behavior

---

docs/reference.rst
include/config_file.h
src/config_file.c
src/update_handler.c
test/config_file.c

This adds a `resize` slot option that will trigger a call of `resize2fs` after having written an ext4 image.
The use case for this is having an image smaller than the actual partition size where the file system should span the entire partition afterwards.

Add option for automatically resizing written ext4 images

---

include/checksum.h
include/utils.h
src/checksum.c
src/manifest.c
src/utils.c
test/checksum.c

This is preparation for allowing multiple files to go into computing the sha256, cf. #325 . From this, it would mostly be a matter of figuring out how one would pass a list of file names and perhaps provide convenience functions for passing a single file. It also tries to fix something I've noticed a couple of times: That memory use of the RAUC process temporarily goes through the roof during an update.
For now only compile-tested, as I don't have any boards handy, and it is anyway mostly a POC.

Preparations for multi-file-checksums

---

include/config_file.h
src/config_file.c
src/main.c

* Show slot name in 'Booted from' line
* Do not dump misleading status output on mark-* commands

Two useful improvements for 'rauc status'

---

src/bundle.c

'input_stream_check_bundle_identifier()' calls 'g_set_error()' when
'bytes_read != sizeof(squashfs_id)', but the format specifier is
incorrect.  It uses "%lu" for 'bytes_read' (of type 'gsize'), and for
'sizeof(squashfs_id)' (of type 'size_t').  Use "%"G_GSIZE_FORMAT for
'bytes_read' and "%zu" for 'sizeof(squashfs_id)' to avoid compiler
warnings.
Signed-off-by: Ian Abbott <abbotti@mev.co.uk>

src/bundle: Correct a g_set_error() format specifier

---

src/bootchooser.c
test/bin/grub-editenv
test/bootchooser.c

Previously, GRUB2 was supported only for writing (setting state or setting primary slot).
I have implemented `grub_get_state()` and `grub_get_primary()` so that now `rauc status` shows valid slot information, e.g.:
```
root@localhost:~# rauc status
Compatible:  x86_64
Variant:     (null)
Booted from: A
Activated:   rootfs.0
slot states:
rootfs.0: class=rootfs, device=/dev/sda1, type=ext4, bootname=A
state=booted, description=, parent=(none), mountpoint=(none)
boot status=good
rootfs.1: class=rootfs, device=/dev/sda2, type=ext4, bootname=B
state=inactive, description=, parent=(none), mountpoint=(none)
boot status=good
```

src/bootchooser: added full GRUB2 support

---

include/utils.h
src/main.c
src/utils.c

This will lead to undesired behavior such as endless loops or having
bundle artifacts inside the bundle.
Fixes #21

Check that we do not generate a bundle inside a source dir

---

Makefile.am
rauc.1

Every good tool should have a manpage, at least as a first pointer
to further documentation.
This is mostly in preparation for Debian packaging since we
earn a lintian warning otherwise.

Add an initial version of a man page

---

src/main.c

1)
According to documentation g_get_current_dir() returned string should
be freed when no longer needed. So use a g_autofree decorated variable
to buffer the returned pointer.
2)
g_filename_from_uri() allocs memory for the hostname component if found.
But in this case (hostname != NULL) we leave the funtion with return
which does not free (the now assigned) hostname.
We can use g_autofree decoration to fix this without the need to care
about explicitely.

Fix memleaks in resolve_bundle_path (refs #426)

---

data/rauc-service.sh.in

Apart from avoiding the small memory overhead of a pointless persistent process, this also ensures signals, etc are sent to the rauc process and not the shell wrapper.

tail-call real rauc process

---

build-aux/git-version-gen

As discussed in PR #377, updating the git-version-gen script to the
latest upstream version should fix the erroneous substitution of '-'
with '.'. This should allow us to build -rcX releases without any local
modifications.
This version is from commit 9447bd9732613c5419611bcb2b8b304d748b62b6 in
the repository https://git.savannah.gnu.org/git/gnulib.git.
Fixes: #357
Suggested-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>

git-version-gen: update to latest upstream version

---

src/bootchooser.c

When getting an error while calling barebox state on a slot that has a
bootname set, this should always fail.

bootchooser: a failure in calling barebox_state should be propagated

---

.uncrustify.cfg
src/context.c
src/network.c
src/signature.c
src/utils.c

This is the de-facto default we use in the entire code except for a very
few cases where not yet. We fix them now.

.uncrustify.cfg: enforce space between if and '('

---

contrib/grub.conf

With recent changes to the grub integration (#384) the variables exported by grub.cfg in contrib should also include A_OK, B_OK and ORDER.

contrib: grub: export additional variables to environment

---

docs/integration.rst
src/install.c

This will allow detection of slots that do not have a bootname set.
A valid use case for this is a A+B+recovery scenario where A+B are
handled by the boot selection mechanism while 'recovery' is selected
automatically as a last resort when normal boot selection handling
fails or does not return any bootable slot.
We fix this with the first patch and document the entire mechanism with the second one.

Allow slot names in rauc.slot and document booted slot detection

---

Makefile.am
rauc.1

These patch opportunities were noticed while creating a Debian package for rauc. Most changes are harmless, but for example `test/invalid-sig-bundle.raucb` was missing which (silently) invalidated the respective test.
The release archive contains `rauc-installer-generated.h` which I'm not sure about if that is right. Other than that the remaining differences between the files in git and the archive are auto* related files (`aclocal.m4`, `autogen.sh`, `build-aux/*`, `configure`, `config.h.in`, `m4/*`, `Makefile.in`, `contrib/cgi/autogen.sh`), `.gitignore` files, `.lgtm.yml`, `travis.yml`, and versioning stuff (`.version`, `.tarball-version`).

Equalize contents of release tar ball to git tree and a typo fix

---

Makefile.am
README.rst
docs/advanced.rst
include/config_file.h
include/mbr.h
include/utils.h
src/config_file.c
src/mbr.c
src/update_handler.c
src/utils.c

This introduces a possibility to update a bootloader on a FAT partition, for SoCs with a ROM code which boots from the first partition in the MBR partition table, by changing the partition table.

Atomic MBR boot partition update

---

docs/reference.rst
include/config_file.h
src/config_file.c
src/install.c
test/config_file.c

This replaces the former `force-install-same` key by a new `install-same` one to reflect that we invert the default.
From now on, the default behavior of RAUC will be to always install an image, regardless of whether its target slot checksum is the same as the image's checksum.
This inverts the default slot skipping optimization present since the initial release of RAUC.
Explicitly enabling this handling is still possible of course, by simply specifying
``` ini
[slot.rootfs.0]
...
install-same=false
```
in your system config.
This change will not have any impact on compatibility with old setup despite that you do not gain minor speed performance in rare cases by default.

Invert Slot Skipping Logic

---

rauc.1

The 'status' command has several subcommands to modify/set slot states.
These should be mentioned briefly in the man page.

manpage: extend the documentation of 'status' command

---

include/context.h
src/install.c
src/manifest.c
src/utils.c

Clang has stricter warnings for some cases, so we should fix these.

minor fixes and annotation for compilation with clang

---

src/mbr.c

In #453, we broke compilation with newer gccs on x86, as reported in #454.
This PR tries to fix it in a simpler way by using `#pragma pack`. Also fix access to 32-bit integers on big-endian platforms by using the correct wrappers.

fix compile warnings/errors in src/mbr.c and endian issues

---

README.rst
test/rauc.t

When following the `README.rst` and running the tests on platforms that have only a minimal set of tools installed, the current dependency description and missing tool handling is insufficient.

Fix test dependency handling and documentation

---

src/bundle.c

The squashfs magic is contained in little endian order in the image. To
be able to detect it correctly on big endian the magic value needs its
endianess switched to properly compare with the respective value found
using read(2) from the image.
With this the test suite runs successfully on a sparc64 box apart from a single test that fails because mksquashfs dies with a bus error, which I reported on https://bugs.debian.org/932787 .

Fix bundle detection on big endian

---

src/rauc-installer.xml

When generating interface classes for Qt projects using qdbusxml2cpp
custom types must be annotated.
To use the generated interface class the RaucSlotStatusArray and
RaucProgress types have to be defined and registered as Qt meta types.
Additionally QDBusArgument proper streaming operators have to be
supplied.
Signed-off-by: Tobias Junghans <tobydox@veyon.io>

service: add annotations for qdbusxml2cpp

---

src/signature.c

It is convenient to pass the PIN via the environment variable. In some
production signing cases the PIN should rather be entered interactively
than being passed to RAUC via the environment variable. The environment
is built nonetheless, but with an empty RAUC_PKCS11_PIN variable. This
leads to a failing login attempt with an empty string as the PIN.
Due to the fact that the PIN is never an empty string anyway do not pass
such a PIN on and thus enable being prompted interactively for a PIN in
that case.
Signed-off-by: Bastian Krause <bst@pengutronix.de>

src/signature: pass only non-empty PINs on to PKCS#11 engine

---

docs/reference.rst
include/config_file.h
src/config_file.c
src/update_handler.c
test/config_file.c

This commit allows setting a different temporary directory for `casync` at extraction.
`casync` caches things in the temporary directory. The default location `/var/tmp` may be limited in some use-cases. Thus, the choice of a temporary directory is very important, and the user/maintainer must have control of it.
For example, if the things that are being updated is very big (lets says 10GB), the seeding requires lots of inodes and `casync` may run out of inodes if the filesystem is already full of files.
The example below sets the temporary directory to `/tmp`:
```
$ cat /etc/rauc/system.conf
(...)
[casync]
tmppath=/tmp
(...)
```

Add casync tmpdir option to system.conf

---

src/config_file.c
src/update_handler.c

The compiler has found those two errors below:
```
In file included from /usr/include/glib-2.0/glib.h:114,
from src/config_file.c:1:
src/config_file.c: In function ‘save_slot_status’:
/usr/include/glib-2.0/glib/glib-autocleanups.h:28:3: error: ‘group’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
28 |   g_free (*pp);
|   ^~~~~~~~~~~~
src/config_file.c:905:21: note: ‘group’ was declared here
905 |   g_autofree gchar *group;
|                     ^~~~~
(...)
src/update_handler.c: In function ‘img_to_boot_mbr_switch_handler’:
src/update_handler.c:1249:3: error: ‘out_fd’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1249 |   close(out_fd);
|   ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Fix uninitialized locals

---

test/install.c

The test '/install/target/' verifies that the target install groups
determined by RAUC match the expectation based on system.conf and
manifest file.
Beside all other slots the system.conf also defines two slots 'rescue.0'
and 'rescue.1' that are in no relation to any of the slots we can detect
as booted / non-booted. Thus, both are candidates for selecting them as
target group candidates.
Now, the actual selection only depends on the order they appear when
iterating over the slot GHashTable. If the implementation of GHashTable
changes, this will also affect the slot that appears in the target
group.
With the current implementation we cannot reliably determine if this
would be rescue.0 or rescue.1 and thus we have to deactivate the check
to prevent it from failing on systems with a …

test/install: deactivate check that depends on GHashTable implementation

---

test/install.c

For the triple-redundancy rootfs.0, rootfs.1, rootfs.2 (including their
childs), we have rootfs.0 set to 'active' so far and thus both rootfs.2
and rootfs.2 being detected as 'inactive'.
For this case, there is still no real definition of when or whether to select
rootfs.1 or rootfs.2.
Prior to this, the test checked for the selected slot being rootfs.1
which was valid for the concrete implementation, but mainly depending on
the order that was given by the GHashTable (iterator) implementation.
In recent glib version this changed resulting in rootfs.2 being selected
instead.
We adapt the test for checking correctly for both cases.
Supersedes #475

test/install: fix test for undefined behavior in slot selection handling

---

src/bootchooser.c
src/install.c

The GDataInputStream 'datainstream' is created from 'instream' with
g_data_input_stream_new() but never freed.
Luckily we have g_autoptr() mechanism, so that we just need to declare
'datainstream' as an auto pointer variable here to have it freed
correctly as soon as it leaves the context.
Note that the bug described above also leads to an open file descriptor
remaining.
The more often on calls, for example, 'rauc status' the more open file
descriptors will be collected until they suddenly hit the maximum number
of open file descriptors allowed (e.g. by systemd service settings)
resulting in error message:
> Too many open files

Fix leaking GDataInputStream's

---

docs/integration.rst

Fixes a single character documentation error.
Signed-off-by: Leif Middelschulte <leif.middelschulte@klsmartin.com>

docs/integration: fix typo

---

src/main.c

A little gadget I always wanted to have... And did in the train locally
because of poor german LTE performance...
It gives you a two-lined progress bar while installing with RAUC. The
first line contains the message in the same style as before, the second
line contains a hash-printing progress bar in the width of the current
terminal.
Output will be similar to this:
50% Checking Bundle done.
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ] 50%
This is only activated if we detect a tty, otherwise we use the
old-style printing format.

src/main.c: A progress bar for RAUC

---

src/install.c

Detection of external mount points was a little buggy and tend to fail in scenarios where multiple mount points for the same slot exist and when mount points are removed during rauc service's life cycle.
Let's fix it.

src/install: Fix External Mount Point Handling

---

contrib/uboot.sh

Currently, the U-Boot contrib script decreases the boot attempt counter before
echoing the message about the valid slots being found, which results in the
following:
3 boot attempts -> prints 2 attempts left
2 boot attempts -> prints 1 attempt left
1 boot attempt -> prints 0 attempt left
The script should print the message first, then decrease the counter. This
commit fixes the issue.
Signed-off-by: Ellie Reeves <ellierevves@gmail.com>

Fix U-Boot contrib script

---

.travis.yml
Makefile.am
README.rst
configure.ac
data/de.pengutronix.rauc.conf

For the D-Bus system service directory, we can rely on pkg-config
to query the target directory, instead of constructing our own
assumption.
For D-Bus policy directory, there is no such pkg-config variable.
However, D-Bus's $datadir might be different from ours, so use
D-Bus's ones.
This allows to compile/install rauc to /usr/local but place the
D-Bus config files in the directories which are considered by
distribution's D-Bus.
While at, adjust the syntax for systemd service directory part
a little bit to match the D-Bus stuff.
We also rename some internal autoconf variables to match the
configure parameter names.

configure: refine D-Bus install directories

---

include/utils.h
src/bootchooser.c
src/bundle.c
src/mount.c
src/update_handler.c
src/utils.c

We have the utility function r_debug_subprocess() which precedes each
call of g_subprocess_newv() and prints the command and args used.
But, for subprocess calls being invoked with g_subprocess_new()
(non-argv-variant), this is not possible and there currently simply is
no output of the invoked call.
This is quite unexpected in debugging scenarios (to see some subprocess
calls and others not).
This patch fixes this by adding manual g_log() calls for each
subprocess.
Note this is a duplication of the argument list, but still much shorter
than using invocations of g_subprocess_newv().

src: add missing subprocess call debug logs for g_subprocess_new()

---

configure.ac

If we build the rauc host tool or use rauc on the target without the service
feature, then we also do not need D-Bus and thus should not depend on it
unconditionally.
We move the check to the service conditional to fix this.

configure.ac: do not depend on dbus pkconfig if D-Bus is not required

---

CHANGES
configure.ac
include/context.h
include/signature.h
src/bundle.c
src/context.c
src/main.c
src/signature.c
test/bundle.c
test/openssl-ca.sh
test/openssl-ca/dev-only-ca.pem
test/signature.c

When doing post-signing verification for 'rauc resign' we must be aware
that we need two different keyrings:
a) The one to verify the *original* bundle against
b) The one to verify the *resigned* bundle against
For now we only had the option `--keyring` and the same keyring was used
for both case a) and b).
While there are cases where this is valid (if the keyring accepts both
signatures), the default is that this will fail.
The existing '--keyring' parameter is already used for passing the
systems keyring to the RAUC service etc.
Thus for post-signing verification we must introduce another parameter to
explicitly pass the 'second' keyring. This is what we do here with the
'--verify-keyring' parameter.
Note that this will 'break' setups that did use the '--keyring'
verification feature …

Introduce --signing-keyring to fix post-signing verification for 'rauc resign'

---

CHANGES
docs/advanced.rst

This is one possible solution how to select the correct data partition when using redundant data slots.
As talked with ejoerns at #rauc.
Feel free to modify.

add example how to mount the correct data partition for redundant layout

---

rauc.1
src/mbr.c

These typos show up when building the package for Debian, the Lintian
tool can be picky:
~~~~
$ lintian ../rauc_1.2-1_amd64.changes
I: rauc: spelling-error-in-binary usr/bin/rauc multipe multiple
I: rauc: spelling-error-in-manpage usr/share/man/man1/rauc.1.gz allows to allows one to
~~~~
Actually there are many more "allows to" in RAUC codebase, which indeed
seems to be a common mistake according to [1]. Replacing by "allows one"
or "allows us" or something else? I'm not a native English speaker, I
can't say, so I prefer not to touch it, except for the one that Lintian
complains about :)
[1]: https://www.impan.pl/wydawnictwa/dla-autorow/errors.pdf
Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>

Typos (multipe, "allows to")

---

README.rst
docs/faq.rst
docs/index.rst
docs/integration.rst

Various places of the RAUC documentation noted ext2 and ext3 file system
support. This was quite misleading as RAUC has an ext4 file type, but
not an ext2 / ext3 type.
This removes the notions of ext2 and ext3 and adds a section in the FAQ
why they are intentionally not supported.

remove misleading reference to ext2 / ext3 support.

---

src/main.c

This fixes double-free in case of concurrent accesses to the service via D-Bus.
It also shortens the resulting error message from 
> rauc-Message: 11:40:37.649: rauc mark: rauc status: error retrieving slot status via D-Bus: rauc status: error retrieving slot status via D-Bus: error calling D-Bus method "GetSlotStatus": GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code30: already processing a different method
to
>  rauc-Message: 12:24:30.734: rauc status: error retrieving slot status via D-Bus: error calling D-Bus method "GetSlotStatus": already processing a different method

Various Fixes (including double-free) for slot status D-Bus error handling

---

docs/conf.py

readthedocs.org modifies conf.py, which causes a confusing -dirty suffix
for very build.

docs/conf.py: ignore -dirty in the docs version

---

src/bundle.c
test/bundle.c

The res variable can be set to TRUE by one of the preceding function
calls. Explicitly set the variable to FALSE for error paths.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>

bundle: fix result values for error paths

---

configure.ac
src/network.c

I would like to consume RAUC bundles straight from our CI environment which uses OpenStack Swift as a backend for artifact storage, and OpenDev's Zuul as the CI runner. As it happens, our CI jobs [sends file content to Swift with a `Content-Encoding: gzip`](https://review.opendev.org/688154), and Swift appears to always send the file with that `Content-Encoding` no matter what `Accept-Encoding` the HTTP client sends in their request.
This patch simply uses curl's list of default supported `Content-Encoding` decoders (that's the special magic `""` value of this header). The end result is that our boxes can now fetch stuff from our CI environment without any problems.
TL;DR: this should save some bandwidth at essentially a zero cost, and it unbreaks updates from network under at least one …

curl: Enable decoding from server's Content-Encoding

---

include/bundle.h
include/checksum.h
include/mount.h
include/signature.h
src/bundle.c
src/checksum.c
src/main.c
src/mount.c
src/network.c
src/signature.c
src/update_handler.c
test/signature.c

Documentation of g_output_stream_splice() says:
> Note that if the number of bytes spliced is greater than G_MAXSSIZE,
> then that will be returned, and there is no way to determine the actual
> number of bytes spliced.
As copy_raw_image() performs a sanity check if returned size matches
expected write size, it will not be possible to install an image whose
size exceeds G_MAXSSIZE.
Thus instead of letting g_output_stream_splice() close the output stream, we
leave it open to use g_seekable_tell() on it and obtain the actual size
read (written), even if it exceeds gssize.
Fixes #463.

src/update_handler: use g_seekable_tell() to get size of written data

---

docs/using.rst

This is no longer valid since commit 9660b57c1959f62b1c584e483e29d94fe2486b47
('src/main: do not reject local bundles that do not have a .raucb extension')

docs/using.rst: remove note on mandatory .raucb suffix

---

test/install.c

Ease debugging test failures and make tests more reliable by not only
verifying return code but only checking error variable return value.
This will
a) verify that both return code and error return variable are set
correctly by the called method
b) print the actual error message upon test failure and thus give
more targeted hints on why the test failed

test/install: proper error checking in install_test_target()

---

src/update_handler.c

Is there any reason that I am not aware of to not overwrite that environment variable if it is already set?

Unconditionally export RAUC_BUNDLE_SPKI_HASHES

---

include/network.h
src/network.c
test/network.c

This fixes error handling in transfer() function and improves (simplifies) reporting bundle downloads that exceed the maximum size.

Fix and improve error handling in network code

---

Makefile.am
include/utils.h
src/context.c
src/utils.c
test/utils.c

This was always intended to be a short string without whitespace. Remove the whitespace from when preparing the context. In the manifest, the variant is part of the image section name, so intentional surrounding whitespace would be very unusual.

remove surrounding whitespace from system variant

---

docs/reference.rst
src/main.c
test/rauc.t

Exactly why and when this was deprecated is hard to determine, but the
"Deprecated" description was added 2.5 years ago (a9ac4098a321 -
src/main: add command summary). It's time to remove it completely.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>

main.c: remove deprecated checksum command

---

.gitignore
Makefile.am
configure.ac
src/main.c

This adds some configure knobs that allows one to disable parts of rauc that are not useful on the target device, such as bundle creation or resigning. To get the full benefit of that, add compiler and linker options to discard unused functions and data at link time. Just to get an idea of the effect, I've built each patch in turn with of `--disable-service --disable-create` (the latter of course only has an effect later in the series). That gives
```
$ size rauc.bin.*
text    data     bss     dec     hex filename
214582    8080    1736  224398   36c8e rauc.bin.0
214582    8080    1736  224398   36c8e rauc.bin.1
174336    5000    1672  181008   2c310 rauc.bin.2
174368    5000    1736  181104   2c370 rauc.bin.3
156204    4512    1704  162420   27a74 rauc.bin.4
156172    4512    1704 …
```

reduce rauc binary size

---

src/main.c

This has just bugged me somewhat, not being able to see what the CLI arguments are with a simple `-h`

Add rauc status subcommands to cli help

---

src/main.c

For me, compiling rauc fails with:
> src/main.c:45:55: error: implicit declaration of function ‘strerror’ [-Werror=implicit-function-declaration]
>    g_warning("Unable to obtain window parameters: %s", strerror(errno));
Taking a closer look at main.c shows that the required <string.h> is
actually not included. Not sure how this ever worked or what pulls in
string.h on other systems, but this appears to be the right solution,
anyway.

src/main: add missing include of string.h

---

src/signature.c

As the title already indicates, this solves two issues at once, revealed
by a closer look at the code while discussing #544.
The first issue is that, if the keyring was passed to `cms_sign`, some
error paths in the keyring correctly handled setting the GError, but
left the `res` variable untouched.
While the `res` variable determines the return status (successful /
failed) of the function, this would have led to cases where `cms_sign`
indicated a successful return but actually failed.
While this was already handled in some cases by setting `res = NULL`,
in others it was not. However, also the `res = NULL` is quite problematic
as it causes leakage of the GBytes referenced by 'res' before.
The valid solution to handle both the reset of `res` to `NULL` and cause a
freeing of the memory is to …

src/signature: fix error handling and memory leakage in cms_sign

---

.travis.yml
README.rst
qemu-test
qemu-test-init

Replace UML with QEMU for run-time tests. This will make it easier to test more complex setups (such as UBIFS on nandsim). Also, it should reduce the CI maintenance effort needed caused by the unusual UML dependency.

switch CI to use QEMU instead of UML

---

src/main.c

In 7a390661f089f438855d5ff3c61e7a43ca1ffb99 (#537) the --mksquashfs-args
argument was added for the 'bundle' subcommand.
However, the same method is also used when invoking the 'convert'
command.
Thus, we simply enable the option for 'convert' too here.

src/main: the 'convert' subcommand deserves --mksquashfs-args, too.

---

src/config_file.c
src/main.c

Note that this is based on #477
So far, especially when having more complex slot setups, the output of
'rauc status' did not provide an easy and clear view of the slots
constellation and their respective status (booted, active, inactive).
This patch aims to fix this by giving a more tidied-up view with colors
and bold font for highlighting.
The (uncolored) variant woll look as follows:
```
=== System Info ===
Compatible:  Test Config
Variant:     myvariant
Booted from: rootfs.1 (system1)
=== Bootloader ===
Activated: rootfs.0 (system0)
=== Slot States ===
[bootloader.0] (/tmp/boot-0, raw, inactive)
description: 
○ [rootfs.1] (/tmp/rootfs-1, raw, booted)
bootname: system1
description: 
boot status: good
[appfs.1] (/tmp/appfs-1, raw, active)
description: 
⏺ [rootfs.0] (/tmp/rootfs-0, raw, …
```

A more fancy rauc status output

---

Makefile.am
docs/integration.rst
include/context.h
src/context.c
src/install.c
test/context.c

This adds the support to use external devices. By external I mean
devices not known by RAUC (listed within the system.conf). So we are
able to use RAUC to initialise the system from a 'special' medium e.g. a
usb-stick which isn't part of the 'normal' update system. To signal it
to RAUC I introduced a cmdline flag called 'rauc.slot.external'. If the
flag is present RAUC won't try to find an active 'normal' slot.
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>

install: add support for external devices

---

include/config_file.h
src/bundle.c
src/config_file.c
test/bundle.c
test/rauc.t
test/test-global.conf
test/test.conf

In order to actually use a provided CRL for checking, some flags need to
be set in OpenSSL. These were unset up to now. As a result of this, a
keyring / cert store file or directory could have contained a CRL, but
the Bundle verification process in RAUC simply ignored it.
This patch now introduces the `[keyring]` section option `check-crl` that
allows enabling CRL handling for RAUC's signature verification.
The reason why this cannot be enabled by default is that OpenSSL would
enforce having a CRL in a cert store. This will not only break existing
setups but also make the simplest case (a simple self-signed
certificate for now) more complex.
Although, we cannot enable CRLs by default, there may be setups
that probably already have a CRL in their key store.
To more visibly tell them to …

Allow to Enable CRL handling in RAUC's Bundle Verification

---

include/context.h
src/context.c
test/config_file.c

This collects all changes that needed to be done to reveal and fix the issue why in my setup the test `/config-file/system-serial` suddenly painted an annoying red in the green meadow of successful test runs.

Fixing a config_file test that suddenly broke..

---

docs/reference.rst

This syncs the usage in documentation with actual output of the tool.

docs/reference: update command line usage

---

docs/reference.rst

Synchronize the documentation to glib's commit [1] contained in release 2.51.0
for the first time which changed the output format from '[OPTION...]' to
'[OPTION…]' (using the unicode character U+2026 "horizontal ellipsis").
[1] 10c490cdfe3a ("Use Unicode in translatable strings")

docs/reference: switch to horizontal ellipsis

---

docs/advanced.rst
rauc.1
src/main.c
test/rauc.t

When the certificate used for signing a bundle has expired, it is useful to explicitly disable verification during resigning.

support --no-verify for rauc resign

---

docs/reference.rst
include/slot.h
src/config_file.c
src/install.c
src/update_handler.c
test/config_file.c
test/install-content/hook.sh
test/install-fixtures.c
test/install.c
test/service.c
test/test.conf

This is an alternative and somewhat less intrusive approach to solving the problem that #186 is also trying to solve. Instead of having RAUC unmount and mount, this simply allows the update to proceed, provided the user takes full responsibility by providing his own install hook. 
For our use case, that actually turns out to be even more convenient, since we can then more easily preserve some of the U-boot environment that would otherwise be lost when one wipes the boot partition completely.
It still requires opt-in per slot in system.conf, since we don't want to effectively disable the mounted-sanity check for those existing users that just happen to provide their own install hook.

allow mounted devices when using custom install handler

---

src/main.c

This fixes 'rauc status' printout by
* clarifying the marking of a booted slot
* fixing unintentional bold printing of closing bracket

Small Fixes for Readable 'rauc status' Output

---

docs/reference.rst
docs/using.rst
include/context.h
include/install.h
src/de.pengutronix.rauc.Installer.xml
src/install.c
src/main.c
src/service.c
test/service.c

In the past, there were a lot of cases where we ran into the limitation of the `Install` method of the D-Bus `Installer` interface. These were all caused by the missing ability to pass additional arguments to the install call.
As we cannot break existing setups, we cannot simply change the method signature. Instead, we need to introduce an alternative method.
Here it is: ``InstallBundle sa{sv}``
Where the new generic dict of string-variant (``a{sv}``) allows passing and handling all kind of current and future parameters without changing the interface again.
This initial series includes support for one argument that was already implemented for the non-D-Bus case: ``--ignore-compatible``. It allows forcing the installation of a bundle on a per-installation-call base
Reference: #248

Add new InstallBundle Method to D-Bus API

---

qemu-test
qemu-test-init

- Add a mechanism to start a shell in the qemu environment for development.
- Avoid using the poweroff binary, which is not available every and use sysrq instead.
- Show remaining mounts and free/df after a failed test.

improve qemu-test helper

---

src/de.pengutronix.rauc.Installer.xml

An annotation is required for the recently added `InstallBundle` method as well when using qdbusxml2cpp.

service: add annotation for InstallBundle method

---

docs/integration.rst

Previously it was not clear that ``CONFIG_FEATURE_SEAMLESS_XZ`` was an example for one tar compression format, no comprehensive suggestion. Make that clear.

docs/integration: clarify tar compression formats

---

README.rst
qemu-test-init
test/update_handler.c
uncrustify.sh

With some additional setup in qemu, we can start testing these update_handlers.

improve testing of NAND and UBIFS slots

---

docs/integration.rst

RAUC's PTXdist integration changed. Reflect the changes here.
Keyring directories were never supported with PTXdist's upstream rules, so remove them altogether from this section.
While at it convert the section to use semantic line breaks, improve wording and clarify some minor details.

docs/integration: update PTXdist section

---

docs/advanced.rst
docs/integration.rst

This should help people migrating from a CA keyring file to the code signing infrastructure as well as people with simple and more complex PKI cases.
Note: to make the link work the [corresponding documentation patch](https://www.mail-archive.com/ptxdist@pengutronix.de/msg16496.html) has to be applied in PTXdist.
Improves #599.

docs: integration: refer to PTXdist's new "Managing CA Keyrings" section

---

src/mbr.c

res variable will be set to true by the previous call of
`get_raw_partition_entry()`. Thus only setting the error and going to
'out' will result in accidentally returning TRUE in case of failures of
`lseek()` or `write()` call.

src/mbr: fix r_mbr_switch_set_boot_partition() error paths

---

docs/basic.rst
docs/integration.rst
docs/reference.rst

This PR includes the documentation for bootloader-custom-backend implementation #541.
Signed-off-by: Andreas Schmidt <mail@schmidt-andreas.de>

docs/integration: add custom bootloader backend description

---

CHANGES
src/update_handler.c
test/common.c

By default, mkfs.ext4 will use 128 byte inodes on filesystems < 512MB. As those don't have enough space for longer timestamps, newer kernels complain with "ext4 filesystem being mounted at /foo supports timestamps until 2038".
Avoid this by specifying 256 bytes, which is already the default for larger filesystems. Also adjust the mkfs.ext4 call in the test suite. This option is supported since e2fsprogs v1.40 (released in 2007) and busybox 1.16.0 (released in 2010).

src/update_handler: use 256 byte inodes for ext4 by default

---

Makefile.am

The test script is useful also for users getting rauc via a tarball, so
ship qemu-test similar to the uml-test script.

qemu-test: also distribute qemu test scripts in a release tarball

---

.travis.yml
CHANGES
Makefile.am
configure.ac
docs/advanced.rst
include/gpt.h
include/mbr.h
include/update_handler.h
src/config_file.c
src/gpt.c
src/mbr.c
src/update_handler.c
test/boot_switch.c

This adds support for atomic update of bootloaders in the first GPT partitions (such as the ESP), similar to what we already support for MBR (via boot-mbr-switch).
The PR also adds support for testing of both boot-switch methods in qemu on a loopback device.

add GPT boot partition support via boot-gpt-switch slot type

---

docs/basic.rst
docs/checklist.rst
docs/reference.rst
src/config_file.c
test/config_file.c

Using a single central slot status file in RAUC has several advantages. Thus we should be more explicit in notifying the user of this feature.
This now:
* adds a check to the design checlist
* explicitly mentions benefits in documentations
* adds an info message when not using the central status

Promote Central Slot Status Usage More Obviously

---

CHANGES
README.rst
docs/integration.rst
src/bootchooser.c
src/config_file.c
test/bootchooser.c

As I missed to review #541 and #600, my minor adaptions and concerns come now as a separate PR.
I think the most gets clear by the individual commits. One major discussion point I see is on how to provide the custom bootloader implementation script/binary.
By now, this is implemented as a 'handler' which is a bit confusing as we set the bootloader and all bootloader parameters in the `[system]` section normally.
But also if we could agree on understanding this as a handler in the same sense of the other handlers, then this would require resolving the handler's name relative to the system configuration file as we do for the others too.
This, in turn, makes the current testing fail (as Travis will show) because the tests expect the bootloader implementation to be script or binary in PATH. …

Fixes and open points for custom bootloader interface

---

docs/reference.rst
src/update_handler.c
test/install-content/hook.sh

Otherwise it is tempting to try and set the bootname on the child slots too, as in #588.

src/update_handler: set RAUC_SLOT_BOOTNAME for child slots too

---

src/bundle.c
test/rauc.t

Commit 00cdb5e6b7bdeab0a3cafe28edcdeb8b2b1034a9 introduced a bug that lead to removing an existing output bundle instead of just aborting. This fixes that issue and also removes incomplete outputs for `rauc convert` (casync)

fix bundle create/resign/convert error handling

---

qemu-test
test/minimal-test.conf
test/rauc.t
test/service.c

Adds tests for "rauc extract" and "rauc install" to rauc.t, also for non-service case and adds minimal qemu-test documentation and error handling updates for service tests.

Add some testing enhancements and extend CLI testing

---

include/slot.h
src/install.c
src/main.c
test/boot_switch.c
test/update_handler.c

We have to use a type name for freeing and GStrv is the standard glib
typedef prepared for this purpose.

src/install: fix leaking gchar** with g_auto(GStrv)

---

src/bootchooser.c

Note that we have the same in `grub_get_state()` already but missed to add it here, too.

src/bootchooser: fix leaking gchar in grub_get_primary()

---

src/network.c

Hi Maintainers,
libcurl ignores the `~/.netrc` file by default.
This makes the use of the `~/.netrc` file optional; the information in the URL is preferred.
With this patch, it is possible to hide the login/passwd in the file `~/.netrc` and enables the HTTP Basic Authentication.
This is a minimalist integration; there is no option given to the command line, nor environment variable, nor attribute in the configuration that may enable or disable the use of `~/.netrc`. I can do it if this is wanted.
Regards,
Gaël

src/network: make the use of .netrc optional

---

src/main.c

'rauc resign' expects an existing bundle as first positional argument and the output bundle filename as a second positional argument, just like 'rauc convert' does. Make the usage string reflect that.

src/main: fix positional arguments in resign usage string

---

docs/integration.rst
src/context.c

Hi folks,
This is basically the same commit as c6730a6d90acd319072f633f35249134a6a1d34e buf for `PARTLABEL`.
Regards,
Gaël

src/context: support resolving PARTLABEL to real path

---

Makefile.am

I digged a bit around and just adding this file to the archive isn't enough to fix the failing tests, but these fail for me also with e.g.
```console
$ sudo make check
```

Makefile.am: Also ship test/minimal-test.conf in release tar ball

---

docs/advanced.rst

The given script moves the keyring files on the currently active slot
instead of the target slot.
Signed-off-by: Christoph Steiger <c.steiger@lemonage.de>

docs: advanced: Fix Keyring move example script

---

src/manifest.c
test/manifest.c

In case we are unable to save the manifest file (e.g. insufficient
permissions), we should propagate the error. Otherwise the error
handling for update_manifest will cause a NULL pointer derefence.
Try to bundle with insufficient permission (before patch):
``` 
$ rauc bundle --keyring=keyring.crt --key=my.key --cert=my.crt RAUC my.img
(rauc:4825): GLib-CRITICAL **: 21:35:37.306: g_propagate_error: assertion 'src != NULL' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
Try to bundle with insufficient permission (after patch):
```
Failed to update manifest: Datei »RAUC/manifest.raucm.7B24S0« konnte nicht angelegt werden: Keine Berechtigung
```

src/manifest: fix NULL pointer dereference if update_manifest fails

---

src/update_handler.c

Move the fallback handler for \*.img.caibx files to the bottom, so other default handlers (such as "boot-\*") do not get omitted.
See also https://github.com/rauc/rauc/issues/639#issuecomment-709931343.

src/update_handler: Reorder *.img.caibx fallback handler

---

.gitignore
src/update_handler.c
test/bundle.c
test/install-fixtures.c
test/install.c
test/update_handler.c

This increases g_autofree and g_autoptr usage in tests to make actual leaks easier to find. Also we add some more runtime checks and print the signer name after signature verification.

various cleanups

---

docs/integration.rst

The description for U-Boot lacked some useful details and omitted some steps or described them misleading.
The aim of this PR is to clarify these things and extend the documentation concerning U-Boot integration.

docs: integration: Extend description of how to set up U-Boot for RAUC

---

include/slot.h
src/config_file.c
src/slot.c

This applies two fixes to re-enable the checking of unknown keys in system.conf for all slots.
This eases writing working configuration and prevents unexpected behavior due to unhandled settings.

Fix checking of remaining keys in system.conf

---

data/rauc.service.in
src/service.c

When shutting down a system running RAUC, one can see RAUC failing regularly with an exit 1 code and a misleading error message:
``` 
rauc[197]: Connection to the bus can't be made for de.pengutronix.rauc
systemd[1]: Stopping D-Bus System Message Bus...
systemd[1]: Stopping Rauc Update Service...
[...]
systemd[1]: rauc.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: rauc.service: Failed with result 'exit-code'.
```
This PR aims to solve both the systemd behavior as well as the error message.

Fix systemd D-Bus handling and RAUC error reporting

---

docs/integration.rst

There is a bug in Kernel version v5.0 until v5.7 when loop device
support is loaded as a module, in a small percentage of cases
mounting the bundle fails. Include information about the patch.
Resolves: #562
Resolves: #582
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>

docs: include Kernel loop device patch

---

.gitignore

This covers some file in e.g. docs/extensions/lexer
and also ignores some files generated during tests.

gitignore: add precompiled Python files and some generated files

---

src/bundle.c

The squashfs should always be padded to 4KiB, but check this explicitly to avoid possible corner cases later.

check squashfs size during check_bundle

---

include/signature.h
src/main.c
src/signature.c

It's useful to have the name of the bundle signer in the logs. Fix some string leaks while updating the code to use an OpenSSL memory BIO.

Print signer name after verification

---

src/install.c

The RAUC bundle is already verified at this point, so there is no need
to verify the checksum of each file individually. This saves time during
the installation.

src/install: remove checksum verification for files in bundle

---

test/get-coverity.sh

Note: coverity currently seems to provide a broken package.
Testing this revealed some drawbacks of the current script handling that should be fixed.
Commit message:
We add 'set -e' to abort on errors. This allows identifying issues in
the test flow earlier.
We remove the created $TOOL_BASE directory on extraction error as this
is used to check for skipping the download the next time the script
runs.

test/get-coverity: let script detect and handle errors more reliably

---

test/get-coverity.sh

A || B && C runs C if either A or B succeeds, which happens always in this case.
This fixes aa4676cacbf23e32905b0b7a66662a816f253d0f.

test/get-coverity: fix error handling

---

src/bundle.c

As convert_to_casync_bundle() already calls sign_bundle() via create_bundle(),
this call is redundant. Remove it.

src/bundle: remove duplicate signature on casync bundle

---

src/mount.c

Build with kernel headers < 4.14 fails since version 1.5.0 and https://github.com/rauc/rauc/commit/527bf2f7f746e0253f7843542e19cb0fa0c7c869:
```
src/mount.c: In function 'r_setup_loop':
src/mount.c:201:25: error: 'LOOP_SET_BLOCK_SIZE' undeclared (first use in this function)
looprc = ioctl(loopfd, LOOP_SET_BLOCK_SIZE, 4096);
^
```
Indeed, `LOOP_SET_BLOCK_SIZE` is only defined since https://github.com/torvalds/linux/commit/89e4fdecb51cf5535867026274bc97de9480ade5
Fixes:
- http://autobuild.buildroot.org/results/829ae7ed66686c11a941ac99bd08a06f754affb4
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

src/mount.c: fix build with kernel < 4.14

---

configure.ac

Since we use `G_VARIANT_DICT_INIT` introduced by f2eda48dde10dded99310122d994d68ec2b5960e ("src/main.c: switch to use new client API") which was first defined in glib 2.49.3, this is now the minimum required glib version.
See: https://gitlab.gnome.org/GNOME/glib/-/blob/master/NEWS#L3180
This affects releases 1.5, 1.4, 1.3.

configure.ac: increase minimum glib version required (2.49.3)

---

src/dm.c
src/signature.c

Some older toolchains do not provide (correct) built-in defintions of `strstr()` or `memset()` and thus emit compilation warnings or errors:
```
[..] warning: incompatible implicit declaration of built-in function 'strstr'
```
```
src/dm.c:15:2: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
memset(header, 0, sizeof(*header));
```
Fix this by including `string.h` explicitly.
Tested on ubuntu-16.04.

Include string.h to fix Compilation With Some Toolchains

---

src/emmc.c

This could be NULL on error, so handle that case.

src/emmc: check the return value of g_fopen

---

configure.ac
src/dm.c
src/network.c

* Optionally define `g_uuid_string_random()` that required to move to glib 2.52 before
* Check for glib API versions required to prevent from unintentionally depending on newer API
* Fix fallout

Restore Compatibility With glib 2.50 API and add API Compatibility Checks

---

.github/workflows/patches/16.04/0001-backport-to-OpenSSL-1.0.2.patch
.github/workflows/patches/16.04/0001-src-replace-G_VARIANT_DICT_INIT-supported-not-before.patch
.github/workflows/tests.yml

Note: This series bases on #677 which needs to be merged first.
In the past, we did not always notice when breaking RAUC compatibility with older toolchains and libraries.
While some incompatibilities cannot and will not be avoided (like dropping support for OpenSSL 1.0.x that is EOL since end of 2019) others are not strictly required and may happen unintentionally.
These added test should allow to be notified when breaking compatibility with old releases and making the decision explicit rather than implicit.
The tests currently run for ubuntu releases:
- 16.04 (gcc 5.3.1, linux-libc-dev 4.4.0-197.229, glib 2.48.2, openssl 1.0.2g)
- 18.04 (gcc 7.3.0, linux-libc-dev 4.15.0-20.21, glib 2.56.4, openssl 1.1.1)
- 20.04 (gcc 9.3.0, linux-libc-dev 5.4.0-59.65, glib 2.64.3, openssl 1.1.1f)
Note …

.github: workflows: compile tests on ubuntu stable releases

---

src/bundle.c

Add `ZFS_SUPER_MAGIC` as defines in openzfs.

bundle: allow installing bundle from ZFS partitions

---

docs/reference.rst
include/config_file.h
include/utils.h
src/bootchooser.c
src/config_file.c
src/utils.c

Make it possible to tweak the number of attempts that are set in the U-Boot environment when marking slots active or good.
This is helpful for systems that want to have different settings for first boots and consecutive ones.

Make uboot attempt settings configurable

---

README.rst
docs/index.rst
docs/integration.rst
docs/reference.rst
qemu-test
qemu-test-init
src/update_handler.c
test/update_handler.c

Add a handler to write images using flashcp. Can be used to update the
bootloader or other images residing in a flash partition.
TODO:
Signed-off-by: Ladislav Michl <ladis at linux-mips.org>
[r.czerwinski@pengutronix.de: adapted for current code, added tests]
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

update_handler: support for nor flash devices using flashcp

---

src/main.c

The same error string prefix is applied in `r_boot_get_primary()` already,
thus the resulting error messages all look like:
> Failed getting primary slot: Failed getting primary slot: Unable to obtain primary element
Thus simply remove the second prefix here.

src/main: remove redundant "Failed getting primary slot:" error string

---

docs/reference.rst
src/update_handler.c

add RAUC_IMAGE_SIZE as hook variable

---

src/update_handler.c

I decided to split this up into two seperate PRs, because the other one might need some adjustment, because it affetcts docs.
This one will provide the image information to pre-install and post-install slot hooks, so you can get the image_name for example.

Add image information to run_slot_hook

---

docs/advanced.rst

We recently open sourced [Upparat](https://github.com/caruhome/upparat) (a client for AWS IoT Jobs) that we use at [CARU](http://caruhome.com) in conjunction with RAUC to update our device fleet. Conceptually it's comparable to the RAUC hawkbit client but for [AWS IoT](https://aws.amazon.com/iot/) instead of hawkbit. 
If you don't mind I'd love to add a link in the docs. :)
Signed-off-by: Livio Bieri <livio@livio.li>

docs: add Upparat (client for AWS IoT Jobs)

---

src/bootchooser.c

Commit ebbdb4be9d ("Make U-Boot attempt settings configurable") made
it possible to tweak the number of attempts that are set in the U-Boot
environment.
There is an issue with that because U-Boot's setexpr can only handle
hex, while in the current implementation those values are treated as
decimals.
To work around that, let's treat those numbers as hex everywhere.

Fix configurable U-Boot attempt setting

---

include/manifest.h
src/bundle.c
src/manifest.c
test/manifest.c

This adds some sanity checks for parsing hook configuration during both bundle generation and bundle installation.
This should let misconfiguration fail faster and more explicitly and thus ease debugging hook handling issues (like https://github.com/rauc/meta-rauc/issues/185).
* Add checks for using valid hook types only
* Give more targeted error messages
* Add checks for specifying hook file when using hooks
* Add check for having hook file actually in bundle
* Fix broken error handling in manifest checking

Some Sanity Checks For Specifying Hooks in Bundle Manifest

---

docs/integration.rst
src/context.c

Both [systemd][1] and [systemd-veritysetup-generator][2] define and use the specific systemd kernel parameter `systemd.verity_root_data=` to setup the integrity protected for the root file-system.
This looks for the kernel parameter `systemd.verity_root_data=` to guess the booted slot name if `root=` is not unset.
[1]: https://www.freedesktop.org/software/systemd/man/kernel-command-line.html#roothash=
[2]: https://www.freedesktop.org/software/systemd/man/systemd-veritysetup-generator.html#systemd.verity_root_data=

Add support for systemd.verity_root_data= in the kernel cmdline

---

docs/reference.rst
src/gpt.c
src/mbr.c
src/update_handler.c

The i.MX28's ROM code expects an absolute offset to the raw device instead of an offset to a partition in the bootloader's header residing in a partition with a certain type. This is problematic when used in conjunction with `boot-mbr-switch`, because depending on which partition is active, the offset varies.
In order to allow such cases, run the pre install hook after the partition is determined and pass information required to manipulate the partition to the hook. Do the same for the post install hook, but run it prior to the actual atomic MBR switch.
To keep things consistent, apply these changes also to `boot-gpt-switch` and `boot-emmc`.
Please note that I only tested the `boot-mbr-switch` case, everything else is just compile-tested.

Make boot slot hooks more versatile

---

src/manifest.c

This fixes memory leaks introduced by PR #719 (commit f0f8a335) and
reported by coverity:
>  *** CID 1452216:  Resource leaks  (RESOURCE_LEAK)
>  /src/manifest.c: 86 in parse_image()
>  80     	g_key_file_remove_group(key_file, group, NULL);
>  81
>  82     	res = TRUE;
>  83     	*image = g_steal_pointer(&iimage);
>  84
>  85     out:
>  -->     CID 1452216:  Resource leaks  (RESOURCE_LEAK)
>  -->     Variable "hooks" going out of scope leaks the storage it points to.
>  86     	return res;
>  87     }
>  88
>  89     /* Parses key_file into RaucManifest structure
>  90      *
>  91      * key_file - input key file
> 
>  ** CID 1452215:  Resource leaks  (RESOURCE_LEAK)
>  /src/manifest.c: 258 in parse_manifest()
The above-mentioned commit made the function return earlier in case of an …

src/manifest: fix leaking hooks string list variables

---

configure.ac
include/manifest.h
src/main.c
src/manifest.c
test/install.c
test/manifest.c
test/manifest.raucm

This removes two manifest config options which were parsed but not actually used anywhere in the code.
This is unexpected and violates the concept that a manifest configuration/content actually has an impact on the installation.
Removed sections are:
* The `file.<slotclass>/<filename>` sections which originates from the long deprecated bundle-free network mode (not to be confused with the current network capabilities of RAUC) we had in the early days of RAUC.
* The `keyring` section that existed since the initial concept but actually never gained any implementation in RAUC
Note this might break very rare cases where one accidentally had one of the deprecated sections in the manifest and probably requires fixing the update bundle in this case. On the other hand, this will prevent future …

Remove Long Deprecated Sections from Manifest Parsing.

---

src/main.c
test/rauc.t

For most commands, `--override-boot-slot` will not have any impact as this is only evaluated for the service (or 'install' command when RAUC is being compiled without 'service' support).
Fix this by moving the parameter from the global option list to the options list of 'service' (and 'install' / 'status').
Also fix the sharness tests that had this argument set without any effect.
Resolves #620

src/main: limit --override-boot-slot argument to specific subcommands

---

docs/reference.rst
include/config_file.h
src/bootchooser.c
src/config_file.c

This makes use of the new feature of dt-utils' barebox-state command
`-i` switch that takes the path to a devicetree file to read the state
information from (introduced by v2021.03.0 release).
We add a new configuration option only being enabled when using
'barebox' boot selection backend: `barebox-dtbpath`.
Example:
``` ini
[system]
...
bootloader=barebox
barebox-dtbpath=/run/efi/EFI/BAREBOX/state.dtb
```
This is especially meant to be used for platforms that do not use
devicetrees for booting, thus mainly x86 ones.

src: allow passing separate devicetree file to barebox-state

---

docs/contributing.rst
docs/using.rst
qemu-test
qemu-test-init
qemu-test-rauc-config

This first adds some initial documentation about the general test infrastructure in RAUC and introduces then a new subcommand for `qemu-test` to allow booting into a mocked RAUC system for debugging and testing purposes.

Testing Documentation & 'qemu-test system' Command

---

docs/advanced.rst

The former description had formulations like "switching between two partitions" which can be quite misleading as we do not actually switch between two partitions but switch a partition between two regions.

docs: advanced: clarify how boot-mbr-switch works

---

contrib/cgi/README.rst
contrib/cgi/src/cgi.c

According to [this ](https://rauc.readthedocs.io/en/latest/reference.html#the-install-method) the used `Install` method in `cgi.c` has been deprecated. Therefor it was replaced by `InstallBundle`. Currently no arguments are passed to installation. If you have an idea how to pass them (custom header? query param?) I can integrate it as well.

Replaced deprecated Install with InstallBundle method

---

src/bundle.c

When having a squashfs that is only 4096 bytes in size, we cannot
generate a hash table.
To catch these issues, an assert was places in the code.
However, the assert must check for '>' instead of '>=' as otherwise it
would allow 'combined_size*4096' equal to 'offset' which results in a
'verity_size' of 0.
As the size of 'offset' actually depends on user input (i.e. bundle
content size), we should not use g_assert() as primary check instance
here, but add a GError check that allows to emit a user-readable error.
Fixes #739

src/bundle: fix error handling for small squashfs sizes

---

src/bootchooser.c

While `barebox_state_get()` allows passing -i argument to barebox-state when 'barebox-dtbpath' is set, `barebox_state_set()` ignored this. This prevents the feature from being useful.
Fixes commit 9e13bdd5 ("src: allow passing separate devicetree file to barebox-state").
Fixes #720

src/bootchooser: handle external dtb also in barebox_state_set()

---

docs/reference.rst
include/bundle.h
src/bundle.c
src/main.c
test/bundle.c
test/rauc.t

Many industrialization procedure requires to sign any artifact in a
dedicated secure room with restricted access
(as Public Key Infrastructure aka PKI).
This purpose add a `extract-signature` command to extract the signature
and allow resigning the signature content externally.
Signed-off-by: Jean-Pierre Geslin <jarsop@outlook.com>

feature: extract signatue: add option to extract signature from bundle

---

docs/reference.rst

The max-bundle-download-size value must be specified in bytes, without
unit. Specifying its default value in MiB might be confusing to some,
thus specify the actual value being used (8*1024*1024).
Signed-off-by: Vivien Didelot <vdidelot@pbsc.com>

docs: explicit max-bundle-download-size in bytes

---

src/bundle.c

If the bundle being checked by `check_bundle_access()` is stored on a
filesystem of type 'ramfs' it will fail with the error message "unable
to find mounted device for bundle".  Fix it by treating the 'ramfs'
filesystem type the same as 'tmpfs' ("prepared by root" so no need to
check the underlying device, which does not exist anyway).
Signed-off-by: Ian Abbott <abbotti@mev.co.uk>

src/bundle: Allow bundle to be stored on ramfs filesystem

---

include/verity_hash.h
src/bundle.c
src/main.c
src/verity_hash.c
test/dm.c

LGTM static code checker rated our C code down to "A" because of two alerts (warnings).
This fixes both.
https://lgtm.com/projects/g/rauc/rauc/alerts/?mode=list

Fix lgtm alerts

---

README.rst
docs/integration.rst

For verity bundles, we use SHA256, so the kernel implementation is required.

docs: add CONFIG_CRYPTO_SHA256=y requirement

---

docs/reference.rst
docs/using.rst
rauc.1
src/main.c
test/rauc.t

This allows easy inspection of bundle contents. As this uses squashfs in the
kernel (as `rauc install` does), this also doesn't allow --no-verify.

src/main: add rauc mount command

---

docs/reference.rst

The bootchooser code and the contrib u-boot script both use
'BOOT_x_LEFT' since implemented in 9760752217c1 ("bootchooser: add
support for uboot via fw_setenv"), which was even before the
documentation on this was added.
Fixes: 631cfb38b8bc ("docs: reference: add section about bootloader interface")
Signed-off-by: Alexander Dahl <ada@thorsis.com>

docs/reference: Fix U-Boot variable

---

qemu-test

`nandsim.parts` parameter is a comma-separated array, but should not be terminated with a comma.
Otherwise kernel option parser will ignore the parameter with:
Booting kernel: `0x100' invalid for parameter `nandsim.parts'
However, this is not critical as 0x100 is equal to the default partition size erase.
Fixes 318640ca ("qemu-test: add setup to test MTD and block devices")

qemu-test: remove trailing comma from nandsim.parts commandline parameter

---

src/context.c

Since 60fc2722a820 ("src/context: remove surrounding whitespace from
system variant"), RAUC will warn when it strips away the whitespace.
It's customary however for UNIX files to have a trailing new line,
so skip the warning if that's the only trailing whitespace.

src/context: don't warn about trailing new line in variant file

---

README.rst
src/install.c

src/install: assert not expanding unset manifest filename
During manifest file parsing, we ensure that filename is set and allow an unset filename only for an install hook.
Thus having filename unset after checking this conditition is a programming error here. Check it with `g_assert_nonnull()`.
Fixes coverity warning:
> CID 1465767 (#1 of 1): Dereference after null check (FORWARD_NULL)
> 20. var_deref_model: Passing null pointer mfimage->filename to g_file_test, which dereferences it.
Fixes 8a9c9213 which added this check:
``` patch
+               /* skip source image checks if filename is not set (install hook) */
+               if (!mfimage->filename && mfimage->hooks.install)
+                       goto skip_filename_checks;
+
```
that lets coverity assume we explicitly pass here …

Fix coverity warning in install.c

---

.github/workflows/distcheck.yml
.github/workflows/tests.yml

Currently, the 'tests' workflow fails almost every time because the 'Run
distcheck' step triggers a test failure.
The underlying failure is not RAUC-specific and related to loodev mount
and cache handling.
Details can be found in https://github.com/rauc/rauc/issues/790
As fixing this issue is not straight forward and the relevance for
real-world scenarios is hardly given, a workaround needs to be
established.
Tests showed, that the distcheck loop mount failure is not triggered (or
significantly less often) when running directly in the GitHub action runner vm
instance (rather than in the rauc testing container).
This commit thus moves the error-prone distcheck from the 'tests'
workflow to a separate 'distcheck' workflow.

.github: workflows: move 'distcheck' to separate workflow

---

README.rst

Some parts of the test suite require root access and access block devices, so
it should be avoided to run it on the host system directly. We therefore remove
that instruction from the README.
Signed-off-by: Holger Assmann <h.assmann@pengutronix.de>

README.rst: testing: remove instruction to run make check

---

src/bootchooser.c
src/service.c
test/update_handler.c

These are harmless, but are reported by clang/ccls.

fix unused variables and a missing field initializer

---

include/bundle.h
include/utils.h
rauc.1
src/bundle.c
src/install.c
src/main.c
src/service.c
src/signature.c
test/bundle.c
test/rauc.t
test/update_handler.c

This PR allows to give `--no-verify` and `--allow-expired` when resigning
to skip over expired certificates in this process.

introduce enum to tweak verification during bundle resigning

---

include/bundle.h
rauc.1
src/bundle.c
src/main.c

In some cases it might not be possible or wanted that RAUC (used as a host tool) performs its standard bundle access checks.
For example when running 'rauc convert' from within a (docker) container, RAUC might not be able to get the underlying device of the bundle's storage location. This way it cannot determine if the mount point is owend by root and will abort with
> initial check_bundle_access failed with: unable to find mounted device for bundle
While --no-verify potentially already works around this, it is a too big hammer for most cases where you actually want to benefit from the usual signature verificaton of the input bundle and just get stopped by the exclusiv access check.
Not the --trust-environment option allows to tell RAUC that we assume we have our environmet we run RAUC in …

src: introduce --trust-environment option for 'rauc convert'

---

include/config_file.h
include/context.h
src/config_file.c
src/context.c
src/main.c
src/service.c
test/service.c

The current set up of the context does not really allow handling errors gracefully. A configuration error will lead to a simple `g_error()` and core dump which is not optimal user experience.
Additionally, the context setup actually requires a configuration only in a few cases: Mainly for the service and for the install operations in a non-service build. The current handling does not enforce using a configuration but falls back to unusable defaults for these cases. This also prevents from printing more targeted error messages.
This PR aims to fix both at once.

Rework parts of context and config handling for more targeted error handling.

---

src/install.c
src/service.c
test/install.c
test/service.c

For now the service silently ignored if it could not determine slot
states. This led to a D-Bus response with a status message that
did not have the slots "state" member set to a proper value.
The CLI trying to interpret this then ends up in the undefined state of
`r_slot_slotstate_to_str()` that emits a `g_error()`
> (rauc:1523868): rauc-ERROR **: 12:32:50.829: invalid slot status 0
Fix this by not ignoring the error but forwarding it through D-Bus so
that the CLI or other frontends do not try to interpret broken data.
For this we equip `create_slotstatus_array()` with proper `GError` handling
and slightly adapt the flow in `r_on_handle_get_slot_status()` in order to
properly handle this and forward the error as a D-Bus error using
`g_dbus_method_invocation_return_gerror()`.

src/service: return D-Bus error if slot states cannot be determined

---

docs/reference.rst
test/Dockerfile

- docs/reference: Remove glossary directive
Since at least Sphinx 3.4.3, glossary entries are referenceable with the
`term` role.
For this reason Sphinx doesn't allow to repeat two times the same
`term`.
- test/Dockerfile: Update the base image to the latest Debian stable
This is a per-requisite for the proposed Desync support in #817.

Update the docker base image to the latest Debian stable

---

src/install.c
test/install.c

* Provides more helpful error message when resolving fails
* adds support for GError
* fixes missing return value check before passing to `find_config_slot_by_device()`
* Improves test debugability
Fallout from debugging behavior described in #631.

Fix and Improve Error Handling for resolve_loop_device()

---

src/service.c

`g_printerr()` does not add a line break itself, thus we should add it in the message string.
Fixes: 88ace592 ("src: make r_context_configure() public to allow calling explicitly")

src/service: add missing line break in g_printerr() call

---

docs/faq.rst

Closes #830 
Signed-off-by: Fabian Büttner <fabian.buettner@rub.de>

Add dm-crypt section to faq documentation page

---

include/context.h
src/context.c
src/main.c
test/rauc.t

This is an alternative to #836 and avoids the code duplication in https://github.com/rauc/rauc/pull/836/commits/e867ce96c5761d3e86cc139c2456c8d40aa3afc2.
Instead, it adds a config mode enum to the context. This allows the context setup code to choose the appropriate method to load the system configuration.
Commands which are intended to be used on the target (`install`, `status`, `write-slot`, `service` and `mount`) need to know the intended security configuration and will now require a config file. If none is given on the command line, they will use ``/etc/rauc/system.conf``.
Commands which are used during development (`bundle`, `resign`, `convert`, `replace-sig`, `extract-sig`) are mainly configured via the command line. If a config is given using ``--conf=``, it's still used, though. …

explicitly handle config file requirements per command

---

src/bundle.c

Commit 8a9c9213 introduced the ability to not provide any image file at all in case an 'install' slot hook is used.
But, when trying to convert such a bundle (to a casync bundle), the method `convert_to_casync_bundle()` will call `image_is_archive()` to determine if a blob or a directory index needs to be created.
So far, this method silently assumed that `image->filename` is always set, which it is not anymore.
Fix this by explicitly skipping image entries with no 'filename' set and additionally add `g_return_val_if_fail()` guards in `image_is_archive()` to prevent from using it wrongly.
Fixes: 8a9c9213 ("src: support omitting filename when 'install' slot hook is used")

src/bundle: fix rauc convert for empty filename

---

src/context.c

Code expects context's configpath to be set if config file is required.
This is an issue for example during installation when it is used to set
the environment variable RAUC_SYSTEM_CONFIG for pre-install handlers.
With current handling, as introduced by a61bb4e0, this causes the rauc
service to die with:
> g_environ_setenv: assertion 'value != NULL' failed
For consistency, simply always set the configpath variable when a config
file was loaded from any location.
Fixes: a61bb4e0 ("main: specifiy configuration mode per command")

src/context: always set context configpath when config is used

---

src/install.c

When `had_errors` is not initialized to FALSE, function always returns an error and rauc status (or service) prints:
> Failed to determine boot states: Could not determine all boot states
Fixes: c2f1e413 ("src/install: determine_boot_states: do not abort on first failed slot")

src/install: fix error indicator init in determine_boot_states()

---

.github/workflows/scan-build.yml
src/context.c

Issues like https://github.com/rauc/rauc/pull/844/files would have been detected by running llvm's 'scan-build' analyzer on the code.
This does not deal well with autofree functionality of glib this, thus memory checks are disabled. But we can already use it for the rest.

Add scan-build Actions workflow

---

include/bundle.h
src/bundle.c
test/bundle.c

Usage of this method was removed in cc8c6252 ("main: refactor info command to use new helpers") and 535ceca5 ("service: use the new load_manifest_bundle helper").

src/bundle: remove unused function extract_file_from_bundle()

---

docs/reference.rst

ref:sec-variants does not render correctly. Fix it.

docs/reference: fix broken link

---

src/bundle.c

Similarly to what it's already done when a signature is not detached, we
should skip `enforce_bundle_exclusive()`, and then
`check_bundle_access()`, if the user has set the option
`--trust-environment`.
----
This option was added with https://github.com/rauc/rauc/pull/770. But it's not currently used for detached signatures.

src/bundle: Don't enforce bundle exclusivity if the env is trusted

---

test/common.h

Glib documentation notes about this:
> g_memdup has been deprecated since version 2.68 and should not be used
> in newly-written code.
> Use g_memdup2() instead, as it accepts a gsize argument for byte_size,
> avoiding the possibility of overflow in a gsize → guint conversion
Thus, when compiling against glib version >= 2.68, use g_memdup2()
instead of g_memdup() to avoid warnings like
``` 
test/install.c:1343:17: warning: ‘g_memdup2’ is deprecated: Not available before 2.68 [-Wdeprecated-declarations]
1343 |                 install_data = memdup((&(InstallData) {
|                 ^~~~~~~~~~~~
```

test/common.h: replace deprecated g_memdup by g_memdup2 for recent glib

---

Makefile.am
configure.ac
src/main.c

Calling 'rauc status' from the command line still produced some noise and used logging methods instead of `g_print()`/`g_printerr()` as we otherwise use halfway consistently in the CLI frontend.
We also do not need to call the boot selection backend when only invoking `mark-*` subcommands.

More usage-friendly and explicitly-handled error and info printouts for 'rauc status' (subcommands)

---

CHANGES
Makefile.am
configure.ac
docs/advanced.rst
docs/basic.rst
docs/integration.rst
docs/reference.rst
docs/using.rst
include/bundle.h
include/config_file.h
include/install.h
include/nbd.h
include/stats.h
include/utils.h
qemu-test-init
src/bundle.c
src/config_file.c
src/install.c
src/main.c
src/nbd.c
src/service.c
src/stats.c
src/utils.c
test/bundle.c
test/nbd.c
test/rauc.t

This adds support `rauc install https://update-server.example/update.rauc` for verity format bundles without needing temporary space. Internally, it is based on mounting the bundle using NBD and a underprivileged helper process.

add HTTP streaming support

---

docs/integration.rst

It seems that some kernel configurations don't have this enabled already, so
mention it here and avoid surprises.

docs/integration: mention CONFIG_CRYPTO_SHA256 in the format migration section

---

test/common.h

This reverts commit c7d40a6e88ed48cb44c740dd3d1b0f3eddc4c80d.
The mentioned commit was wrong in its submitted version (which one can
already see when reading the warning message noted there).
The usage of g_memdup2() would require to bump GLIB_VERSION_MAX_ALLOWED
to not run into 'deprecation' warning saying that g_memdup2() is not
supported, yet.
However, this would drastically increase the latest supported glib
version of RAUC and result in a very wide range of versions to
potentially support with fallback macros, etc.
Such a change is only reasonable if we intend to use a new API that is
worth the bump.
The use of g_memdup() in RAUC however is limited to test cases only and
thus using g_memdup2() instead of g_memdup() has no security
implications for the rauc binary.
Thus, instead of …

Revert "test/common.h: replace deprecated g_memdup by g_memdup2 for recent glib

---

src/bootchooser.c

This is a drive-by fix, while trying to understand the exact
implementation of bootchooser_order_primay I've noticed that the list is
never freed. Jan Luebbe further noticed similar situation in
barebox_set_primary
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>

src/bootchooser: fix pair of memory leaks

---

src/bundle.c
src/signature.c

We've set CMS_ContentInfo_free via G_DEFINE_AUTOPTR_CLEANUP_FUNC, so simplify the memory management with g_autoptr.

fix leaks of CMS_ContentInfo

---

src/nbd.c

A non-root user will not be allowed to run setuid() or setgid() on the nbd process. And there is also no need to do drop permission if it already runs unprivileged.
This will enable accessing remote bundles with `rauc info` which will otherwise fail with:
rauc-Message: 11:34:40.001: Remote URI detected, streaming bundle...
setgid failed
rauc-nbd-Message: 11:34:40.013: sending: {'url': <'http://localhost:8000/test/good-verity-bundle.raucb'>}

src/nbd: do not invoke setgid() and setuid() if we run as non-root user

---

test/Dockerfile

Desync is an alternative casync implementation.
When adding Desync support in rauc, if we already have Desync installed
in the image used for the automated tests, it will be easier to validate
the proposed changes.
---
This is a pre-requisite for https://github.com/rauc/rauc/pull/817
/cc @ejoerns

test/Dockerfile: Install Desync

---

docs/reference.rst
include/manifest.h
src/main.c
src/manifest.c
test/install.c
test/manifest.c

These methods will add extra information to the bundle, allowing RAUC to
access only the parts of an image which are not yet available locally.
Together with streaming, this reduces the amount of downloaded data.
As the full image is still available in the bundle, older RAUC versions can
ignore unsupported incremental methods and we don't need to check the list for
explicit values. Currently, no methods are implemented.
Note that because we reject any manifest with unknown keys, bundles
which use incremental methods will be rejected by versions up to v1.6. By
integrating this change early (without actually implementing any methods), we
can add new methods that will be ignored by older versions. This way, users
can generate bundles with incremental methods without compatibility problems as …

add support for a list of optional incremental methods

---

src/bundle.c

The exclusive_verified flag is set only for local bundles.
Checking this for remote (streaming) bundles will result in exclusive_check_error being unset:
> Failed to extract bundle: cannot check bundle payload without exclusive access: (null)
Instead, explicitly reject remote bundles in check_bundle_payload() by checking if bundle->stream is unset. The resulting error is then:
> Failed to extract bundle: Refused to verify remote bundle. Provide a local bundle instead.
This affects rauc methods like 'extract', 'resign', etc. that conceptually do not work with remote bundles at the moment.

src/bundle: explicitly reject remote bundles in check_bundle_payload()

---

data/rauc.service.in
src/main.c
src/mount.c
src/signature.c

* fixes potential double-close in `r_setup_loop()`
* adds missing `G_GNUC_UNUSED` markers
* fixes error return value in `cms_decrypt()`
* replaces `g_message()` for 'frontent' output
* adds method args input guards
* removes superfluous variable
* fixes case of "RAUC" in service description

Collection of Various Fixes 

---

.github/workflows/tests.yml

This uses glib 2.68, which will allow us to test the glib version checks.

add build test on ubuntu 21.10

---

src/main.c

RAUC stdout can be expected to be machine readable, for example when we
use `rauc status --output-format=json`.
However, by default, Glib sends info and debug log messages to stdout.
This has the side effect of potentially mixing log messages with the
machine readable output.
With `g_log_writer_default_set_use_stderr()` we ensure that all the Glib
log messages we sent to stderr.
Fixes: https://github.com/rauc/rauc/issues/870
---
As mentioned in the related issue, this new glib function requires at least Glib 2.68. However, by using a conditional check, we don't have to raise the minimum supported Glib version.

src/main: divert log to stderr

---

docs/scenarios.rst

Avoid having bootname defined for the rescue slot, as it when updated
would result in RAUC would overwrite bootorder to prefer the rescue slot.
Signed-off-by: Sean Nyekjaer <sean.nyekjaer.ext@siemensgamesa.com>

docs/scenarios: remove bootname for rescue slot in additinal rescue slot

---

docs/reference.rst

The InstallBundle() D-Bus method prototype is accidentally named Install(), probably caused by copy'n'paste. Fix that.

docs/reference: fix InstallBundle() D-Bus method prototype

---

src/context.c
test/service.c

Later install steps were showing 100% due to the way
sub-step percentages were being summed. Fixed by only
allowing the root install step to report 100% progress.
In the case where other steps want to report 100%, they
are reduced to 99% instead to avoid confusion.
Fixes: #711
Signed-off-by: Steven Rau <steven.rau@vecima.com>

Only allow the root step to report 100% progress

---

rauc.1
src/main.c

This option was already available for other commands, like
'rauc convert'.
Sometimes a bundle needs to be extracted but it may not be possible, or
desirable, to perform the standard bundle access checks.
For example if RAUC is executed from a controlled environment where the
ownership of a bundle is not an issue. Or when obtaining the underlying
device is not possible at all, e.g. when inside an unprivileged Docker
container.
----
I didn't add `--no-verify` because that's potentially more risky, and usually `--trust-environment` should be enough to cover nearly all use cases.

Add --trust-environment for 'extract' and 'extract-signature'

---

docs/integration.rst
docs/using.rst

Stumbled upon a broken link, so I used [linkchecker](https://linkchecker.github.io/linkchecker/) to check all doc pages.

docs: fix broken links to GLib/U-Boot docs

---

README.rst
docs/integration.rst

Just mentioning =y can be confusing, so mention that =m is fine, too.

README, docs/integration: be explicit that kernel modules are sufficient

---

docs/reference.rst
include/config_file.h
src/bundle.c
src/config_file.c
src/update_handler.c
test/config_file.c
test/minimal-desync-test.conf
test/rauc.t

This PR partially addresses #748 and adds an initial optional support for Desync.
I updated the Debian base version of `test/Dockerfile` to the latest stable release because Desync needs at least Go 1.14 and the old-stable (buster) has Go 1.11 (with the 1.15 in buster-backports).
This change is a pre-requisite for Desync and can be merged separately, if preferred.
While Desync is mostly a drop-in replacement of Casync, some of its launch options are different.
The most notable change is that Desync expects a seed in the form of `.caibx`. This probably requires some additional thinking/discussion to decide what's the best way to handle that (where do we look for this `.caibx`? If it is not available, should we regenerate it on the fly?)
For this reason I left out the seed for now to try …

Initial desync support

---

Makefile.am
docs/advanced.rst
docs/reference.rst
include/slot.h
include/utils.h
src/config_file.c
src/mbr.c
src/slot.c
src/update_handler.c
src/utils.c
test/boot_raw_fallback.c
test/common.c
test/common.h
test/update_handler.c

Some SoCs (like the Rockchip RK3568) contain a fixed ROM code that searches the possible boot media for valid images in a defined order. Usually this happens at two or more fixed addresses.
This branch adds support to implement a failsafe update of the bootloader for such systems.

atomic bootloader update for SoCs with redundant copy support

---

docs/integration.rst

docs/integration: add a hint to specifiy the file used to store GRUB env

---

Makefile.am
include/stats.h
src/nbd.c
src/stats.c
test/stats.c

This is preparation for additional testing infrastructure. By adding a label to
the RaucStats, we can queue completed (freed) stats for later checks in unit
tests. This also allows us to support `g_autoptr(RaucStats)`.

stats: add g_autoptr support, label property and some testing helpers

---

src/update_handler.c

Previously, this printed each invalid character one-by-one during checking.
As this is derived from the slot name, we don't need to complain about invalid
characters.

src/update_handler: remove debug message in vfat_label_generator

---

src/nbd.c
src/stats.c

We can now set a label when we create a stats struct and a prefix when we print it.
Combine both in `r_stats_show()` and adjust the code in `nbd.c` accordingly.

improve stats messages

---

docs/reference.rst

Fix Typos in Documentation

---

.github/workflows/tests.yml

The Ubuntu mirrors no longer provide 21.10, so we have to move to 22.04.
As 22.04. uses OpenSSL 3.0.0, we need to accept some deprecation warnings.

fix stable CI builds

---

docs/reference.rst
src/manifest.c
test/manifest.c

The `meta.<label>` sections are intended to provide a forwards-compatible way to
add data to the manifest which is not interpreted by RAUC in any way.
Currently, they are just ignored when reading a manifest. In future releases,
they will be accessible via `rauc info`, the D-Bus API and in hooks/handlers.

manifest: ignore meta.<label> sections in the manifest

---

src/signature.c

This replaces `ERR_get_error_line_data()` by `ERR_get_error()`
`ERR_get_error_line_data()` was deprecated with OpenSSL 3.0.
We have never used line data anyway, thus we can use `ERR_get_error()` instead and will be compatible with all supported OpenSSL versions.
This also significantly simplifies error handling code.
:bulb: Note that oe-core master already uses OpenSSL 3.0
http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-connectivity/openssl

Make Error Message Handling OpenSSL 3.0-Compatible

---

src/main.c
test/rauc.t

It is not necessary (but instead misleading) to have the `--cert` and `--key` arguments as global options because they apply to only a very few commands.
Introduce a purpose-driven (rather than subcommand-driven) GOptionEntry for this.

src/main: limit --cert and --key arguments to signing commands

---

include/mount.h
src/mount.c
test/common.c
test/install-content/custom_handler.sh

These were added to simplify testing before we had the qemu test environment.
By now, they are mostly useless, as other things will break without root. Also,
failed sudo accesses can cause annoying audit messages for admins.

mount: remove use of sudo when running as non-root

---

test/nginx_backend.py

This fixes the following warning:
```
.../rauc/test/nginx_backend.py:15: DeprecationWarning: Changing state of
started or joined application is deprecated
```

test/nginx_backend: avoid DeprecationWarning when changing application state

---

test/update_handler.c

It seems to occur that `sum_target_written` is zero.
This currently causes CI checks to fail sometimes unexpectedly.
Fix this by also allowing 0 as we cannot certainly determine yet which factors influence the found chunks for the ext4 test case.
For reference: https://github.com/rauc/rauc/runs/7895842002?check_suite_focus=true

test/update_handler: do not fail when sum_target_written is zero

---

src/update_handler.c

We must prevent using the fallback handler match when slot type is
'boot-emmc' regardless of whether eMMC support is enabled or not.
Thus move the corresponding match out of the #if statement.
Fixes: c0f8ad4e

src/update_handler: unconditionally avoid fallback for boot-emmc

---

CHANGES
docs/advanced.rst
docs/integration.rst
docs/reference.rst
include/manifest.h
include/update_handler.h
src/bundle.c
src/main.c
src/manifest.c
src/update_handler.c
test/install.c
test/manifest.c
test/update_handler.c

Since the release of 1.7, it turned out that the name 'incremental' for this
functionality is confusing.
Accordingly we decided to rename it to 'adaptive' for 1.8 and accept the
downside of not being able to benefit from compatibility with 1.7.

rename incremental mode updates to adaptive mode updates

---

src/bootchooser.c
src/main.c
src/mark.c

This series aims to fix a number of redundant error message printouts in the context of boot selection handling.
By introducing a clearer scoping when a function should add which information (and, more important: which not), we should be able to better prevent these annoying redundancies which likely confuse the reader.
The series also rewrites some useless or imprecise error messages to be more concrete with telling what actually failed and thus to ease identifying issues.

Improve boot selection error messages and scoping

---

test/update_handler.c

When running CI from GitHub Actions, sum_source can obviously be 29 in some cases. Since this is no exact science anyway, be less strict here to prevent false-positive test suite failures.

test/update_handler: be less strict with sum_source

---

src/context.c

This allows us to detect configuration errors earlier and avoids problems where
other parts of RAUC expect this to exist.

src/context: create the data directory on startup

---

src/bundle.c
src/context.c
src/mount.c
src/slot.c

The `g_mkdir_with_parents()` documentation notes:
> Returns -1 if an error occurred, with errno set.
Since We should not silently drop the cause if we could present it to the user, use `errno` to create a more precise `GError` code and message.
Based on #958

src: obtain error from errno if g_mkdir_with_parents() fails

---

Makefile.am

Compared to the git repository there are a few files missing in the 1.7 tarball. Add them to EXTRA_DIST.
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>

Makefile.am: Add some more test files to the dist tar.xz

---

src/mbr.c
test/boot_switch.c

Otherwise `partition_size_le` will be 0 and region calculation will be invalid and fail with something like:
> Failed updating slot bootloader.0: Region start address 0x40000 is in area of partition 3 (0x0 - 0xffffffffffffffff)
Checking for the partition size to be 0 is exactly what util-linux does in this case, too:
https://github.com/util-linux/util-linux/blob/364de8f4f5625d17094a4d6e9b5fb49cb19c20a4/libfdisk/src/dos.c#L158
To have test coverage for this, simply remove the fourth partition in corresponding test case.
Fixes: #665

src/mbr: skip empty partitions in is_region_free() check

---

README.rst

This allows easily opening the link in a desktop element install or 
other matrix clients.

Readme.rst: link to matrix.to instead of app.element.io

---

src/bundle.c

Fixes: #976 (079b97438c6f1d06275bec7e4a8feb1d7e094336)

src/bundle: remove excess newline discovered by uncrustify

---

docs/index.rst

The C variant is more actively supported and the primary choice compared to the python evaluation variant.

docs/index: mention rauc-hawkbit-updater instead of rauc-hawkbit

---

test/dm.c

Sporadically, the test cases for detecting modified data fail because we were
still able to read the original (un-modified) data from the bundle after the
backing file was manipulated. While it seems to happen mostly in GitHub
Actions, it is still reproducible in QEMU by looping over the specific test
cases.
Although we use fsync() and drop_caches, we still sometime read the unmodified data.
We tried to use sync() and modified timing in the test case, but this was not a
reliable fix.
Instead, we now open the dm devices with O_DIRECT to avoid interacting
with any caches. As reading from O_DIRECT FDs requires page-aligned buffers, we
need to use aligned_alloc() instead of placing the buffer on the stack.

fix sporadic device mapper test failures

---

docs/advanced.rst
docs/examples.rst
docs/faq.rst
docs/scenarios.rst
docs/using.rst

It's better to be explicit about what the bootloader partitions are for and what should be stored somewhere else.

docs: improve bootloader update documentation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/SUPPORT.rst
.github/pull_request_template.md

This should help point users to the Matrix/IRC channel and GitHub discussions instead of opening issues.
Also add some hints in a pull request template and information on how to get support.

add GitHub configuration for issues, pull requests and general support 

---

src/utils.c

It's my first PR. Please let me know if I did something wrong.

src/utils.c: fix null reference error for g_propagate_prefixed_error

---

README.rst

This does not indicate code quality anymore, but at least a successful execution of the check.

README.rst: replace lgtm badge by CodeQL workflow status badge

---

docs/reference.rst
include/manifest.h
src/manifest.c
test/manifest.c

Since 3cc11ecd34a1e03e99c8798fd1e9bd1a976cbf94, RAUC ignores `[meta.*]` sections in the manifest. With this PR, the metadata entries are parsed and written back to the manifest during bundle creation.
Still missing is support for passing the entries to `rauc info`, the D-Bus API and hook/handlers.

manifest: parse and store metadata

---

.github/workflows/tests.yml

The armel arch cross build currently fails: https://github.com/rauc/rauc/actions/runs/3828804526/jobs/6514792764
Fix this by replacing qemu-user-static docker image with the corresponding ubuntu package.
While at it, update to bullseye and add a bit more logging output.

CI: fix (armel) cross build

---

include/utils.h
src/update_handler.c
src/utils.c
test/update_handler.c
test/utils.c

In some cases, we can abort early if the image in the bundle is too large for the slot. This is not possible when installing tar archives or when writing images to slot which point to a file.
Fixes: #1008

Check image size before starting installation

---

.github/workflows/coverity.yml

Since we moved to meson here, invoking 'make' will let coverity fail.
Tested on my github profile.

.github: workflows: coverity: use meson build command

---

docs/reference.rst
rauc.1
src/main.c

* Notes that `--intermediate` supports PKCS#11
* Makes `--intermediate` command-specific
* Adds help arg text
* Adds missing note of `RAUC_KEY_PASSPHRASE` in help
* Updates man
* Updates help text
* Updates doc

Documentation and usage updates around signing parameters (primarily --intermediate)

---

.github/workflows/tests.yml
test/meson.build

Coverage data is expected to be generated and has not been (re)enabled yet when transitioning from autotools to meson in CI tests.

.github: workflows: tests: (re)enable coverage in builds

---

data/meson.build
qemu-test-init

When 'service' option is disabled, there is no point in installing service files.
Since currently all files installed from data/ are service-related, simply use subdir_done() here.
This is something that is wrong in autotools, too. But since we intend to remove autotools support in the near future, fix this for meson only.

data: allow skipping service files installation

---

src/context.c
test/context.c

Do not invoke any target-related context setup steps if no config is required.
This is safe since config mode is 'required' for all target-related subcommands (like 'service') that need to have specific context available (such as bootname, etc.).
With this we gain two major benefits:
* Not invoking pointless procfs, sysfs and mount inspections when running as a host tool
* Removing the misleading 'info'-Messages like:
> rauc-Message: 13:53:56.765: Failed to resolve realpath for '/dev/mapper/Root-root'
e.g. when running rauc 'host' subcommands from a container
Resolves #846
Fixes #737

Skip target-related context setup if no config is required

---

src/bundle.c

We cannot encrypt plain bundles and these do not even initialize the bundle->manifest member. Thus we ran into a segfault here when attempting to evaluate bundle->manifest->bundle_format:
Fix this by checking for bundle->manifest being NULL first.
Fixes: #1054

src/bundle: fix plain bundle detection for rauc encrypt

---

rauc.1
src/main.c

The list of RAUC commands increased over the last releases.
Together with the dual use of RAUC as host and target tool it becomes harder to distinguish between host and target tool usage.
While for some commands (as 'rauc info') no clear category can be found, for others (as 'rauc service' or 'rauc status') the distinction is quite clear.
To better guide the user, we split the subcommand info prompt into 'bundle handling' and 'target' subcommands.

Split help into bundle handling and target commands

---

README.rst
docs/reference.rst
docs/using.rst
src/de.pengutronix.rauc.Installer.xml
src/main.c

This is still missing in various places.
Also fix the 'rauc info' help text to use `BUNDLE` instead of `FILE`.

Document URL as proper argument for 'rauc install' / InstallBundle

---

docs/reference.rst
docs/using.rst
src/de.pengutronix.rauc.Installer.xml
src/service.c
test/service.c

The old 'InfoBundle' method lacked the capability of passing additional arguments, which prevented adding a lot of features in the past.
Compared to the existing one, the new method differs only in the additional array-of-string-variant parameter 'args'.
This allows passing all kinds of future additional simple arguments.
To guarantee API stability, the old method will be kept as an alternative.
This builds on top of #965 but with the review feedback addressed.
Closes #965.

Introduce new 'InspectBundle' D-Bus API 

---

docs/examples.rst

List more known projects that provide a reference integration with RAUC by extending the already-existing chapter.
Also, add a few more details.

docs/examples: extend example integration section

---

include/manifest.h
include/slot.h
src/config_file.c
src/install.c
src/main.c
src/manifest.c
src/service.c

This introduces a manifest hash that is calculated when loading the manifest from the bundle.
Together with 'verity' (or derived) bundle formats, this will allow unambiguously identifying a bundle, since the verity root hash is also part of the manifest and thus indirectly both the payload and the meta data are part of the hash.
The information is exposed both for bundle introspection (`rauc info`) as well as system introspection (`rauc status`) and thus allows for example to see if a given bundle is exactly the one that was installed on the system.

Introduce Manifest Hash

---

src/config_file.c
src/slot.c

I've split out the slot parsing from `load_config()`, which has grown much too long.
Also fix a minor memory leak in the handling of the data directory for slots.

refactor config file parsing and fix memory leak in slot handling

---

contrib/uboot.sh
src/bootchooser.c
test/bootchooser.c

* The remaining attempts are hexadecimal numbers (due to `setexpr`) but without a prefix
* The comparisons should take this into account
* Previously [the comparison]() failed for all values containing non-decimal digits like 'f', for example
```
=> setenv BOOT_A_LEFT b00d
=> if test ${BOOT_A_LEFT} -gt 0; then echo greater; else echo not greater; fi
not greater
```
* Providing the prefix when comparing with `test` gives the expected result
```
=> if test 0x${BOOT_A_LEFT} -gt 0; then echo greater; else echo not greater; fi
greater
```
* As `setexpr` emits the result without prefix, adding the prefix when setting the variable is not possible
*  RAUC also should write hex values to the U-Boot environment consistently
* Previously a successful update left the new boot slot with its remaining …

Fix number format handling for U-Boot

---

docs/meson.build

Since we do not track all doc input files, we cannot say if sphinx needs to rebuild. Thus, with the configuration so far, meson would have built the docs only once and then assumed they were built.
Since sphinx can track required rebuilds itself and does not rebuild unnecessary parts, we can safely enforce always calling sphinx here by settings the target as 'stale'.

docs: meson.build: add input files as build dependencies

---

meson.build
version-gen
version.h.in

This creates a `version.h` file with version information derived from `git describe` using `vcs_tag`.
The `version.h` include will be injected into rauc and librauc builds.
For `meson dist`, no git information will be available, thus `meson.project_version()` serves as a fallback.
However, the generated tarball then still produces a non-fatal message that might upset users:
> fatal: not a git repository (or any parent up to mount point /)
Note that meson does not seem to allow including generated files in dist tarballs by design, thus adding a '.tarball-version'-like file will not be possible.

meson.build: support generating version information from git

---

src/main.c

For human-readable output formats of `rauc info` or `rauc status` we can print the image sizes in human readable units, too.

src/main: print sizes in human-readable form

---

src/bundle.c

* This PR adds support for FTPS
* It depends on https://github.com/systemd/casync/pull/266 to do the same for casync
* libcurl already supports FTPS in its default configuration
* We just need to allow the FTPS URL schema at RAUC
* Successfully tested casync updates via FTPS (unsing vsftpd as server)

Add support for FTPS

---

include/context.h
src/context.c
src/install.c
test/service.c

This adds a function for formatted weighting of progress and uses it to give the 'check_slot' progress sub step of 'update_slots' a weight of 1 while the actual 'copy_image' step gets a weight of 9 to reflect that in 'check_slot' hardly any work is done in contrast to 'copy_image'.
An alternative could be to just fully remove the check_slot sub step which does not check nearly as much as the name might indicate.
Without this patch and with having a single slot, progress will be:
```
40% Updating slots
40% Checking slot rootfs.1
70% Checking slot rootfs.1 done.
70% Copying image to rootfs.1
99% Copying image to rootfs.1 done.
```
Note that this almost instantly jumps from 40% to 70%.
With the patch instead, we get:
```
40% Updating slots
40% Checking slot rootfs.1
46% Checking slot …
```

src: give check_slot low progress weight

---

.github/workflows/tests.yml

I had prepared this since I thought I could reproduce another issue with this (which I couldn't), but maybe this is something we want to have anyway? It's not really 'stable' testing then anymore but 'compatibility' testing?..

Extend tested distros

---

src/manifest.c

In the error case, we didn't free the value string. Use `g_autofree` and `g_steal_pointer` to handle this.

src/manifest: fix memory leak

---

src/install.c
test/install.c

The memory leakage 'fix' introduced in a6c17a402 ("src/install: avoid leaking string if multpile mount points match") erroneously uses 'break' where it should have used 'continue'.
As a result, external mount point detection aborts way too early in some cases and further external mount points will not be detected then.
This is also not ideal in terms of safety, since it could lead to unintentionally overriding a still-mounted partition which RAUC refuses normally.
This affects all RAUC releases since (including) v1.2.

src/install: un-break external mount point detection

---

src/service.c

Just before invoking the `cmd_handler` in `main.c`, the context is configured. Thus we should not directly configure it again from within our command handler `r_service_run()`.

src/service: do not configure context twice

---

include/config_file.h
include/install.h
src/context.c
src/install.c
src/main.c
src/service.c
test/context.c
test/install.c
test/rauc.t

This splits up slot state determination and external mount point detection and ensures slot state determination is called quite early in the service.
This removes unnecessary re-determination of static data and allows us to access slot state information earlier in the future.

Rework Parts of Slot State Determination

---

docs/reference.rst

Commit dc6e2b2faaa6 introduced a more detailed description of RAUC's central statusfile that is cut down again in bb02c9edcf21 after the implementation of RAUC's shared data directory. However the description was cut down a little too much as the "above-noted requirements" cited later in the text were removed, as well - fix this.

Amend Description of Key ``statusfile``

---

src/bundle.c

At least since Linux 5.7 the Kernel supports the exFAT file system. So allow it to use modern flash drives as local file system in rauc.
The changes has been tested on a i.MX6ULL SoC embedded device called Tarragon (Linux 6.1) with a common flash drive (Sandisk Ultra USB 3.0 64 GB).

src/bundle: allow exFAT as local file system

---

test/common.c

This should avoid some possible leaks.

test/common: convert to g_autofree for strings

---

configure.ac
meson.build

This allows us to use g_ptr_array_find().
Versions newer that 2.54.0 are used by the oldest releases of mayor
distributions still in long term support.
- Debian buster: 2.58.3
- Ubuntu bionic: 2.56.1
- Yocto dunfell 2.62.2

update glib version

---

src/bundle.c

Otherwise, unsquashfs will just fail with a possibly confusing error message.
Fixes: #1028

src/bundle: ensure that the output directory does not exist before extracting

---

docs/reference.rst
docs/using.rst
include/context.h
include/utils.h
rauc.1
src/bundle.c
src/context.c
src/install.c
src/main.c
src/manifest.c
src/update_handler.c
test/bin/systeminfo.sh
test/config_file.c
test/context.c
test/install.c
test/service.c

This cleans up a bit of the handler code, fixes some issues and prepares for more.
The actual focus of this is to extend the already-existing `system-info` handler (that had no real purpose yet) with the capability to add and collect custom information. For now, these informations are made available in pre- and post-install handler env variables only, but there will be follow-up work to provide them via HTTP headers.
Preparation is related to #1114

Refactor and Extend `system-info` Handler to Obtain Generic System Information

---

.github/workflows/container.yml
.github/workflows/coverity.yml
.github/workflows/distcheck.yml
.github/workflows/scan-build.yml
.github/workflows/tests.yml

Node 12 based workflows are deprecated, so update to the current version.

.github/workflows: update to actions/checkout@v3

---

.github/workflows/sanitizers.yml
src/context.c
test/bundle.c
test/checksum.c
test/manifest.c
test/network.c
test/slot.c

For now, there are still several tests for which address sanitizer reports leaks, but we can still check for regressions in the others.

fix some leaks and add a address-sanitizer workflow

---

.github/workflows/tests.yml

Note that standard meson under debian buster is too old:
> meson.build:1:0: ERROR:  Meson version is 0.49.2 but project requires >=0.51.

.github: workflows: tests: test building against older debian releases

---

docs/reference.rst
include/manifest.h
src/bundle.c
src/manifest.c
test/manifest.c

There is no reason to start new projects with plain format bundles, so
recommend against it in the docs and when creating new bundles.
Also point to the migration section for existing projects.

recommend verity bundles by default

---

src/context.c

By using `r_context()` in methods that are called from the context, developers may quickly run into infinite recursions.
This can be quite unexpected. Thus explicitly error out and tell what's going on.

src/context: developer-friendly recursion error-out

---

docs/reference.rst
include/install.h
include/slot.h
rauc.1
src/config_file.c
src/install.c
src/main.c
src/service.c
src/slot.c

It can either be provided manually (via D-Bus or command line arg) or will be auto-generated.
The transaction UUID allows us to identify and track an installation run.
It is an important building block for adding future features like history logging, life cycle tracing, and more.
First of all, add a simple printout of the UUID when the installation starts so we can follow it in the logs.
Also see #1070

src: add installation transaction UUID

---

rauc.1
src/bundle.c
src/main.c

For the decryption use case, this specifies the decryption key.
The global `--key` option has been replaced by command-specific ones but the purpose of `--key` for 'rauc info' has not been considered.
Since the former global options are still available but hidden, using the options always worked but it has not been shown in the help output or man page.
Fixes #875.

src/main: add missing --key argument for 'rauc info'

---

src/install.c

The rework that introduced installation plan handling ignored the result of `handle_slot_install_plan()` and used the wrong jump label (`image_out`).
The handling belonging to the `image_out` label should be part of handle_slot_install_plan() and the formerly used `out` label should be used to abort the installation properly. We also need to save the failure information in 'res' to let `launch_and_wait_default_handler()` fail correctly.
Fixes 99ce07bc ("src/install: factor out per-slot image installation logic")

src/install: fix broken plan installation failure handling

---

include/context.h
src/context.c

For now, we just collect some information to be used in follow-up features:
* machine-id -> allows to identify the machine we run on
* boot-id -> allows to identify the boot we are in
Related to #1070 and #1114

Obtain system's boot ID and machine ID

---

src/bundle.c

The pread call confused the pointer size with the buffer size. Use a local constant for the size to make it easier to read.
Fixes: dbbb009e0d8f ("src/bundle: add function to completely read device")

src/bundle: fix read size for read_complete_dm_device

---

data/meson.build

The script needs to be executable. This got lost during meson transition.
Fixes #1165

data: meson.build: install rauc-service.sh with executable bit set

---

include/nbd.h
src/nbd.c

With _FILE_OFFSET_BITS=64 there is no "off64_t", but off_t is 64 bit long: https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#index-_005fFILE_005fOFFSET_005fBITS
While glibc defines the off64_t anyway, musl is more restrictive and only provides the "off64_t" when _LARGEFILE64_SOURCE is defined.
Signed-off-by: Christian Hohnstaedt <christian@hohnstaedt.de>

nbd.c: use off_t instead of off64_t with _FILE_OFFSET_BITS=64

---

src/nbd.c

As we have 5 retries, the default timeout results in 25 minutes total, which is much too long.

src/nbd: use a shorter connect timeout

---

include/mark.h
src/install.c
src/mark.c

* Fixes inconsistent step reporting of slot updates
* Fixes inconsistent error handling of `mark_active()`
* Fixes potentially marking multiple slots while installing
Closes #362

Cleanup, Refactoring and Fixes For Installation Handling and Slot Marking

---

src/hash_index.c

Note that it was not actually used uninitialized since using it depended on having 'found' set to TRUE which can only happen in a code path that also sets 'middle' to some value.
Closes: #1155

src/hash_index: initialize 'middle' for consistency

---

src/dm.c

Since we've bumped the minimum version to glib 2.56, we do not need to re-define methods available since 2.52.

src/dm: remove fallback implementation of g_uuid_string_random()

---

configure.ac

The actual name of the option (`--with-streaming_user` ) differs from the help text (`--with-streaming-user`). Fix this.

configure.ac: fix help text name of --with-streaming_user

---

meson.build

Looks like the default directories for system services and interfaces were pointing to wrong locations.
The build variable dbusinterfaces is currently not explicitly set by the recipe rauc.inc in meta-rauc. This causes bitbake not to find the proper package for file de.pengutronix.rauc.Installer.xml.

meson.build: fix dbus default directories

---

README.rst

Only meson versions (<0.54.0), as on Ubuntu 20.04 LTS don't support 'meson compile'. Mention this alternative until we can deprecate support for it.

README.rst: document 'ninja -C build' alternative to 'meson compile -C build'

---

Makefile.am
configure.ac
src/context.c
test/context.c
test/test-dummy-handler.conf

context->system_serial and context->config->system_variant was deleted even when no substitute is found in the script.
This breaks systems using DTB compatible variant setups when the script did not supply this information.
Keep off values not supplied by the handler script!

get_system_info_from_handler: do not step on existing values

---

include/utils.h
src/bootchooser.c
src/config_file.c
src/utils.c
test/config_file.c

Since efibootmgr 18, the default output of `efibootmgr` is now more verbose [1], which breaks the assumptions made by RAUC in regards to parsing the output. This issue is also affecting others [2].
Fix the parsing logic by unconditionally splitting on a tab in the detected name part of the boot entry, so that the unused data part can be discarded.
Emit a debug message for each found boot entry, as this helps in detecting issues in the future.
[1] https://github.com/rhboot/efibootmgr/commit/8ec3e9dedb3cb62f19847794012420b90f475398
[2] https://github.com/rhboot/efibootmgr/issues/169
This fix is not related to an open ticket, as I noticed this quite recently and got in touch on matrix to discuss a possible fix.
I verified this to work in an Arch Linux VM using efibootmgr 18 and a RAUC 1.10 …

Fix bootchooser for the output of efibootmgr 18

---

docs/advanced.rst
docs/reference.rst
include/bundle.h
include/config_file.h
include/install.h
include/nbd.h
src/bundle.c
src/config_file.c
src/install.c
src/nbd.c
test/config_file.c

This implements passing system information upon the first HTTP request when accessing the URL of a streaming bundle.
This allows the server to collect more information about the device in order to create more verbose logs or to actually build deployment logic on this.
Besides some standard information that is configurable, custom information can be provided by the `system-info` handler.
This implements parts of concept #1114

Add System Information HTTP Headers

---

test/meson.build

We've seen this fail with TIMEOUT in GitHub actions now a couple of times and also some successful runs take >250 seconds so that it's likely that the current limit of 300 is just too low for GitHub CI.

test: meson.build: increase timeout for sharness tests by 1 minute

---

src/config_file.c
src/install.c

So far, the slot status has only been written after a successful (not-skipped) slot update.
This makes it hard to identify what the actual content and state of the slot is.
Also, the existing `status=` field had only one possible value which was `"ok"`.
Besides some minor adaptions, the main aspect of this PR is to ensure the slot status gets updated even when the slot update failed or was skipped due to the 'slot skipping' mechanism.
In the first case, it also sets the status to `"failed"` to let the user know this slot is in an unusable state. When having skipped, it sets the state to `"skipped"` indicating it matches the content of the noted bundle information but was not explicitly written.

Ensure Consistent Slot Status

---

README.rst

Simply including the LGPL license text is not enough information to determine the license of a software project, as Section 13 of the LGPL allows licensees to choose the terms of "any later version of the license" if specified so by the copyright holders.
The information in meson.build implies "LGPL-2.1-or-later" as project license. As a minimal measure to make this information explicit, add the usual license notice and warranty disclaimer as recommended in the [GNU GPL How-To](https://www.gnu.org/licenses/gpl-howto.html#why-license-notices) (also see [https://www.gnu.org/licenses/identify-licenses-clearly.html]) to the README file, and also add a minimal copyright notice as required by Section 1 of the LGPL.
Let the LGPL badge at the start of the README point to the relevant section …

README: clarify license

---

.gitignore

The `qemu-test` script downloads the kernel to this filename.

.gitignore: add bzImage

---

src/install.c

Previously, if `r_slot_status_save()` failed after an slot handler failure, we reported the handler error with a mismatching prefix. Instead, capture the slot status error in a separate `GError` and report it explicitly.

src/install: fix error handling on status write failure during slot update failure

---

docs/advanced.rst
include/bundle.h
rauc.1
src/bundle.c
src/main.c
test/rauc.t

This option allows providing the slotclass of an image to ignore during conversion. Multiple images can be ignored by using the argument multiple times.
This can be useful to generate 'mixed' casync bundles that contain both .caidx/.caibx images as well as conventional ones.
Usage:
rauc convert [..] --ignore-image=rootfs input-bundle.raucb mixed-bundle.raucb
Fixes: #1200
Note: This is a proof-of-concept and a base for discussion only for now.

src: implement --ignore-image option for rauc convert (casync)

---

src/manifest.c
test/manifest.c

In some cases, it's useful to annotate images with more specific information than we currently have at the bundle level. For now, just use the same keys as at the bundle level.
In this change, we just ignore them to allow installation of bundles which contain them in the manifest.
Later, we should store this information in the slot status and expose it via D-Bus and `rauc status`.

src/manifest: ignore new per-image keys version, description and build

---

src/main.c
src/slot.c

Fix memory leaks in retrieve_slot_states_via_dbus()

---

include/mark.h
src/install.c
src/mark.c

So far, we have an `r_mark_*` function for marking "active" but not for marking "good" or bad.
This results in having to use different semantic layers/modules between different mark actions.
Fix this by introducing and using `r_mark_good` and `r_mark_bad`.

Make marking interface more consistent

---

Makefile.am
include/update_utils.h
meson.build
src/update_handler.c
src/update_utils.c

This renames copy_with_progress to r_copy_stream_with_progress and moves it to
a new update_utils module. Also change the return value to a `gboolean`, as a
partial copy is an error case for this function.

update_utils: make copy_with_progress reusable

---

docs/using.rst
qemu-test-init
src/main.c
test/rauc.t

This will be extended by artifact repository links later.

create links to active slot devices in /run/rauc/slots/active

---

test/Dockerfile

We don't wan't to switch to bookworm yet, so don't try to install python3-sphinxext-opengraph (which is not available in bullseye).

test/Dockerfile: remove python3-sphinxext-opengraph for now

---

test/Dockerfile

Later versions fail to build with:
```
/go/pkg/mod/golang.org/x/crypto@v0.8.0/curve25519/curve25519_go120.go:9:8: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.15/src/crypto/ecdh)
/go/pkg/mod/golang.org/x/net@v0.9.0/publicsuffix/table.go:5:8: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:19:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)
```

test/Dockerfile: pin desync to version 0.9.3

---

src/main.c

Instead of printing
> Activated: null (null)
which is not quite intuitive, print
> Activated: none
This also simplifies the logic a bit.

src/main: more user-friendly output when no slot is activated

---

src/update_handler.c
src/update_utils.c

* Fixes zero-sized image handling in combination with progress reporting
* Fix error propagation in `img_to_boot_raw_fallback_handler()`
Addresses parts of the issues mentioned in #1236.

Fix Arithmetic exception on Zero-sized images + Error Propagation Fix

---

subprojects/glib.wrap
subprojects/json-glib.wrap
subprojects/openssl.wrap

This allows us to build against a local copies of these dependencies (with --wrap-mode=forcefallback) and also supports static compilation for use in oss-fuzz.
These files were installed from meson's wrapdb.

add meson wrap files for glib, json-glib and openssl

---

include/config_file.h
src/config_file.c
src/service.c

A common usage issue with RAUC is to change the system configuration but not to restart the rauc service to re-read the configuration.
To make this more obvious, at least in the service log output, this implements a simple checksum-based checking for changes in the system.conf.
On config file loading, the checksum of the original parsed configuration is cached and used as reference for later comparisons of re-calculated checksums.
The checker function r_config_file_sanity_check() that implements the comparison is used first of all in the service on calls of 'install' or 'status' actions and prints a warning.

src: detect config file change and warn in service log

---

include/update_utils.h
include/utils.h
src/update_handler.c
src/update_utils.c
src/utils.c

This prepares for artifact updates:
- move open_ helpers to update_utils
- add new r_syncfs helper

make open_ helpers reusable and add r_syncfs

---

docs/contributing.rst
docs/integration.rst
docs/reference.rst
src/bundle.c
test/bundle.c
test/common.c
test/common.h
test/install-fixtures.c
test/install.c
test/service.c

This increases the flexibility for testing artifacts later.

test: fix pre-check tests and generate slot artifacts only when needed

---

README.rst

OpenSSL has moved from https://bestpractices.coreinfrastructure.org/ to https://www.bestpractices.dev/.

README: update OpenSSL badge URL

---

src/manifest.c

Credit to OSS-Fuzz for finding this issue.
Fixes: 1e2d723f ("src/manifest: explicit error when using [handler] args without filename")

src/manifest: add missing return on error

---

meson.build

`install_data()` as currently used puts the manpage to `/usr/share/man/rauc.1`, however the right place is `/usr/share/man/man1/rauc.1`. Use the dedicated meson macro `install_man()` to get this right.

Fix installation of rauc.1 manpage

---

.github/workflows/coverity.yml

Otherwise job will fail with
>  fatal: detected dubious ownership in repository at '/__w/rauc/rauc' | To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /__w/rauc/rauc
since the container user is not the repository owner.

.github: workflows: coverity: disable git unsafe directory check

---

.github/workflows/tests.yml

riscv64 is not available for bookworm, but we'll be able it use it with the next release.

.github/workflows/tests: switch to official multiarch Debian containers

---

src/main.c
test/rauc.t

In 3272c7ba ("src/main: support --no-verify for rauc resign"), the `--no-verify` argument was added to 'rauc resign' to allow resigning a bundle without the need to verify against the keyring.
Due to the additional sanity check in src/main, it was however not possible to omit the keyring and thus this implicitly enforces a (possibly unexpected) post-signing verification.
A check for a missing keyring is implemented in check_bundle() anyway, thus the extra check in `resign_start()` is safe to omit.
To ensure this is also covered by testing, we simply omit the `--keyring` argument in the no-verify resigning test.

src/main: fix --no-verify usage for rauc resign

---

.github/workflows/tests.yml
docs/meson.build
meson_options.txt

Currently there is a limited set of documentation installed by default. We already have the sphinx docs wired into the meson build, although there is no way for the end-user to install them.
Add an `htmldocs` option which guards both build and install of the docs. Thus people can opt out of, even if they have sphinx installed.
Issue: https://github.com/rauc/rauc/issues/1251
---
Thanks for wiring up sphinx to the meson build team. I've secretly waited for the autotools build to be merged, since wiring that wasn't fun :-P
Silliness aside, this PR addresses half the referenced issue hence why I didn't use "Fixes".

meson: add htmldocs option for installing the docs

---

src/bundle.c
test/rauc.t

So far, `rauc resign` and `rauc replace-signature` did not support crypt bundles.
While fixing some underlying inconsistencies, this PR adds support for both.

Add 'crypt' Bundle Support to 'resign' and 'replace-signature' Subcommands

---

include/utils.h
src/utils.c
test/utils.c

These support a persistent fakeroot environment, so multiple subprocess can be executed within the same environment (for example extracting a tar and generating a squashfs).

utils: add fakeroot helpers

---

include/utils.h
src/bundle.c
src/mount.c
src/update_handler.c
src/utils.c

We often run external tools without the need to communicate with them while running.
So add a helper which calls `r_subprocess_newv()` and `g_subprocess_wait_check()` instead of duplicating that everywhere.

simplify subprocess handling

---

docs/using.rst
src/main.c

These were listed only in the man page so far and are thus hard to guess for users.

List Available Format Options for `rauc info` and `rauc status`

---

test/service.c

We need the same system setup in both cases, but the bundle in only one of them. Refactor the fixtures into a generic one (`service_fixture_set_up`) and one for install tests (`service_install_fixture_set_up`).

test/service: simplify service fixture setup

---

test/common.c
test/common.h

This will be used for artifact installation tests, where we need to check if file ownership and created device nodes are correct.

test/common: add test_lstat helper

---

README.rst
docs/integration.rst
src/dm.c

CRYPTO_AES option is mandatory to have crypto support working in RAUC.
Adding a bit of documentation and a better error when RAUC fails setup DM for cypto format.

Adding CRYPTO_AES documentation

---

README.rst
docs/advanced.rst
docs/basic.rst
docs/index.rst
docs/integration.rst
docs/reference.rst
docs/using.rst
rauc.1

Before documenting artifact updates (for containers/external applications/data
files), we should avoid using the same term for different things in the
documentation.

avoid using the term artifacts in the documentation

---

qemu-test
qemu-test-init

This makes debugging easier when something fails in the service.

qemu-test-init: print backtrace for service threads if gdb is available

---

src/install.c
src/main.c
src/mark.c
test/install.c

While #1230 provided the framework for configurable event logging, this now aims to implement the actual events to log.
The list of events logged:
* system boot or service start
* slot update
* installation start
* installation success/failure/reject
* slot marking (good/bad/active)
Most events have a distinct MESSAGE_ID to allow identifying them (e.g. for later systemd catalog entry handling).
This is the first proposal of event items to log.
<details>
<summary>example human-readable log file content</summary>
```
2023-12-20T11:32:15Z: Booted into rootfs.0 (A)
boot ID: 55304525-445b-45b2-95e3-71d6646ca437
bundle hash: unknown
2023-12-20T11:32:16Z: Marked slot rootfs.0 good
2023-12-20T11:32:33Z: Service restarted
2023-12-20T11:33:56Z: Installation 871dbf94 started
transaction ID: …
```

Implement Actual Log Events for Configurable Event Logging

---

test/event_log.c

Avoid theoretical overflow issues by using the same type as `rotates_at` for the loop variable.

test/event_log: fix type mismatch

---

CHANGES
docs/advanced.rst
src/event_log.c
src/install.c
src/main.c
src/mark.c
test/event_log.c

The journald catalog uses UUIDs without dashes, as generated by `systemd-id128 new` (without `-u`), so remove the dashes while the change won't cause backwards-compatibility issues.
We don't consider the details of the new log events fixed yet, so please use them as a preview and for testing.
In a future release, they will be documented in a [journald message catalog](https://www.freedesktop.org/wiki/Software/systemd/catalog/).

remove dashes from message IDs and add note in changelog

---

src/bootchooser.c
src/mark.c
test/rauc.t

So far, `rauc status mark-*` methods allow to mark slots that are not bootable. For them, what happens then depends on the actual invoked bootchooser backend.
Given the current grub backend, for example, this will slightly accept it and produce env variables like `(null)_OK`.

Ensure Only Bootable Slots Can be Marked

---

test/service.c

With the rework of 8e2c45ed, these tests cannot be run as unpriviledged user anymore.
Fixes #1283.

test/service: run service tests only as root

---

src/config_file.c
src/signature.c
test/bundle.c
test/config_file.c

OpenSSL so far defined a number of certificate check purposes but none for 'codesign'. Thus RAUC added its own purpose check for this.
Since v3.2.0, OpenSSL now defines a 'codesign' check purpose itself which not only conflicts with the RAUC variant in naming, but also has some differences compared to the RAUC check:
* OpenSSL enforces `Key Usage` existence, while RAUC only checks that it allows digital signatures if it exists
* RAUC enforces that `Extended Key Usage` on CA certs allows code signing if it exists
While RAUC is stricter on the one hand and OpenSSL on the other hand, we tend to preserve the RAUC check first of all.
For this, the RAUC check purpose is renamed internally to `codesign-rauc` and the config file setting `check-purpose=codesign` will be mapped to this.
For where …

Resolve Conflict With OpenSSL's built-in Check Purpose 'codesign'

---

src/main.c
test/rauc.t

The current boot detection handling did not take into account that there is no booted slot when using `rauc.external` in cmdline and called `r_slot_status_load()` with `NULL` argument causing a
(rauc:676): rauc-CRITICAL **: 16:16:16.336: r_slot_status_load: assertion 'dest_slot' failed
Fix this by explicitly checking for external boot and also emit a dedicated log message since this might be relevant for the log, too.
Fixes #1313
Fixes b9e4cdce0879862126aeb786bdd7f6672e392ca9 ("src/main: log boot and service restart")

src/main: fix and add support for boot detection with rauc.external

---

docs/using.rst

Pre-install hooks currently offer a guarantee that the target slot will be mounted. For this, we explicitly error-out if the target slot is unmountable for any reason.
This can cause unexpected troubles when running this from a system that does not have the target slot formatted (yet) or where the target slot's file system is broken for any reason.
Be more explicit in the documentation about this fact.

docs/using: be more explicit on current pre-install hook implementation

---

CHANGES
meson.build

Update the meson version and fix a typo in the changelog.

prepare for 1.11.1 release

---

test/common.c
test/common.h

This makes it easy to create a `GPtrArray` containing some strings for use in test cases.
It will be used in artifact tests.

test/common: add helper to build a GPtrArray from a ;-separated string

---

.github/workflows/container.yml
.github/workflows/style.yml
.github/workflows/tests.yml
test/Dockerfile

This PR refactors our CI container builds to use podman instead of docker.
It also adds pre-built containers for arm/v5, arm/v7, arm64/v8 and 386, which allows us to drop the dependency installation under QEMU.
For now, we need to install a newer buildah/podman from Ubuntu noble, but we'll be able to drop that step when GitHub Actions adds an image for the Ubuntu 24.04 LTS release.
To show how the containers work, I've added one commit to pull them from jluebbe/rauc instead of the main repo. When this PR is reviewed, I'd drop that commit.

build multiarch CI containers, use podman and run user-level tests

---

test/update_handler.c

Fixes a non-severe defect in test code reported by Coverity.

test/update_handler: check return value of g_rmdir()

---

src/nbd.c
test/rauc.t

When `g_variant_dict_lookup()` does not find the given key, it does not modify the values of the arguments provided.
This results in `info_headers` being undefined and can cause the rauc-nbd-server to crash, which will result in a broken request on client side that lets RAUC terminate hard with:
(rauc:769): rauc-nbd-ERROR **: 15:40:30.553: failed to recv nbd config reply header
The behavior of `g_variant_dict_lookup()` has also recently been clarified in the glib documentation:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3334

src/nbd: initialize info_headers to NULL

---

docs/reference.rst

Using titles makes the index more useful and allows us to deep-link to a specific section. 
Sometimes, we noted required/optional keys in the description, but it's better make it easy to see.

improve structure of config and manifest reference

---

src/main.c

When running 'rauc install ..' and pressing Ctrl+C, a common expectation is that this will interrupt the ongoing installation.
However, there is no current support for this in RAUC and it is also not really trivial.
Thus, to at least prevent wrong expectations, handle `SIGINT` explicitly and emit a message to the user to inform about the ongoing installation.
In the same enhance the message emitted when trying to run `rauc install` with an ongoing installation in the background.

src/main: more explicit handling of rauc install user interruption

---

src/nbd.c

When the running nbd server fails to read from the remote HTTP(S) server, it will trigger a retry.
After 5 retires, it sets `xfer->reply.error` to `GUINT32_TO_BE(5)` with the intention to signal an IO error to the NBD client, which is the kernel's nbd implementation in this case.
But, when entering finish_read(), there was a check for the HTTP response code being != 206 (Partial Content) with a hard `g_error()`.
This handling was wrong, since when entering the method after the retry abort, we have to expect that the last HTTP response code indicated an error.
The least invasive fix for this is to just change the g_error() to g_message(). (It might be worth discussing if checking the response code here gives any benefit at all.)
With this change, the NDB client will now receive an EIO …

src/nbd: fix nbd server 'no more retries' handling

---

docs/reference.rst
src/install.c

Add the value as RAUC_MF_BUILD to the execution environment of the install hook.

src/install: add bundle/manifest build value to hook environment

---

docs/reference.rst

Also fix the rst syntax for the `statusfile` definition list entry.

document manifest syntax for image variants

---

src/install.c

The log message for a rejected 'unencrypted crypt bundle' will be emitted by the call of `log_event_installation_done()` anyway (and with proper `MESSAGE_ID`, etc.).

src/install: remove redundant installation rejection log message

---

src/bundle.c

If we only forward the parsing errors from load_manifest_*() methods, they will look like:
>Failed to create bundle: Key file contains line 'EOF' which is not a key-value pair, group, or comment
This does no real indication that it's the manifest that RAUC failed to read and will thus not be very helpful for people who are not that deep into RAUC.
With the prefix, we get a better hint now:
> Failed to create bundle: Failed to load manifest: Key file contains line 'EOF' which is not a key-value pair, group, or comment

src/bundle: prefix manifest load errors with hint on manifest

---

.uncrustify.cfg
src/bundle.c
src/main.c
src/nbd.c
test/dm.c
test/fakerand.c
test/service.c
test/update_handler.c
test/utils.c

This makes three uncrustify options stricter that have a manageable impact on the current code but can help to keep the style even more readable and consistent:
* enforce spaces around assignments, comparisons, and boolean operators
* add spaces after commas

Slightly Stricter Style Checks

---

docs/integration.rst

They are not unique in an A/B setup, so the mapping depends on the udev execution order.

docs/integration: recommend against /dev/disk/by-label/

---

data/meson.build
data/rauc.catalog
meson.build
meson_options.txt

The systemd journal message catalog [1] is a proper way to enrich journal log messages with additional information.
Since the log messages emitted by the RAUC event logging/history framework have distinct MESSAGE_IDs set, we can leverage this mechanism to ship a catalog file for RAUC containing explanations for the defined messages.
This is a first attempt to provide helpful explanation texts.
Due to the limited consistency in error handling, especially in the context of installation errors, providing more specific help texts is not easily feasible at the moment.
The catalog file will be installed under `/usr/lib/systemd/catalog/rauc.catalog` unless otherwise configured.
To update the binary catalog index and thus to make the log messages appear in the journal, run
$ journalctl …

add systemd catalog support for event log messages

---

include/slot.h
src/main.c
src/slot.c

* Introduces a helper `r_slot_get_booted()` to get the determined boot slot
* Replace indirect re-determination of bootslot
* remove obsolete helper `r_slot_find_by_bootname()` then
Fixes #1360

Simplify and Fix Bootslot Handling

---

src/main.c

The bundle format is displayed in the standard "readable" output format for rauc info but it is missing from the shell and JSON formatters. Add it now.
Notice that I only added the format and not the format specific details shown by the "readable" format. I currently don't have a need for those, but we could add it if needed.
Example of the shell formatter:
```
rauc --output-format=shell info foo.raucb
RAUC_MF_COMPATIBLE='...'
RAUC_MF_VERSION='...'
RAUC_MF_DESCRIPTION='..'
RAUC_MF_BUILD='...'
RAUC_MF_HASH='085860cd4e09a942c6ed1bf4682a3b7d8cfd0574b1df2371a260ca25bf7f7f05'
RAUC_MF_FORMAT='verity'
```

add bundle format to shell and json output of rauc info

---

.github/workflows/sanitizers.yml
src/nbd.c

Most of the nbd asan tests are not running in the CI, as we're not using qemu there, yet.

fix some memory leaks in the NBD server and enable asan for the tests

---

docs/reference.rst
src/config_file.c

We've seen this option set in some cases even when streaming was enabled, so warn that it has no effect.

src/config_file: add a hint that max-bundle-download-size is not used for streaming

---

test/rauc.t

On some platforms faketime doesn't work as intended due to not supporting the libc functions that provide 64bit time_t on 32bit architectures.
This problem already made rauc fail to build in Debian unstable, see [Debian bug #1032177 ](https://bugs.debian.org/1032177). With the expectation that the problem will also affect rauc mainline at some time in the future, precautionarily check faketime being functional before using it.

test/rauc.t: test faketime before relying on it

---

.github/workflows/sanitizers.yml
qemu-test
qemu-test-init
src/install.c
src/service.c
test/asan.supp
test/boot_raw_fallback.c
test/boot_switch.c
test/service.c

To mark intentionally leaked memory (the glib thread local data), this also adds a suppression file.

fix minor memory leaks in the D-Bus service and related tests

---

test/Dockerfile

With some further changes, this will allow us to collect coverage data from the NBD helper as well.

test/Dockerfile: add acl to control access to coverage files in qemu

---

include/utils.h
src/bundle.c
src/context.c
src/main.c
src/utils.c
test/common.c

So far, we've only run the C-based test suite with address sanitized and fixed the resulting issues.
This PR fixes issues detected by running `./qemu-test` with a asan enabled and prepares for enabling these checks in CI as well.

fix leaks discovered via shell based tests

---

include/checksum.h
include/manifest.h
src/main.c
src/manifest.c
test/boot_raw_fallback.c
test/boot_switch.c
test/common.c
test/manifest.c
test/update_handler.c

A size of -1 indicates that no `size` key was given in the manifest. Instead of hardcoding that in everywhere, create a `r_new_image()` constructor function and use it instead.

manifest: ensure that size always defaults to -1 in RaucImage

---

qemu-test-init

As the nbd helper is running as a different user, it cannot write to the gcda files (which belong to the host user id). Instead of trying to solve this via umask or separate GCOV_PREFIXs per user with merging as post-processing, we use a /tmp/cov with a default ACL.
We need to create and configure that directory and then save the coverage data to the host before shutting down.

qemu-test-init: fix coverage for nbd helper

---

src/context.c
src/nbd.c

Glib already sets SIGPIPE to ignore when using gsocket and will do the same for gsubprocess from 2.82 as well [1]. As we want to handle all broken pipe errors explicitly, we should do it globally.
We add the call in r_context_conf instead of in main() to catch the relevant tests as well. For the nbd helper (which doesn't use a context), we do it on startup.
[1] https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3991

ignore SIGPIPE to handle broken pipes explicitly

---

src/install.c
test/install.c
test/test-install-same-false.conf

This fixes slot skipping handling on two levels.
With v1.10, slot skipping got broken while with v1.11 the slot skipping *detection* got broken (and thus hides the previously introduced issue).
The error that will be raised by v1.10 is:
```
Not enough substeps: update_slots (12/20)
```
Fix both and add a minimal test case that triggers an installation twice.

Fix slot skipping (install-same) handling twice

---

src/bundle.c

The ntfs3 kernel driver [1] uses this super block magic.
Refer to libfuse for a similar extension:
https://github.com/libfuse/libfuse/commit/869a4a6fa550ae054df01f9d50db68871f88ca4f
[1] https://lore.kernel.org/lkml/20210729162459.GA3601405@magnolia/T/

src/bundle: add ntfs3 kernel driver magic to known fs list

---

src/utils.c

- RAUC should not try to resolve a PKCS11 URI like a file path.  This would happen if a URI was given as the key in the [encryption] section of /etc/rauc/system.conf.
- If a PKCS11 URI is detected in the resolve function, just return it back to the caller.
- I think this only affected a URI given in system.conf.  A URI passed in on the command line was correctly unmodified - which is why the unit tests related to PKCS11 were passing.

Fix PKCS11 URI handling in /etc/rauc/system.conf

---

qemu-test-init
test/bundle.c
test/dm.c
test/hash_index.c
test/install.c
test/install_fixtures.c
test/meson.build
test/nbd.c
test/network.c

An issue with the current test suite is that it is quite hard to see
what tests were actually executed and what tests were just skipped.
Since the glib test suite produces TAP-parsable output by default, we
could use this to gain more detailed information on skipped tests.
Also enable verbose subtest output for run-qemu.
A general known issue is that in glib versions shipped with recent distros, the test log output emitted is duplicated: One tap-conform output with `# ` prefixed and the non-tap-conform default logging output.
The latter will cause non-fatal parsing errors for meson >= 1.0 versions that slightly pollute the log still.
This is fixed by glib commit https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3140/diffs?commit_id=6c714c9f46344c37b10c6e42936a54977f888d2d
However, we …

Use meson TAP protocol parser

---

docs/reference.rst
include/slot.h
include/utils.h
src/config_file.c
src/slot.c
src/update_handler.c
test/config_file.c

This PR adds an `extra-mkfs-opts` parameter to the system.conf file which can be used to provide extra options to `mkfs.ext4`/`mkfs.vfat`/`mkfs.ubifs` for each configured slot. 
An example configuration:
```
[slot.rootfs.0]
device=/dev/mmcblk0p5
type=ext4
extra-mkfs-opts=-i 8192 -L ROOT_A
bootname=SLOT_A
[slot.bootfs.0]
device=/dev/mmcblk0p2
type=vfat
extra-mkfs-opts=-F 32 -S 512 -n BOOT_A
parent=rootfs.0
[slot.rootfs.1]
device=/dev/mmcblk0p6
type=ext4
extra-mkfs-opts=-i 8192 -L ROOT_B
bootname=SLOT_B
[slot.bootfs.1]
device=/dev/mmcblk0p3
type=vfat
extra-mkfs-opts=-F 32 -S 512 -n BOOT_B
parent=rootfs.1
```
The meaning of the options depends on the type, see of course the man pages for `mkfs.ext4`/`mkfs.vfat`/`mkfs.ubifs` as appropriate.
See also issue #457, although note that this PR only …

Add extra-mkfs-opts to allow customising filesystem format options

---

test/boot_switch.c

g_bytes_unref_to_data doesn't provide a null-terminated string, so json_from_string might read beyond the end of the subprocess output. Instead of adding a null-byte ourselves, switch to g_subprocess_communicate_utf8.
This is a better fit, as json_from_string expects a valid UTF-8 string anyway.
Fixes: #1414

test/boot_switch: fix out of bound read

---

include/utils.h
src/bootchooser.c
src/utils.c
test/utils.c

When using `g_subprocess_communicate`, we often need to process the stdout as a null-terminated string (instead of a `GBytes`). While there is `g_subprocess_communicate_utf8`, we can't be sure that the output is actually valid UTF-8, so we need our own helper.
While we've not seen any issues with this in CI or in the field, it's better do be careful.

avoid possible OOB read in bootchooser backends

---

qemu-test-init

Without `/dev/shm`, `faketime` fails with `faketime: sem_open: No such file or directory`.

qemu-test-init: fix support for faketime

---

test/conftest.py
test/test_install.py
test/test_mark.py
test/test_service.py
test/test_status.py

The rauc_service fixture only pulled in the select_system_or_session_bus
fixture, which actually always set up a session bus. Also, each
individual tests pulled in the rauc_service fixture to ensure a D-Bus
bus was available.
Simplify this by replacing the select_system_or_session_bus and
rauc_service fixtures with a dbus_session_bus fixture. Then, pull it in
for the rauc_dbus_service* fixtures and drop it from the individual
tests.
Also add a short sleep to avoid busy-looping.

simplify dbus fixtures

---

test/conftest.py

The service will need some time to be available on the bus, so wait a bit before each try. This also gives the service more CPU time, so it may be faster.

test/conftest: avoid busy-waiting

---

docs/faq.rst
src/bundle.c
test/install-content/manifest.raucm
test/install-content/manifest.raucm.crypt

Currently, we modify and add files in the input directory. While this
isn't much of a problem now, we will need to delete converted files when
converting tar archives to file trees in the context of artifacts. That
would require the user to always re-create the bundle input directory
after running 'rauc bundle', which would be annoying.
It seems the simplest way is to hard-link all files from the input dir
to a .rauc-workdir subdirectory. This way, we don't need actually copy
any data and keep the rest of the bundle creation code unaffected.
For simplicity, we abort on anything in the input dir which is not a
regular file. If someone relies on the old (undocumented) behaviour of
including directories and symlinks in the bundle, please contact us.

use a temporary workdir during bundle creation

---

include/utils.h
src/main.c
src/utils.c
test/utils.c

We currently prepare the env variables for subprocesses and
shell-parsable output separately. To unify them, handle the shell
quoting at the end, during collection into a string.

refactor shell and environment variable preparation

---

qemu-test

This updated kernel now supports more filesystems and other features useful for development: https://github.com/jluebbe/linux/commit/13dac85770242a144142ed46719d230464adf04e

update qemu-test kernel to 6.6.36 and enable multidevs=remap for virtfs

---

src/bundle.c

The `output_stream_write_uint64_all()` and `input_stream_read_uint64_all()` methods had `GError` handling in theory, but actually, in most cases this will be pointless.
The reason is that there is a `g_assert()` that will fail before being able to indicate an error as the function return code and lead to hard aborts like:
> Bail out! rauc:ERROR:src/bundle.c:479:input_stream_read_uint64_all: assertion failed: (bytes_read == sizeof(tmp))
Fix this by directly returning `FALSE` in case of an error in the read/write calls and use the `g_assert()` only if no error has been detected before.

src/bundle: fix assert handling in uint64 read/write functions

---

src/main.c

The bundle hash must be set for `GLogField [7]` (`"BUNDLE_HASH"`), not `[5]` (`"SLOT_BOOTNAME"`).
Note that this left the `"BUNDLE_HASH"` field with a NULL pointer which the default log writer seems to handle but which fails when running in a systemd context where `g_log_writer_journald()` is used, too. There, the call to `strlen()` with a `NULL` pointer causes a segfault in RAUC.

src/main: fix wrong log field numbers in r_event_log_booted

---

src/main.c

The GPtrArrays are reference-counted correctly, but since they do not have a free func set, the newly allocated gchar's will not be freed.
Fix this by just using string literals instead.

src/main: fix leaking strings when printing hooks with 'rauc info'

---

src/bundle.c

Fixes memory leakages, over-allocations, and a sort of double-free crash for 'rauc convert' calls with archives as input images.
Fixes: #1461

Memory handling fixes for casync archive conversion

---

src/update_handler.c

The g_output_stream_close call was introduced at some point after the casync functionality for UBI was introduced (#501). This close call is fine for the copy_raw_image branch, but for the casync branch it causes the update to fail:
>rauc[250]: Installation error: Failed updating slot rootfs.1: Error closing file descriptor: Bad file descriptor
This was also mentioned in #1200. However it was not investigated there but instead sidestepped by using a different update approach.
Investigation with strace shows that the descriptor is closed twice:
```
290   openat(AT_FDCWD, "/dev/ubi0_1", O_WRONLY|O_EXCL|O_LARGEFILE <unfinished ...>
290   <... openat resumed>)             = 8
[snip]
290   close(8 <unfinished ...>
290   <... close resumed>)              = 0
290   close(8 <unfinished ...>
290 …
```

src/update_handler: fix double close on ubivol descriptor

---

include/event_log.h
src/event_log.c
src/install.c
src/main.c
test/event_log.c

In contrast to `g_log_structured()`, `g_log_structured_array()` takes a `log_level` as input argument but uses this for filtering only.
The `"PRIORITY"` field must already be present in the array fields provided.
Note that the messages are shown in systemd with default priority anyway.
A difference can only be observed when using `journalctl` with `-o verbose`.
Fixes: #1470

Add missing "PRIORITY" field to structured logging arrays

---

meson.build

Add some more useful warnings and allow declarations after statements. This makes is easier to declare (temporary) variables where they are
initialized. Together with g_auto*, this makes code easier to read.

update compiler warning configuration 

---

src/nbd.c

It may not be obvious that using HTTP/2 is important to get good performance when using streaming, so add a warning if an earlier version is used.

src/nbd: warn about slow installation when using HTTP/1

---

test/install.c

`data` (= `user_data`) is always passed to this function, so check it only once in the beginning.

test/install: avoid false positive in coverity

---

src/hash_index.c
test/update_handler.c

As building a hash index can take multiple minutes, we should tell the
user by default. Usually, this should only happen for the initial
installations, as the index is stored after writing the image.
Also reword the chunk count check, which can trigger for partitions as
well as for images, to use 'image/partition' instead of 'data file'.

improve log messages related to block hash indices

---

docs/advanced.rst
docs/basic.rst
docs/index.rst
docs/reference.rst

Disable TOC numbering and improve description of `adaptive=block-hash-index`.
The numbering makes the index harder to read and distracts from the
section titles, which are more relevant.

minor docs cleanup

---

meson.build

All other dbus directory locations are derived from libdbus pkg-config variables.
The dbuspolicydir instead only used the 'datadir' which has a fixed default and might thus not be valid on some distributions.
If the value cannot be obtained from pkg-config, the fallback remains the same as before.
Fixes #1479

meson.build: derive dbuspolicydir from libdbus datadir

---

docs/integration.rst

The link was not rendered as a link because of a missing `_`; see https://rauc.readthedocs.io/en/latest/integration.html#create-update-bundles-from-your-rootfs

docs: integration: fix link syntax

---

include/slot.h
src/install.c
src/slot.c
test/status_file.c

This fixes use of the block-hash-index, which wouldn't be found under
the old hash value during installation.
Fixes: #1158
Fixes: #1455

move existing slot data directory to "unknown"

---

src/install.c
test/install.c

Depending on the name of slots and classes, some of these messages can
be hard to understand. Highlight names by using quotes.

improve install messages

---

test/conftest.py
test/test_mark.py
test/test_status.py

To test with artifact repos, these files and directories will need to
exist. The simplest way is to reuse the system setup from the 'with
service' case, but without starting the daemon. Instead, provide a
command prefix to the test cases which sets the config path.

test: prepare system files with config for no_service tests

---

src/main.c
test/test_info.py

Using "\t" in the strings makes them hard to align in the source code and
results in tab characters in the output, which tends to disrupt the
alignment when copying the output somewhere else. So, keep it simple by
aligning using spaces in the source as well.

improve rauc info/status/help output by avoiding tabs

---

src/nbd.c

We already keep track of how much we have downloaded, so it's easy to show that in comparison to the full bundle size.

straming: show how much of the bundle was downloaded

---

include/shell.h
meson.build
src/install.c
src/main.c
src/shell.c
test/adaptive-test.conf
test/bin/postinstall.sh
test/bin/preinstall.sh
test/conftest.py
test/test_install.py

The manifest meta-data can be useful in the pre/post-install handlers for customization. By exposing them as environment variables it's no longer necessary to parse files from the bundle in the script.

expose manifest meta-data in handler environment

---

docs/reference.rst
include/utils.h
src/install.c
src/update_handler.c
src/utils.c
test/conftest.py
test/test_install.py

This uses the same variable names (and implementation) as `rauc info`.
Only the install-check hook is updated for now, as the slot hooks
currently don't have access to the manifest. We'd need to pass the
manifest or prepared variables down through all the update handles, but
that's a larger change.
Also add a helper class to build custom bundles in pytest test cases, based
on code from my artifact tests.

expose manifest meta-data in install-check hook environment

---

test/conftest.py
test/test_info.py

While we tested signing using PKCS#11 extensively, we didn't have tests for bundle decryption with PKCS#11 for key access.
This PR first refactors keypair loading, adds checks that OpenSSL works fine with the loaded keys and then adds a test case for decryption with a PKCS#11 key.

add test case for PKCS#11 decryption

---

src/bundle.c
src/hash_index.c
test/conftest.py
test/hash_index.c
test/test_bundle.py

When calling `r_hash_index_open()`, the ownership of the file descriptor provided should be handed over to the hash index and will be later closed in `r_hash_index_free()`.
Thus, the file descriptor provided must not be closed by the calling code anymore.
In `generate_adaptive_data()` however, the provided pointer was closed manually in the later error case, which would lead to a double-call of `g_close()` on the same pointer happened.
This was wrong anyway but results in a critical error in RAUC since glib version 2.75.0 which comes with a pickier `g_close()` handling: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2964
Fix this and add a hint to the function documentation.
Fixes: https://github.com/rauc/meta-rauc/issues/334

src/bundle: fix hash_index fd close handling

---

contrib/rauc-client/rauc-client
contrib/rauc-client/rauc-client.conf
contrib/rauc-client/rauc-client.service

This service implements a simple remote update service for rauc. The service will check at time or intervals if there is a new release available on the select update channel url. If the version is newer of the current installed version, it calls `rauc install` to install the update and reboot.
The service is simple enough to be compatible with busybox posix shell and can be easily integrated in any environment. It depends only on rauc and posix shell.

contrib: rauc-client: simple update service for rauc

---

test/conftest.py

We shouldn't send SIGKILL right away, but instead use SIGTERM to give the service some time to shut down cleanly and write coverage data. Otherwise, some coverage data is lost. In my tests, this improved overall coverage from 81% to 82%.

test/conftest: fix service shutdown

---

src/signature.c
test/test_encrypt.py

When rauc is used to encrypt a bundle, and a certificate file is provided which does not contain any certificate, then the encryption process was not stopped. Check the number of certificates when reaching end of certificate file. If this is zero, display an error and abort.

check if encryption recipient cert file containes at least one certificate

---

qemu-test-init

resolv.conf can be a symlink to /run (or somewhere else), so we need to remove the symlink to reliably replace it with our configuration. This works because we already mount an overlayfs at /etc.

qemu-test-init: remove potential symlink at /etc/resolv.conf

---

src/nbd.c

This should give some context for analyzing the problem.

src/nbd: show stats even if the NBD server exits with an error

---

src/main.c

The slot booted does not necessarily need to be a slot with a 'bootname' set since RAUC supports identifying slots via root= command line argument, too.
For these cases `fields[6].value` would have been set to `NULL` which made the journal log handler crash.

src/main: handle empty bootname in r_event_log_booted()

---

meson.build
test/meson.build

The tests lack a dependency on building the rauc binary. As a result, the tests will fail when running them directly from a fresh build directory:
meson setup build
meson test -C build
Fix this by defining the missing dependency for both the C-based and pytest-based tests.

meson: fix test dependencies on rauc binary

---

qemu-test

This updated kernel now has the SD/eMMC driver enabled as preparation for testing the boot-emmc slot type:
https://github.com/jluebbe/linux/commit/d8327fabb815615e86494e9e0a7325244472aa55

qemu-test: enable eMMC driver

---

.github/workflows/scan-build.yml
scan-build

It seems the report path has changed at some point, so fix it.
A working upload can be seen at https://github.com/jluebbe/rauc/actions/runs/11365746904/job/31614597488#step:8:23.

fix scan-build report

---

docs/faq.rst
src/bundle.c
test/test_bundle.py

Local symlinks in the same directory (containing no slashes) seem
harmless and can be useful in special cases for backwards compatibility,
so allow them.

allow local symlinks in bundle contents

---

.github/workflows/tests.yml

This allows codecov to show the coverage for each case separately.

.github/workflows/tests: upload coverage separately for service=true/false

---

include/bundle.h
src/bundle.c

Currently installing a remote bundle without having first enabled networking support at build-time results in a warning followed by a crash:
```
Mounting remote bundle not supported, recompile with --enable-network
installing http://192.168.8.15:8080/TODO-prod.raucb: Checking and mounting bundle...
g_str_has_suffix: assertion 'str != NULL' failed
rauc.service: Main process exited, code=dumped, status=5/TRAP
rauc.service: Failed with result 'core-dump'.
```
Fix this by early exiting in this case and propagating the error up.

src/bundle: gracefully abort remote bundle install if support is disabled

---

include/manifest.h
src/bundle.c
src/manifest.c
test/manifest.c

When using an `install` hook, the `pre-install` and `post-install` hooks will not be called. To avoid confusion, prevent generating bundles having both 'install' and 'pre-install' (or 'post-install') hook set for the same slot.
Fixes https://github.com/rauc/meta-rauc/issues/321

src/manifest: throw parser error for invalid slot hook combination

---

test/test_extract.py

Since the migration it extracted the normal bundle by mistake.
Fixes: 1470d2c2cc68 ("test: migrate extract tests to pytest")

test/test_extract: fix test for crypt bundle extraction

---

src/artifacts.c
test/artifacts.c

The `supported_repo_types array` must be properly terminated.

artifacts: fix repo type check

---

src/signature.c

As specified in the documentation, setting `G_MESSAGES_DEBUG=all` is supposed to enable log output for all logging domains. However the check to print CMS info introduced by
2cd407600a35eb51995c53bf97fc9cdb0d0fade4
only checks if `G_MESSAGES_DEBUG` contains `-signature`.
The goal is to make this check consistent with the rest of the program and the documentation. This does not affect the `-d` command line option as this uses the `rauc` debug message domain. But when one requests `all`, there should be all messages.

src/signature: fix CMS debug output check

---

data/rauc.service.in
docs/examples.rst
docs/integration.rst
docs/reference.rst
docs/using.rst
rauc.1
src/context.c

Traditionally, programs look up their configuration in /etc and this is
also what RAUC has been doing so far.
The modern pattern is to consult configuration files at a number of
locations. The default distro-provided config goes into /usr/lib,
which may be even read-only.
A runtime override is possible by placing a configuration into /run,
which masks the distro-provided config. The old location in /etc becomes
the highest priority override and is left to the system administrator.
Putting RAUC along with its configuration into /usr is called hermetic
/usr. The search path order implemented here is the recommendation
described in this patch is aligned with the UAPI group's Configuration
Files Specification[1].
The specification goes beyond what is implemented here and describes
also …

support locating system.conf in /usr and /run

---

.github/workflows/tests.yml
.gitignore
qemu-test
qemu-test-init
test/conftest.py
test/test_write_slot.py

This required some fixes to QEMU's eMMC emulation and needs [one patch that is still pending](https://lore.kernel.org/qemu-devel/20241015135649.4189256-1-jlu@pengutronix.de), also available at https://github.com/jluebbe/qemu/commit/6d41ee1ac963fbdcea46d00764d835fabf23852a.
To make further tests easier, I've also added a (minimal) fixture to build a `system.conf`.

test boot-emmc slots in QEMU

---

docs/integration.rst

The `bundle.bbclass` file was moved from `classes` to `classes-recipe`. This PR adjusts sources to changes.

Update `bundle.bbclass` references

---

docs/reference.rst
src/install.c

We currently only define RAUC_SYSTEM_VARIANT for hooks in the bundle, but not for handlers; unless we have a system-info script that sets RAUC_SYSTEM_VARIANT.
This can be confusing and the variant is a useful info to provide to handlers, so let's make it available.
---
If you add a feature, please answer these questions:
- What do you use the feature for?
I used to have a system-info handler setting `RAUC_SYSTEM_VARIANT`, which I have now replaced by having two configs, each with its own `variant-name` and installed dynamically into `/run/rauc/system.conf`. I was surprised to see `RAUC_SYSTEM_VARIANT` unset in the pre-install handler.
- How does RAUC benefit from the feature?
It makes it easier to write pre-install handlers that do checks depending on the variant.
- How did you verify the …

install: define RAUC_SYSTEM_VARIANT for handlers

---

src/install.c
test/service.c

This makes the output more user friendly on systems where the bootname is the common way to refer to a slot.
```
...
40% Checking slot rootfs.1 (secondary)
46% Checking slot rootfs.1 (secondary) done.
...
```
If no bootname is specified

Print bootname during install

---

src/de.pengutronix.rauc.Installer.xml

Adds qt type annotations so classes can be generated with `qdbusxml2cpp`.

Add missing qt type annotations

---

docs/reference.rst

* Updates slot status file documentation to better reflect today's perspective
* add documentation for 'status' field
* add documentation for system status

docs/reference: Update and Extend Slot/System Status File Documentation

---

test/conftest.py
test/helper.py
test/test_install.py
test/test_mark.py

So far we had no assertions testing that the boot selection backend actually changes the boot status on installation or manually `mark-*` calls. Here we add basic support for testing this.

test: Support Testing Boot Status Changes

---

README.rst
src/bundle.c

Unlock TFTP support for upgrades.
Tested extensively in the [Infix NOS](https://github.com/kernelkit/infix/) project.

Add support for TFTP

---

src/bootchooser.c

This fixes a spelling typo by adding the missing 'r' to the word primary in the function name bootchooser_order_primary().

src/bootchooser: fix spelling typo in code

---

include/emmc.h
src/emmc.c
src/update_handler.c
test/test_write_slot.py

The only valid `BOOT_PARTITION_ENABLE` bits for boot partition handling are:
0x0: Device not boot enabled
0x1: Boot partition 1 enabled for boot
0x2: Boot partition 2 enabled for boot
All other values either mean boot partitions are not selected or are 'Reserved' values. Make the method `r_emmc_read_bootpart()` fail for these values with an explicit error message.
This can prevent RAUC from performing eMMC boot partition operations on actually invalid configurations.
While at it, this PR also introduces dedicated error codes in `src/emmc.c` and adds some cleanup and simplification of code.

src/emmc: Error-Out for invalid boot partition configuration and use more explicit errors

---

test/conftest.py

In the future, we want to be able to customize the `system.conf` per test-case.
By moving the necessary startup/shutdown code from a helper and special-purpose fixtures
to generic code in the `System` class, we can change the config via the `system` fixture before
starting the service.

refactor service startup for pytest-based tests

---

docs/reference.rst
include/context.h
rauc.1
src/config_file.c
src/context.c
src/main.c
test/test_info.py

add -C option to set/overwrite config file parameters (currently only for keyring:check-crl=false and keyring:check-purpose=codesign)
Fixes: #953

Add -C option to overwrite config file parameters

---

src/install.c

This PR aims to fix slot selection by checking slot status with the checksum incase of reinstalling bad slot with the same image
Fixes: #1554

Check the slot status in case of reinstalling of failed slot

---

include/install.h

This is a left-over from cc86459f ("src/install: remove network mode") that removed the network mode back in 2019.

include/install.h: remove left-over do_install_network() prototype

---

docs/reference.rst
include/config_file.h
src/config_file.c
src/mark.c
test/conftest.py
test/test_mark.py

This PR aims to implement an option that automatically marks all _other_ slots as bad when the booted one is marked as good. This can be used to ensure not booting into the previous used slot after installing a new rootfs. The option is called "prevent-fallback" and can be set in the _system_ section.
For example:
``` ini
[system]
compatible=My BSP
bootloader=barebox
bundle-formats=-plain
data-directory=/data/rauc
prevent-late-fallback=true
....
```
The main logic for this patch is mostly based on the underlying "mark-bad other" command.
In order to make the prevent-fallback option to work for more than two slots, I have reworked the _get_slot_by_identifier_ function to be able to return more than one slot.
For the test case I decided to only test the "mark-bad other" command as the …

Add option to prevent fallback

---

src/mount.c

According to the `mount()` syscall manpage, `ENODEV` means "filesystemtype not configured in the kernel."
Since we know our file system, we can directly inform the user about the missing 'squashfs' support in kernel.
While at it, also follow the rule of not adding information a caller would know anyway and remove the "failed to mount bundle: " prefix.
So instead of:
> Failed mounting bundle: failed to mount bundle: No such device
we get
> Failed mounting bundle: squashfs support not enabled in kernel

src/mount: provide more helpful error message when squashfs is missing

---

.github/workflows/scan-build.yml

The actions/upload-artifact@v3 action was deprecated.

.github/workflows/scan-build: update to actions/upload-artifact@v4

---

qemu-test
qemu-test-init

Hello,
I have tried to use `qemu-test` to run the whole test suite, and I faced some issues with my host (Arch Linux, sh -> bash, meson 1.6.1).
I have made a change that moves the mark-good before the interactive shell is started, and I am not sure about that one. I do not understand why it runs after the shell and before the tests :thinking: I have probably a misunderstanding of how to use that script.
Also, is there a good way to ensure mark-good runs after the rauc service is started?
Regards

qemu-test: few fixes

---

src/update_handler.c

Use the number of chunks in the source image for tracking installation progress.
Fixes: #1277

src/update_handler: add detailed progress when installing block hash index images

---

test/Dockerfile

This is useful for communicating with the HTTP server from pytest to prepare and analyze advanced tests for streaming.

test/Dockerfile: add python3-requests

---

src/context.c
src/update_handler.c
src/update_utils.c

Moves the skipping of unchanged progress updates into `r_context_set_step_percentage()` instead of handling it individually on each call.

src: simplify unchanged progress update skipping

---

test/conftest.py
test/nginx_backend.py
test/test_http.py

Add some endpoints to the aiohttp-based HTTP server backend so that we can run tests while collecting additional info, such as request headers or ranges.
Also, support this using a class-based fixture and add some basic test cases.

test: improve http tests

---

src/context.c
src/install.c
test/context.c

Since 2928ac06 ("src/main: fix and add support for boot detection with rauc.external"), we consider `"_external_"` in `r_context()->bootslot` as an indicator for an external boot.
While this works well for explicit 'rauc.external' boots, it does not for boots with 'root=/dev/nfs' in the commandline since `r_context()->bootslot` is '/dev/nfs' in this case.
Unify these cases by returning `"_external_"` from `get_cmdline_bootname()` both for the 'rauc.external' as well as the 'root=/dev/nfs' case.
To not loose the info printout for external or nfs, move these to get_cmdline_bootname(), too.
From here on it is now actually safe to use `"_external_"` as an indicator for all kinds of external boots.

src: simplify and fix NFS (external) boot detection

---

test/update_handler.c

This fixes tests for block hash index (with mke2fs 1.47.2).
Fixes:
not ok /update_handler/block_hash_index/ext4_to_raw - rauc:ERROR:../test/update_handler.c:565:test_update_handler: assertion failed (sum_zero >= IMAGE_SIZE/4096 - 29): (2523 >= 2531)
Bail out!
----------------------------------- stderr -----------------------------------
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
The file /tmp/rauc-SPKR12/rootfs-0 does not exist and no size was specified.
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025)
mke2fs 1.47.2 (1-Jan-2025) …

test/update_handler: fix tests for block hash index

---

test/Dockerfile

Since pydbus is no longer maintained, we should switch to the successor project dasbus. To avoid breaking the current test suite, keep pydbus for now.

test/Dockerfile: add python3-dasbus for testing

---

src/artifacts.c
src/manifest.c

With the cast, it would cause a warning:
```
../src/artifacts.c: In function ‘r_artifact_repo_free’: ../src/artifacts.c:85:43: warning: function called through a non-compatible type
85 |         g_clear_pointer(&repo->artifacts, (GDestroyNotify)g_hash_table_destroy);
/usr/include/glib-2.0/glib/gmem.h:136:8: note: in definition of macro ‘g_clear_pointer’
136 |       (destroy) (_ptr);                                  \
|        ^~~~~~~
```
See also https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/269.

avoid GDestroyNotify cast for g_clear_pointer

---

include/bootchooser.h
src/bootchooser.c
src/context.c
test/context.c

This introduces the function r_boot_get_bootname() to retreive the bootname of the current booted slot.

src/context: introduce r_boot_get_current_bootname()

---

src/mount.c

We don't intend to write to the RAUC bundle, so open /dev/loop* readonly.
Mounting readwrite only works when the Kernel option CONFIG_BLK_DEV_WRITE_MOUNTED is enabled. Without this option mounting the bundle fails with -EBUSY.

src/mount: open /dev/loop* readonly

---

src/bundle.c

When encrypting bundles for a large number of recipients, the signature size may exceed the default sanity check size of 64 KiB.
Since RAUC will refuse to install such a bundle by default, the user should be informed during bundle creation already and not surprised in the field.
To give guidance, also note the new 'max-bundle-signature-size' system config option. However, this still has to have been set beforehand on devices in the field.
Use IEC units for printout to let 64*1024 bytes appear more reasonable.

src/bundle: add printout if crated signature size exceeds sanity default

---

include/bundle.h
src/service.c
test/conftest.py

The leak only happens if there actually are access args in the method call dict.

src/service: fix leak of RaucBundleAccessArgs for InspectBundle

---

meson.build

This allows us to use g_ptr_array_copy()/_extend() from 2.62, g_canonicalize_file() from 2.58 and g_warning_once() from 2.64.
Versions newer than 2.64.0 are used by the oldest supported releases of major distributions.
- Debian bullseye: 2.66.8 (EOL: 2026-08-31)
- Ubuntu focal: 2.64.2 (EOL Standard Support: May 2025)
- Yocto kirkstone: 2.72.3 (EOL: April 2026)

require glib version 2.64.0

---

docs/reference.rst
include/manifest.h
meson.build
src/manifest.c
test/test_bundle.py

This gives us an additional way to ensure that bundles are not installed by an incompatible version. In the future, we could also require an explicit minimum version during bundle creation when using new features to make the requirements explicit to the user.

manifest: add a min-rauc-version

---

src/context.c
src/main.c

This fixes issues that occur when `/proc/sys/kernel/random/boot_id` (or procfs) is not present for some reason.

Fix handling for missing boot ID

---

docs/reference.rst
include/install.h
src/install.c
src/main.c
src/service.c
test/test_install.py

Check that the hash of the to be installed bundle's manifest matches the expected value. This can be used to when explicit confirmation is needed before installing a bundle by first reviewing the information returned by InspectBundle and then passing the hash here. If the bundle was replaced by a different (but correctly signed) bundle, this is detected by comparing the manifest hashes.
This is also useful with the upcoming polling support if the user wants to automate the polling only and still trigger the installation explicitly.

add support for requiring a specific manifest hash during installation

---

src/manifest.c
test/test_bundle.py

The main polling configuration is set in the system.conf. In the future, we may want to further delay or restrict polling/installation, e.g. to specific time windows or for phased roll-outs.
By ignoring unknown options in this section until then, it will be easier to use them later as an intermediate update can be avoided.

src/manifest: ignore the rollout section for now

---

test/stats.c

Our minimum glib version is 2.64, thus these are not required anymore.

test/stats: remove compatibility defines for glib < 2.58

---

include/utils.h
src/utils.c
test/utils.c

This will be useful to print the time until the next poll for the upcoming polling support.

utils: add function to format a duration as a human readable string

---

src/nbd.c

It doesn't seem to understand that g_strchomp returns the same pointer, so it thinks that the memory allocated by g_strndup is leaked.

src/nbd: avoid a false positive in coverity

---

docs/integration.rst

The FILESEXTRAPATHS_prepend syntax is no longer valid since honister[1], switch to the new one.
Also change it for IMAGE_INSTALL, and add the missing space after the quote.
[1]: https://docs.yoctoproject.org/migration-guides/migration-3.4.html#override-syntax-changes

docs/integration: change old override syntax in example

---

docs/advanced.rst

With the previous commit the event-log anchor was misplaced.

advanced.rst: fix event-log anchor

---

src/mount.c

There is no need for a `res` variable and gotos in these simple functions.

src/mount: simplify control flow

---

src/install.c

fix segmentation fault caused by checking `converted->len` without ensuring `converted` is valid in `pre_install_check`

src/install: ensure converted pointer is valid before dereferencing

---

src/slot.c

This returns the slot directly and removes the unnecessary goto.

src/slot: remove unnecessary goto

---

src/bootloaders/custom.c

When using `autoptr()` for the inner error, it will be freed when leaving the function context and the propagated error message will be empty.

src/bootloaders/custom: don't auto-free GError r_custom_get_current_bootname()

---

src/context.c
src/signature.c

In the test suite, we sometimes recreate the context, which caused
multiple initialization of the network and signature dependencies. With
OpenSSL 3.5, this leads to purpose ID collisions, as we try to add the
same purpose multiple times.
Avoid this by remembering if the have initialized our dependencies
already.
Also handle possible gaps in the number space for OpenSSL 3.5.
Fixes: 295fa3a ("src/context.c: fully free context in r_context_clean()")

fix OpenSSL 3.5 compatibility

---

meson.build
meson_options.txt
src/signature.c

Adding -DDISABLE_OPENSSL_ENGINE will disable engine support and remove openssl-devel-engine dependency on Fedora.
OpenSSL engine support will also be removed in 4.0 in favour of providers API.
I have tested an earlier version of the patch in Fedora Copr RPM build.
https://copr.fedorainfracloud.org/coprs/bax/rauc/build/8859137/
Fixes: #1688

meson: add support for building without OpenSSL engine support

---

src/nbd.c

When rauc is streaming a bundle during an installation operation, it creates a sub-process, and switches the user of this subprocess, to create e sandbox environment where this user have access only to the required resources in the system.
Until now, when this subprocess received the UID and GID of the streaming user, however, the groups of this user were not set accordingly.
This can cause problems when resources needed for the installation (e.g., installation keys) are available only through group permissions of the sandbox user.
This commit adds relevant logic to the child preparation and setup functions, where the code finds out which groups the user is a part of and sets them accordingly.
Setting the groups of the process must happen before changing the UID of the process, otherwise, …

src/nbd:set groups of child process

---

test/install.c

There is no other caller of `r_quit`, so just fold it into `install_cleanup`.

test/install: simplify install_cleanup

---

src/update_handler.c

This PR improves the robustness of clear_slot() by addressing a potential memory leak when G_IO_ERROR_NO_SPACE occurs
- Added explicit g_clear_error() when the error is expected and recoverable.
Using `ioctl(fd, BLKDISCARD)` to discard blocks rather than zero-write may be more efficient for flash-based block devices?

src/update_handler: fix memory leak on G_IO_ERROR_NO_SPACE in clear_slot()

---

docs/examples.rst

Prior to this patch if the A side failed to boot the B side would never have been tried.
This is because default=0 is used as a sentinel value, while in fact it is also the case where the A side is selected
I think this happened when someone took the grub.conf from the repo [0] and tried to remove the rescue menuentry. If the rescue menuentry is present using default=0 as a sentinel value works, as it will never be selected unless both sides are broken.
[0]: https://github.com/rauc/rauc/blob/master/contrib/grub.conf

docs/examples: fix grub.cfg example

---

LICENSES/CC0-1.0.txt
src/de.pengutronix.rauc.Installer.xml

While we initially intended this file to be freely reusable, as we
considered it not to be copyrightable, it seems that opinions differ and
not having an explicit licenses causes friction.
To clarify and simplify the situation, we use the CC0-1.0 to declare
that it can be used without restrictions.
Fixes: #1713
Reported-by: Bruno Thomsen <bruno.thomsen@gmail.com>

de.pengutronix.rauc.Installer.xml: add and use CC0-1.0 license

---

docs/reference.rst
src/config_file.c
src/main.c
src/update_handler.c
test/config_file.c

* Adds missing bootloader update option bits to reference.rst
* size check for eMMC bootloader updates
* better error handling or `boot-emmc` device misconfiguration
* more clear error printout for `write-slot`

Error handling and usability improvements around (eMMC) bootloader updates

---

src/install.c

Enhance the log messages during RAUC Bundle installation to provide more clarity on the process:
- For non-bootable, indicate that the slot is being marked as bad by calling r_mark_bad. For example:
```
Jun 16 14:58:12 raspberrypi5 rauc[925]: Marking target slot rootfs.1 as non-bootable (bad)...
Jun 16 14:58:12 raspberrypi5 rauc[925]: Marked slot rootfs.1 as bad
```
- For bootable, clarify that r_mark_active is being executed to mark the slot as active and to make it primary. For example:
```
Jun 16 14:58:49 raspberrypi5 rauc[925]: Marking target slot rootfs.1 as bootable (active and primary)...
Jun 16 14:58:49 raspberrypi5 rauc[925]: installing http://XXX.XXX.X.XXX:8000/update-bundle-raspberrypi5.raucb: All slots updated
Jun 16 14:58:49 raspberrypi5 rauc[925]: Marked slot rootfs.1 as …
```

src/install.c: Add details to the log messages

---

src/update_handler.c

With the change made in 705c9e5d ("src/update_handler: replace some gotos by immediate return"), there are now paths that may leave 'part_slot' NULL (and it's also always dereferenced before).
Thus, we can safely remove the check after the goto.
Fixes inconsistency reported by coverity:
> CID 1611650: (#1 of 1): Dereference before null check (REVERSE_INULL)
> check_after_deref: Null-checking part_slot suggests that it may be null, but it has already been dereferenced on all paths leading to the check

src/update_handler: remove NULL check after dereferencing part_slot

---

docs/reference.rst

Document all options handled by `key_file_consume_binary_suffixed_string()`, explicitly specifying the supported value formats.

docs/reference: more explicit documentation for binary suffixed strings

---

docs/faq.rst
docs/reference.rst
include/slot.h
src/config_file.c
src/update_handler.c
test/test_write_slot.py

For special cases, where e.g. the manufacturer decided to store data at the end of the boot partition and where this information is required and cannot be migrated, we allow specifying a `size-limit` option for the `boot-emmc` slot type that allows limiting the cleared/written size.
Fixes: #780

add new 'size-limit' option for type 'boot-emmc'

---

test/Dockerfile

With the upcoming multisig support, we'll need to inspect CMS signatures in the pytest testsuite. Instead of trying to parse the 'openssl cms' text output or using the currently unmaintained asn1crypto module, use pyasn1 for the low-level parsing, so that we can build some convenience layer on top.

test/Dockerfile: add python3-pyasn1 for testing

---

qemu-test-init
src/update_handler.c

Next to fixing a minor bug and improving manual testing of eMMC boot partition handling, this removes some unnecessary code duplication and prepares for a broader use of the eMMC update handling.

eMMC Update Handler Refactoring

---

include/context.h
include/hash_index.h
qemu-test-init
qemu-test-rauc-config
src/context.c
src/hash_index.c
src/update_handler.c
test/hash_index.c
test/progress.c
test/update_handler.c

Depending on the CPU and storage speed, generating the hash index for the adaptive mode 'block-hash-index' might take a notable amount of time.
So far, we don't emit any progress information during these steps, which could give the impression that the installation progress stalls.
With this approach, we reserve 10% of the step progress for both the 'target_slot' and the 'active_slot' generation and increment the progress evenly while generating the hash index.
Also, add some testing adaptations and improvements related to this feature.

Add progress handling during hash index generation for adaptive mode 'block-hash-index'

---

.github/workflows/tests.yml

These log file locations are no longer valid, so remove them.

.github/workflows/tests: don't try to print old logfile locations

---

src/config_file.c

Use `g_clear_pointer()` instead of simply assigning `NULL` when the 'variant-name' key is not found.
While the memory leak prevention is more theoretical, it keeps cleanup logic consistent (we already do so for 'variant-file') and also silences the following codecov-reported defect:
```
| 560     	if (g_error_matches(ierror, G_KEY_FILE_ERROR, G_KEY_FILE_ERROR_KEY_NOT_FOUND)) {
| >>>     CID 1619518:         Resource leaks  (RESOURCE_LEAK)
| >>>     Overwriting "variant_data" in "variant_data = NULL" leaks the storage that "variant_data" points to.
| 561     		variant_data = NULL;
```

src/config_file: clear 'variant_data' more consistently

---

qemu-test-init

If the meson call fails early, it does not produce a new log. However, if a previous run already created a log file, this will be shown instead. This might be confusing..
Thus, better remove the old log file before generating a new one.

qemu-test-init: wipe old logs to avoid confusion

---

.mailmap

This makes`git shortlog` work correctly.

.mailmap: add mailmap to unifiy naming
